// GameCore.Rules.Gameplay.Player - pure transitions of the player's authoritative state (P1.3, catalog row 3).
//
// The player's state is int32 slots owned by the player plugin (player.posX/Y/Z mm, player.yaw mrad, player.stamina,
// player.focus, plus the bookkeeping slots player.regionKey and player.regenDelayMs). A move command carries the
// displacement the presentation's collision resolver produced for this step; the rules clamp it to what the tuning
// allows (walk or run speed over the move window), charge or regenerate stamina, and pay for a jump. Nothing here
// depends on frame time: the same commands from the same state give the same slots, which is what replay relies on.
#nullable enable
namespace GameCore.Rules.Gameplay.Player
{
    /// <summary>Integer tuning of one player (converted once from the authored PlayerDefinition).</summary>
    public readonly struct PlayerTuning
    {
        public PlayerTuning(
            int walkMillimetresPerSecond,
            int runMillimetresPerSecond,
            int stepMilliseconds,
            int moveWindowMilliseconds,
            int maxVerticalMillimetresPerStep,
            int staminaMax,
            int staminaDrainPerSecond,
            int staminaRegenPerSecond,
            int staminaRegenDelayMilliseconds,
            int jumpCost)
        {
            WalkMillimetresPerSecond = walkMillimetresPerSecond < 0 ? 0 : walkMillimetresPerSecond;
            RunMillimetresPerSecond = runMillimetresPerSecond < WalkMillimetresPerSecond ? WalkMillimetresPerSecond : runMillimetresPerSecond;
            StepMilliseconds = stepMilliseconds < 1 ? 1 : stepMilliseconds;
            MoveWindowMilliseconds = moveWindowMilliseconds < StepMilliseconds ? StepMilliseconds : moveWindowMilliseconds;
            MaxVerticalMillimetresPerStep = maxVerticalMillimetresPerStep < 0 ? 0 : maxVerticalMillimetresPerStep;
            StaminaMax = staminaMax < 1 ? 1 : staminaMax;
            StaminaDrainPerSecond = staminaDrainPerSecond < 0 ? 0 : staminaDrainPerSecond;
            StaminaRegenPerSecond = staminaRegenPerSecond < 0 ? 0 : staminaRegenPerSecond;
            StaminaRegenDelayMilliseconds = staminaRegenDelayMilliseconds < 0 ? 0 : staminaRegenDelayMilliseconds;
            JumpCost = jumpCost < 0 ? 0 : jumpCost;
        }

        public int WalkMillimetresPerSecond { get; }

        public int RunMillimetresPerSecond { get; }

        /// <summary>The logical duration of one step (stamina accounting).</summary>
        public int StepMilliseconds { get; }

        /// <summary>
        /// The longest frame a single move may cover: a move is clamped to speed x this window, so a slow rendered frame
        /// does not lose distance while a forged command cannot teleport.
        /// </summary>
        public int MoveWindowMilliseconds { get; }

        public int MaxVerticalMillimetresPerStep { get; }

        public int StaminaMax { get; }

        public int StaminaDrainPerSecond { get; }

        public int StaminaRegenPerSecond { get; }

        public int StaminaRegenDelayMilliseconds { get; }

        public int JumpCost { get; }

        /// <summary>Stamina drained by one running step (at least 1 when draining is on).</summary>
        public int DrainPerStep => PerStep(StaminaDrainPerSecond);

        /// <summary>Stamina regenerated by one resting step (at least 1 when regeneration is on).</summary>
        public int RegenPerStep => PerStep(StaminaRegenPerSecond);

        /// <summary>The longest horizontal move of one step at walking or running speed.</summary>
        public int MoveLimit(bool running) =>
            PlanarMath.Travel(running ? RunMillimetresPerSecond : WalkMillimetresPerSecond, MoveWindowMilliseconds);

        /// <summary>Defaults: walk 2.5 m/s, run 5.5 m/s, 20 ms steps, 100 ms window, 0.4 m vertical, stamina 1000.</summary>
        public static PlayerTuning Default => new PlayerTuning(2500, 5500, 20, 100, 400, 1000, 200, 150, 800, 150);

        private int PerStep(int perSecond)
        {
            if (perSecond <= 0)
            {
                return 0;
            }

            long value = (long)perSecond * StepMilliseconds / 1000L;
            return value < 1L ? 1 : (int)value;
        }
    }

    /// <summary>The player's authoritative slots.</summary>
    public readonly struct PlayerState
    {
        public PlayerState(int posX, int posY, int posZ, int yaw, int stamina, int focus, int regionKey, int regenDelayMilliseconds)
        {
            PosX = posX;
            PosY = posY;
            PosZ = posZ;
            Yaw = yaw;
            Stamina = stamina;
            Focus = focus;
            RegionKey = regionKey;
            RegenDelayMilliseconds = regenDelayMilliseconds;
        }

        public int PosX { get; }

        public int PosY { get; }

        public int PosZ { get; }

        /// <summary>Heading in milliradians, [0, 6283).</summary>
        public int Yaw { get; }

        public int Stamina { get; }

        /// <summary>Stable key of the focused interactable or NPC, or <see cref="PlayerRules.NoFocus"/>.</summary>
        public int Focus { get; }

        /// <summary>Region key the pose belongs to (mirrors world.region; a change means a travel was committed).</summary>
        public int RegionKey { get; }

        public int RegenDelayMilliseconds { get; }

        public bool HasFocus => Focus != PlayerRules.NoFocus;

        public PlayerState WithPose(int x, int y, int z, int yaw) => new PlayerState(x, y, z, yaw, Stamina, Focus, RegionKey, RegenDelayMilliseconds);

        public PlayerState WithStamina(int stamina, int regenDelay) => new PlayerState(PosX, PosY, PosZ, Yaw, stamina, Focus, RegionKey, regenDelay);

        public PlayerState WithFocus(int focus) => new PlayerState(PosX, PosY, PosZ, Yaw, Stamina, focus, RegionKey, RegenDelayMilliseconds);

        public PlayerState WithRegion(int regionKey) => new PlayerState(PosX, PosY, PosZ, Yaw, Stamina, Focus, regionKey, RegenDelayMilliseconds);

        public override string ToString() =>
            "player(pos=" + PosX + "," + PosY + "," + PosZ + " yaw=" + Yaw + " stamina=" + Stamina + " focus=" + Focus
            + " region=" + RegionKey + ")";
    }

    /// <summary>One sampled move: the step's displacement (mm), the facing (mrad) and the run/jump flags.</summary>
    public readonly struct PlayerMove
    {
        public PlayerMove(int dx, int dy, int dz, int yaw, bool run, bool jump)
        {
            Dx = dx;
            Dy = dy;
            Dz = dz;
            Yaw = yaw;
            Run = run;
            Jump = jump;
            ExtraFlags = 0;
        }

        private PlayerMove(int dx, int dy, int dz, int yaw, int flags)
        {
            Dx = dx;
            Dy = dy;
            Dz = dz;
            Yaw = yaw;
            Run = (flags & PlayerRules.RunFlag) != 0;
            Jump = (flags & PlayerRules.JumpFlag) != 0;
            ExtraFlags = flags & ~PlayerRules.KnownFlags;
        }

        public int Dx { get; }

        public int Dy { get; }

        public int Dz { get; }

        public int Yaw { get; }

        public bool Run { get; }

        public bool Jump { get; }

        /// <summary>Flag bits the rules do not know (a newer writer); a move carrying any is refused.</summary>
        public int ExtraFlags { get; }

        /// <summary>Flag bits as carried in the command payload.</summary>
        public int Flags => (Run ? PlayerRules.RunFlag : 0) | (Jump ? PlayerRules.JumpFlag : 0) | ExtraFlags;

        public static PlayerMove FromFlags(int dx, int dy, int dz, int yaw, int flags) => new PlayerMove(dx, dy, dz, yaw, flags);
    }

    /// <summary>Why a player command was refused (moves are clamped, not refused, unless malformed).</summary>
    public enum PlayerRefusal
    {
        None = 0,
        InvalidFocus = 1,
        FocusUnchanged = 2,
        NoFocus = 3,
        UnknownFlags = 4,
    }

    /// <summary>Stable refusal codes of the player rules.</summary>
    public static class PlayerRefusals
    {
        public const string InvalidFocus = "player.invalid-focus";
        public const string FocusUnchanged = "player.focus-unchanged";
        public const string NoFocus = "player.no-focus";
        public const string UnknownFlags = "player.unknown-flags";

        public static string Code(PlayerRefusal refusal)
        {
            switch (refusal)
            {
                case PlayerRefusal.InvalidFocus: return InvalidFocus;
                case PlayerRefusal.FocusUnchanged: return FocusUnchanged;
                case PlayerRefusal.NoFocus: return NoFocus;
                case PlayerRefusal.UnknownFlags: return UnknownFlags;
                default: return string.Empty;
            }
        }
    }

    /// <summary>The outcome of one move.</summary>
    public readonly struct PlayerMoveResult
    {
        public PlayerMoveResult(PlayerState state, PlayerRefusal refusal, bool clamped, bool ran, bool jumped, bool jumpRefused)
        {
            State = state;
            Refusal = refusal;
            Clamped = clamped;
            Ran = ran;
            Jumped = jumped;
            JumpRefused = jumpRefused;
        }

        public PlayerState State { get; }

        public PlayerRefusal Refusal { get; }

        public bool Accepted => Refusal == PlayerRefusal.None;

        /// <summary>The displacement was longer than the tuning allows and was shortened.</summary>
        public bool Clamped { get; }

        public bool Ran { get; }

        public bool Jumped { get; }

        /// <summary>A jump was asked for without the stamina to pay for it; upward motion was dropped.</summary>
        public bool JumpRefused { get; }
    }

    /// <summary>The outcome of a focus or interact command.</summary>
    public readonly struct PlayerTransition
    {
        private PlayerTransition(PlayerRefusal refusal, PlayerState state)
        {
            Refusal = refusal;
            State = state;
        }

        public PlayerRefusal Refusal { get; }

        public PlayerState State { get; }

        public bool Accepted => Refusal == PlayerRefusal.None;

        public static PlayerTransition Accept(PlayerState state) => new PlayerTransition(PlayerRefusal.None, state);

        public static PlayerTransition Refuse(PlayerRefusal refusal, PlayerState state) => new PlayerTransition(refusal, state);
    }

    /// <summary>Pure transitions of the player.</summary>
    public static class PlayerRules
    {
        public const int NoFocus = -1;

        public const int RunFlag = 1;

        public const int JumpFlag = 2;

        public const int KnownFlags = RunFlag | JumpFlag;

        /// <summary>Displacements shorter than this (mm) count as standing still for stamina.</summary>
        public const int StillThreshold = 1;

        /// <summary>The state of a player placed at a pose with full stamina and no focus.</summary>
        public static PlayerState Spawned(int x, int y, int z, int yaw, int regionKey, PlayerTuning tuning) =>
            new PlayerState(x, y, z, PlanarMath.NormalizeYaw(yaw), tuning.StaminaMax, NoFocus, regionKey, 0);

        /// <summary>
        /// Applies one sampled move: clamps the displacement, drains stamina while running, pays for a jump, regenerates
        /// stamina after the regeneration delay, and turns the player to the move's facing.
        /// </summary>
        public static PlayerMoveResult Move(PlayerState state, PlayerMove move, PlayerTuning tuning)
        {
            if (move.ExtraFlags != 0)
            {
                return new PlayerMoveResult(state, PlayerRefusal.UnknownFlags, false, false, false, false);
            }

            int dx = move.Dx;
            int dz = move.Dz;
            bool canRun = move.Run && state.Stamina > 0;
            bool clamped = PlanarMath.ClampLength(ref dx, ref dz, tuning.MoveLimit(canRun));
            int dy = move.Dy;
            int maxVertical = tuning.MaxVerticalMillimetresPerStep;
            if (dy > maxVertical)
            {
                dy = maxVertical;
                clamped = true;
            }
            else if (dy < -maxVertical)
            {
                dy = -maxVertical;
                clamped = true;
            }

            bool moving = PlanarMath.Distance(dx, dz) >= StillThreshold;
            bool ran = canRun && moving;
            int stamina = state.Stamina;
            int regenDelay = state.RegenDelayMilliseconds;
            bool jumped = false;
            bool jumpRefused = false;

            if (move.Jump)
            {
                if (stamina >= tuning.JumpCost)
                {
                    stamina -= tuning.JumpCost;
                    jumped = true;
                    regenDelay = tuning.StaminaRegenDelayMilliseconds;
                }
                else
                {
                    jumpRefused = true;
                    if (dy > 0)
                    {
                        dy = 0;
                    }
                }
            }

            if (ran)
            {
                stamina -= tuning.DrainPerStep;
                regenDelay = tuning.StaminaRegenDelayMilliseconds;
            }
            else if (!jumped)
            {
                if (regenDelay > 0)
                {
                    regenDelay -= tuning.StepMilliseconds;
                    if (regenDelay < 0)
                    {
                        regenDelay = 0;
                    }
                }
                else
                {
                    stamina += tuning.RegenPerStep;
                }
            }

            stamina = ClampStamina(stamina, tuning);
            PlayerState next = state
                .WithPose(PlanarMath.Add(state.PosX, dx), PlanarMath.Add(state.PosY, dy), PlanarMath.Add(state.PosZ, dz), PlanarMath.NormalizeYaw(move.Yaw))
                .WithStamina(stamina, regenDelay);
            return new PlayerMoveResult(next, PlayerRefusal.None, clamped, ran, jumped, jumpRefused);
        }

        /// <summary>
        /// Adopts a pose written by the world (portal travel arrival or a world.place): the region key and pose are
        /// replaced and stamina is kept; focus is cleared because the candidates belong to the old surroundings.
        /// </summary>
        public static PlayerState Adopt(PlayerState state, int regionKey, int x, int y, int z, int yaw) =>
            state.WithPose(x, y, z, PlanarMath.NormalizeYaw(yaw)).WithRegion(regionKey).WithFocus(NoFocus);

        /// <summary>Sets the focused key (a positive stable key or <see cref="NoFocus"/>).</summary>
        public static PlayerTransition SetFocus(PlayerState state, int key)
        {
            if (key != NoFocus && key <= 0)
            {
                return PlayerTransition.Refuse(PlayerRefusal.InvalidFocus, state);
            }

            if (state.Focus == key)
            {
                return PlayerTransition.Refuse(PlayerRefusal.FocusUnchanged, state);
            }

            return PlayerTransition.Accept(state.WithFocus(key));
        }

        /// <summary>An interact request needs a focus; the state is unchanged.</summary>
        public static PlayerTransition Interact(PlayerState state) =>
            state.HasFocus ? PlayerTransition.Accept(state) : PlayerTransition.Refuse(PlayerRefusal.NoFocus, state);

        /// <summary>Stamina clamped to [0, max].</summary>
        public static int ClampStamina(int stamina, PlayerTuning tuning) =>
            stamina < 0 ? 0 : (stamina > tuning.StaminaMax ? tuning.StaminaMax : stamina);

        /// <summary>Stamina as thousandths of the maximum (for HUD bars).</summary>
        public static int StaminaMilli(PlayerState state, PlayerTuning tuning) =>
            (int)((long)ClampStamina(state.Stamina, tuning) * 1000L / tuning.StaminaMax);
    }
}
