// <auto-generated />
// Generated by tools/emit_catalog_reachability.py; do not edit by hand.
//
// Catalog reachability manifest (GC-025, 04 section 8, P-058). Every registration group entry, every
// declared schema's generated serializer and every closed-generic root statement of every committed
// catalog, with the derived key and stable name each belongs to. `-probeCatalogCoverage` compares its live
// generated tables against this list and reports the exact missing root, so a root that only the Editor
// keeps alive fails the player instead of passing it silently.
#nullable enable
using System;

namespace GameCore.Validation.ProbeHost
{
    /// <summary>Generative category of one manifest root; the same names <c>FactoryKind</c> uses (P-009).</summary>
    public enum CatalogReachabilityKind
    {
        /// <summary>Generated registration kind <c>PluginFactory</c>.</summary>
        PluginFactory = 0,
        /// <summary>Generated registration kind <c>SystemFactory</c>.</summary>
        SystemFactory = 1,
        /// <summary>Generated registration kind <c>Reducer</c>.</summary>
        Reducer = 2,
        /// <summary>Generated registration kind <c>StaticPredicate</c>.</summary>
        StaticPredicate = 3,
        /// <summary>Generated registration kind <c>Serializer</c>.</summary>
        Serializer = 4,
        /// <summary>Generated registration kind <c>Migration</c>.</summary>
        Migration = 5,
        /// <summary>Generated registration kind <c>ResourceFactory</c>.</summary>
        ResourceFactory = 6,
        /// <summary>Generated registration kind <c>LayoutApply</c>.</summary>
        LayoutApply = 7,
        /// <summary>Generated registration kind <c>SchemaFactory</c>.</summary>
        SchemaFactory = 8,
        /// <summary>Generated registration kind <c>StatePolicy</c>.</summary>
        StatePolicy = 9,
        /// <summary>Generated registration kind <c>Handler</c>.</summary>
        Handler = 10,

        /// <summary>A closed-generic root statement: not a <c>FactoryKind</c>, the manifest's own category.</summary>
        ClosedGenericRoot = 11,
    }

    /// <summary>Why one manifest root is mandatory: a registration, a schema's serializer, or a root statement.</summary>
    public enum CatalogReachabilityRole
    {
        /// <summary>A generated registration table entry resolved through the table's lookup method.</summary>
        Registration = 0,

        /// <summary>A declared schema's generated serializer, resolved from the serializer table.</summary>
        Serializer = 1,

        /// <summary>A generated closed-generic root statement executed through the root method.</summary>
        ClosedGenericRoot = 2,
    }

    /// <summary>One mandatory reachability root of one catalog.</summary>
    public readonly struct CatalogReachabilityRoot
    {
        /// <summary>Builds one manifest row.</summary>
        public CatalogReachabilityRoot(
            string catalog,
            string group,
            CatalogReachabilityKind kind,
            CatalogReachabilityRole role,
            string stableName,
            string keyName,
            ulong keyHigh,
            ulong keyLow,
            uint keyVersion)
        {
            Catalog = catalog;
            Group = group;
            Kind = kind;
            Role = role;
            StableName = stableName;
            KeyName = keyName;
            KeyHigh = keyHigh;
            KeyLow = keyLow;
            KeyVersion = keyVersion;
        }

        /// <summary>Manifest label of the catalog this root belongs to.</summary>
        public string Catalog { get; }

        /// <summary>Generated registration table, or the schema-registration table for a serializer root.</summary>
        public string Group { get; }

        /// <summary>Generated registration kind; <c>ClosedGenericRoot</c> for a root statement.</summary>
        public CatalogReachabilityKind Kind { get; }

        /// <summary>Why this root is mandatory.</summary>
        public CatalogReachabilityRole Role { get; }

        /// <summary>Stable name the entry's key is derived from (P-004).</summary>
        public string StableName { get; }

        /// <summary>Name of the generated key constant in the catalog class.</summary>
        public string KeyName { get; }

        /// <summary>High word of the derived 128-bit registration key.</summary>
        public ulong KeyHigh { get; }

        /// <summary>Low word of the derived 128-bit registration key.</summary>
        public ulong KeyLow { get; }

        /// <summary>Key version the registration carries.</summary>
        public uint KeyVersion { get; }

    }

    /// <summary>One catalog's reachability summary.</summary>
    public readonly struct CatalogReachabilityCatalog
    {
        /// <summary>Builds one catalog summary.</summary>
        public CatalogReachabilityCatalog(
            string label,
            string className,
            string coverageClassName,
            string catalogFileHash,
            string catalogFingerprint,
            int registrationGroupCount,
            int schemaCount,
            int registrationCount,
            int closedGenericRootCount)
        {
            Label = label;
            ClassName = className;
            CoverageClassName = coverageClassName;
            CatalogFileHash = catalogFileHash;
            CatalogFingerprint = catalogFingerprint;
            RegistrationGroupCount = registrationGroupCount;
            SchemaCount = schemaCount;
            RegistrationCount = registrationCount;
            ClosedGenericRootCount = closedGenericRootCount;
        }

        /// <summary>Manifest label, unique within this manifest.</summary>
        public string Label { get; }

        /// <summary>Generated catalog class name, for diagnostics.</summary>
        public string ClassName { get; }

        /// <summary>Generated coverage companion class name, for diagnostics.</summary>
        public string CoverageClassName { get; }

        /// <summary>Recorded file-prefix hash of the committed generated catalog.</summary>
        public string CatalogFileHash { get; }

        /// <summary>Recorded canonical fingerprint of the committed generated catalog (P-028).</summary>
        public string CatalogFingerprint { get; }

        /// <summary>Registration groups the catalog declares.</summary>
        public int RegistrationGroupCount { get; }

        /// <summary>Schemas the catalog declares.</summary>
        public int SchemaCount { get; }

        /// <summary>Registration entries across every group.</summary>
        public int RegistrationCount { get; }

        /// <summary>Closed-generic root statements the catalog emits.</summary>
        public int ClosedGenericRootCount { get; }
    }

    /// <summary>
    /// The committed catalog reachability manifest. Every row is mandatory: the player resolves it through
    /// the generated lookup method and reports the missing key when a build dropped it.
    /// </summary>
    public static class CatalogReachability
    {
        /// <summary>Manifest format, so a reader can reject a shape it does not know.</summary>
        public const string Format = "gamecore.catalog-reachability/1";

        /// <summary>Every committed catalog this manifest covers, in declaration order.</summary>
        public static readonly CatalogReachabilityCatalog[] Catalogs =
        {
            new CatalogReachabilityCatalog(
                "probe",
                "ProbeCatalog",
                "ProbeCatalogCoverage",
                "03bdcd23fd8ec0515d93d7c54d7f7c695f3860a850a7280b82316aaacd14c5c1",
                "02bb94ab81353a2063fb1cb92d77ce3b9889885b02a95de515193e45178f37ff",
                3,
                1,
                3,
                2),
            new CatalogReachabilityCatalog(
                "cards",
                "CardCatalog",
                "CardCatalogCoverage",
                "75a60968c3c59ac69e0c2b6b806c792f48e5b243a526b1ae29c7615e8c1a2e9e",
                "77838f4766f9086a0fa32b4fb30d8d5fceeb3a8072e61594fa2177946ad3315d",
                5,
                1,
                8,
                0),
            new CatalogReachabilityCatalog(
                "checkpoint",
                "CheckpointCatalog",
                "CheckpointCatalogCoverage",
                "08d43a031cd41a968daf1ea86633fc826956ae64a8a717e6d999d77e5cd5d2d9",
                "2d931c984b3bcf3f995a0f88bc82708b0d07e4395fcad44019ebc033126a0eb5",
                0,
                13,
                0,
                0),
            new CatalogReachabilityCatalog(
                "traversal",
                "TraversalCatalog",
                "TraversalCatalogCoverage",
                "3332a5e54f1e5beea869200672f423b0089c6ec2fb4991334090ab797c0a1f8c",
                "f66d97d489bc1d8b891b20bc1c16186e0843d2ca5760dcd010909feea6829459",
                4,
                1,
                8,
                0),
        };

        /// <summary>Every mandatory registration root of every covered catalog.</summary>
        public static readonly CatalogReachabilityRoot[] Registrations =
        {
            new CatalogReachabilityRoot(
                "probe",
                "FamilyEntryRegistrations",
                CatalogReachabilityKind.PluginFactory,
                CatalogReachabilityRole.Registration,
                "gamecore.validation.entry.narrative",
                "NarrativeFamilyEntryKey",
                0x81C6EE94C5A5EA51UL,
                0xE32CE40F411F56CDUL,
                1U),
            new CatalogReachabilityRoot(
                "probe",
                "HandlerRegistrations",
                CatalogReachabilityKind.Handler,
                CatalogReachabilityRole.Registration,
                "gamecore.validation.handler.magnitude",
                "ClosedGenericHandlerKey",
                0x1C9A1F368FDAD8DDUL,
                0x4E0CC4C0E9F7DA67UL,
                1U),
            new CatalogReachabilityRoot(
                "probe",
                "PluginRegistrations",
                CatalogReachabilityKind.PluginFactory,
                CatalogReachabilityRole.Registration,
                "gamecore.validation.plugin.fixture",
                "FixturePluginKey",
                0x0284B6EC6D41B5AAUL,
                0xD17744CF859C74B6UL,
                1U),
            new CatalogReachabilityRoot(
                "cards",
                "FamilyEntryRegistrations",
                CatalogReachabilityKind.PluginFactory,
                CatalogReachabilityRole.Registration,
                "gamecore.validation.entry.cards",
                "CardFamilyEntryKey",
                0x6924A730DAE9ADD6UL,
                0xDE4FC185BD76C778UL,
                1U),
            new CatalogReachabilityRoot(
                "cards",
                "PluginRegistrations",
                CatalogReachabilityKind.PluginFactory,
                CatalogReachabilityRole.Registration,
                "cards.factory.card-table-plugin",
                "CardTablePluginKey",
                0xBB026AC0599E6783UL,
                0x83F12FFCA82E5B2BUL,
                1U),
            new CatalogReachabilityRoot(
                "cards",
                "ReducerRegistrations",
                CatalogReachabilityKind.Reducer,
                CatalogReachabilityRole.Registration,
                "cards.reducer.int32-sum",
                "CardSetBonusReducerKey",
                0xF85B12F56C1232B2UL,
                0x70108056ACB54B19UL,
                1U),
            new CatalogReachabilityRoot(
                "cards",
                "StaticPredicateRegistrations",
                CatalogReachabilityKind.StaticPredicate,
                CatalogReachabilityRole.Registration,
                "cards.predicate.always",
                "CardAlwaysPredicateKey",
                0xD8CABB8F16C64380UL,
                0x102DE6820045DF34UL,
                1U),
            new CatalogReachabilityRoot(
                "cards",
                "SystemFactoryRegistrations",
                CatalogReachabilityKind.SystemFactory,
                CatalogReachabilityRole.Registration,
                "cards.system.output",
                "CardOutputSystemKey",
                0x2CB9BBFC9BB6CC94UL,
                0x95666C211E20EE0FUL,
                1U),
            new CatalogReachabilityRoot(
                "cards",
                "SystemFactoryRegistrations",
                CatalogReachabilityKind.SystemFactory,
                CatalogReachabilityRole.Registration,
                "cards.system.input",
                "CardInputSystemKey",
                0x4522EE4E182F61DCUL,
                0xE6E7466B929DEE07UL,
                1U),
            new CatalogReachabilityRoot(
                "cards",
                "SystemFactoryRegistrations",
                CatalogReachabilityKind.SystemFactory,
                CatalogReachabilityRole.Registration,
                "cards.system.commit",
                "CardCommitSystemKey",
                0xA61B22DF091D9AC4UL,
                0xC299AE0D0AE30F30UL,
                1U),
            new CatalogReachabilityRoot(
                "cards",
                "SystemFactoryRegistrations",
                CatalogReachabilityKind.SystemFactory,
                CatalogReachabilityRole.Registration,
                "cards.system.validate",
                "CardValidateSystemKey",
                0xE113F54073E28D83UL,
                0x0803E540BE4EEDFBUL,
                1U),
            new CatalogReachabilityRoot(
                "traversal",
                "PluginRegistrations",
                CatalogReachabilityKind.PluginFactory,
                CatalogReachabilityRole.Registration,
                "traversal.factory.course-plugin",
                "PluginFactoryKey",
                0x6AB4EE28C7914A6DUL,
                0x1C321510AA2A39C2UL,
                1U),
            new CatalogReachabilityRoot(
                "traversal",
                "ReducerRegistrations",
                CatalogReachabilityKind.Reducer,
                CatalogReachabilityRole.Registration,
                "traversal.reducer.vec3i-sum",
                "ReducerKey",
                0xAC39BBF7CC19582FUL,
                0xFF8FDDC39D1DB6D2UL,
                1U),
            new CatalogReachabilityRoot(
                "traversal",
                "StaticPredicateRegistrations",
                CatalogReachabilityKind.StaticPredicate,
                CatalogReachabilityRole.Registration,
                "traversal.predicate.always",
                "PredicateKey",
                0x2FB8E2A0A8F97F28UL,
                0xF73C805A090FAFF2UL,
                1U),
            new CatalogReachabilityRoot(
                "traversal",
                "SystemFactoryRegistrations",
                CatalogReachabilityKind.SystemFactory,
                CatalogReachabilityRole.Registration,
                "traversal.system.integrate",
                "IntegrateSystemKey",
                0x0B710434FE439447UL,
                0x697BF7843E390FDCUL,
                1U),
            new CatalogReachabilityRoot(
                "traversal",
                "SystemFactoryRegistrations",
                CatalogReachabilityKind.SystemFactory,
                CatalogReachabilityRole.Registration,
                "traversal.system.sense",
                "SenseSystemKey",
                0x4B816113044D9926UL,
                0x1E5061764CBC5C0BUL,
                1U),
            new CatalogReachabilityRoot(
                "traversal",
                "SystemFactoryRegistrations",
                CatalogReachabilityKind.SystemFactory,
                CatalogReachabilityRole.Registration,
                "traversal.system.output",
                "OutputSystemKey",
                0xA7B1FB1A30A57005UL,
                0xAB331F36B6F78AE9UL,
                1U),
            new CatalogReachabilityRoot(
                "traversal",
                "SystemFactoryRegistrations",
                CatalogReachabilityKind.SystemFactory,
                CatalogReachabilityRole.Registration,
                "traversal.system.checkpoints",
                "CheckpointSystemKey",
                0xA8D4EA54F8DAFB72UL,
                0x37C88D74316D2478UL,
                1U),
            new CatalogReachabilityRoot(
                "traversal",
                "SystemFactoryRegistrations",
                CatalogReachabilityKind.SystemFactory,
                CatalogReachabilityRole.Registration,
                "traversal.system.input",
                "InputSystemKey",
                0xB893DD85CA45AEE4UL,
                0x77CF897C4154EE95UL,
                1U),
        };

        /// <summary>Every mandatory serializer root contributed by a declared schema.</summary>
        public static readonly CatalogReachabilityRoot[] Serializers =
        {
            new CatalogReachabilityRoot(
                "probe",
                "SchemaRegistrations",
                CatalogReachabilityKind.Serializer,
                CatalogReachabilityRole.Serializer,
                "gamecore.validation.schema.probe-record",
                "ProbeRecordSerializerKey",
                0xB917D6C4A639ECC8UL,
                0xB217BB961E7592D3UL,
                1U),
            new CatalogReachabilityRoot(
                "cards",
                "SchemaRegistrations",
                CatalogReachabilityKind.Serializer,
                CatalogReachabilityRole.Serializer,
                "cards.schema.card-config",
                "CardConfigSerializerKey",
                0x02BB49501222979CUL,
                0xFEA308CE5F5F2CA1UL,
                1U),
            new CatalogReachabilityRoot(
                "checkpoint",
                "SchemaRegistrations",
                CatalogReachabilityKind.Serializer,
                CatalogReachabilityRole.Serializer,
                "gamecore.checkpoint.schema.scope",
                "ScopeRecordSerializerKey",
                0x1BB5C533DAB84E76UL,
                0x04C8B98F1B97066AUL,
                1U),
            new CatalogReachabilityRoot(
                "checkpoint",
                "SchemaRegistrations",
                CatalogReachabilityKind.Serializer,
                CatalogReachabilityRole.Serializer,
                "gamecore.checkpoint.schema.cursor",
                "CursorRecordSerializerKey",
                0x1DDC64B87DAA5363UL,
                0xE1C1951D44AD5F07UL,
                1U),
            new CatalogReachabilityRoot(
                "checkpoint",
                "SchemaRegistrations",
                CatalogReachabilityKind.Serializer,
                CatalogReachabilityRole.Serializer,
                "gamecore.checkpoint.schema.slot",
                "SlotRecordSerializerKey",
                0x325EBFC76F751EE2UL,
                0xC2B4985DF3D088A0UL,
                1U),
            new CatalogReachabilityRoot(
                "checkpoint",
                "SchemaRegistrations",
                CatalogReachabilityKind.Serializer,
                CatalogReachabilityRole.Serializer,
                "gamecore.checkpoint.schema.selection",
                "SelectionRecordSerializerKey",
                0x4736AFCCC12B5B62UL,
                0x5ADB5BCDBB714E3FUL,
                1U),
            new CatalogReachabilityRoot(
                "checkpoint",
                "SchemaRegistrations",
                CatalogReachabilityKind.Serializer,
                CatalogReachabilityRole.Serializer,
                "gamecore.checkpoint.schema.clock",
                "ClockRecordSerializerKey",
                0x49F4779FA88D83EAUL,
                0x0440E2BAB679D545UL,
                1U),
            new CatalogReachabilityRoot(
                "checkpoint",
                "SchemaRegistrations",
                CatalogReachabilityKind.Serializer,
                CatalogReachabilityRole.Serializer,
                "gamecore.checkpoint.schema.grant",
                "GrantRecordSerializerKey",
                0x54D0F9CCCEC243B7UL,
                0x8414EC19245173C6UL,
                1U),
            new CatalogReachabilityRoot(
                "checkpoint",
                "SchemaRegistrations",
                CatalogReachabilityKind.Serializer,
                CatalogReachabilityRole.Serializer,
                "gamecore.checkpoint.schema.install",
                "InstallRecordSerializerKey",
                0x5666C5DB5D34AD37UL,
                0xD470140F8C18808FUL,
                1U),
            new CatalogReachabilityRoot(
                "checkpoint",
                "SchemaRegistrations",
                CatalogReachabilityKind.Serializer,
                CatalogReachabilityRole.Serializer,
                "gamecore.checkpoint.schema.message",
                "MessageRecordSerializerKey",
                0x744D60D006798058UL,
                0xB50B656C613A21F3UL,
                1U),
            new CatalogReachabilityRoot(
                "checkpoint",
                "SchemaRegistrations",
                CatalogReachabilityKind.Serializer,
                CatalogReachabilityRole.Serializer,
                "gamecore.checkpoint.schema.outbox",
                "OutboxRecordSerializerKey",
                0xAC96339BD83D4A4CUL,
                0xA453B3F4E46E4639UL,
                1U),
            new CatalogReachabilityRoot(
                "checkpoint",
                "SchemaRegistrations",
                CatalogReachabilityKind.Serializer,
                CatalogReachabilityRole.Serializer,
                "gamecore.checkpoint.schema.target",
                "TargetRecordSerializerKey",
                0xB780328C6FA158F7UL,
                0xBD88603DB3EBAE2FUL,
                1U),
            new CatalogReachabilityRoot(
                "checkpoint",
                "SchemaRegistrations",
                CatalogReachabilityKind.Serializer,
                CatalogReachabilityRole.Serializer,
                "gamecore.checkpoint.schema.rng",
                "RngRecordSerializerKey",
                0xCD069D4291975928UL,
                0xEDB3F9E9AF5E037DUL,
                1U),
            new CatalogReachabilityRoot(
                "checkpoint",
                "SchemaRegistrations",
                CatalogReachabilityKind.Serializer,
                CatalogReachabilityRole.Serializer,
                "gamecore.checkpoint.schema.header",
                "HeaderRecordSerializerKey",
                0xD578E5FE72E484BEUL,
                0x8D8C015A17D8B66BUL,
                1U),
            new CatalogReachabilityRoot(
                "checkpoint",
                "SchemaRegistrations",
                CatalogReachabilityKind.Serializer,
                CatalogReachabilityRole.Serializer,
                "gamecore.checkpoint.schema.command",
                "CommandRecordSerializerKey",
                0xEFE5AB3007E3F7B8UL,
                0x21D96F9264AB31EFUL,
                1U),
            new CatalogReachabilityRoot(
                "traversal",
                "SchemaRegistrations",
                CatalogReachabilityKind.Serializer,
                CatalogReachabilityRole.Serializer,
                "traversal.schema.course-config",
                "ConfigSerializerKey",
                0xA84CDEF288CAB0B5UL,
                0xDC1283D7CD208E72UL,
                1U),
        };

        /// <summary>Every closed-generic root statement, in catalog and declaration order.</summary>
        public static readonly CatalogReachabilityRoot[] ClosedGenericRoots =
        {
            new CatalogReachabilityRoot(
                "probe",
                "RootClosedGenericInstantiations",
                CatalogReachabilityKind.ClosedGenericRoot,
                CatalogReachabilityRole.ClosedGenericRoot,
                "ProbeAotRoots.TrackJob(default(ProbeAggregateJob<ProbeVector3Value>))",
                string.Empty,
                0UL,
                0UL,
                0U),
            new CatalogReachabilityRoot(
                "probe",
                "RootClosedGenericInstantiations",
                CatalogReachabilityKind.ClosedGenericRoot,
                CatalogReachabilityRole.ClosedGenericRoot,
                "ProbeAotRoots.TrackHandler(HandlerRegistrations[0].Implementation)",
                string.Empty,
                0UL,
                0UL,
                0U),
        };

        /// <summary>Rows of one catalog label; an unknown label yields the count zero with no rows.</summary>
        public static int CountOf(string catalog, CatalogReachabilityRoot[] rows)
        {
            int count = 0;
            for (int i = 0; i < rows.Length; i++)
            {
                if (string.Equals(rows[i].Catalog, catalog, StringComparison.Ordinal))
                {
                    count++;
                }
            }

            return count;
        }
    }
}
