// <auto-generated />
// Generated by GameCore.Content.Compiler catalog tooling; do not edit by hand.
//
// Reachability exercise for TraversalCatalog: it resolves every generated registration through the
// catalog's own generated lookup method, writes and re-reads every declared schema through its generated
// serializer, and calls the generated closed-generic root method when the catalog emits one. It is compiled
// into the same assembly as the catalog, so a stripped registration or serializer fails here in a player build
// instead of only in the Editor (04 section 8, GC-025).
#nullable enable
using System;
using GameCore.Contracts;

namespace GameCore.Validation.GeneratedTraversal
{
    /// <summary>
    /// Generated reachability exercise of <see cref="TraversalCatalog"/>. Every method returns the number of
    /// entries it exercised and reports the first failure in <c>failure</c> instead of throwing, so a player
    /// probe can record the exact missing entry.
    /// </summary>
    public static class TraversalCatalogCoverage
    {
        /// <summary>Number of generated registration entries this exercise resolves by key.</summary>
        public const int RegistrationCount = 8;

        /// <summary>
        /// Resolves every generated registration through the table's own generated lookup method and checks that a
        /// non-null implementation comes back under exactly the key the table declares. A key absent from the
        /// table must return false (P-009).
        /// </summary>
        public static int ExerciseRegistrations(out string failure)
        {
            failure = string.Empty;
            int exercised = 0;

            // PluginRegistrations (PluginFactory, 1 entry)
            for (int i = 0; i < TraversalCatalog.PluginRegistrations.Length; i++)
            {
                FactoryKey key = TraversalCatalog.PluginRegistrations[i].Key;
                if (!TraversalCatalog.TryGetPluginFactory(key, out GameCore.Gameplay.Traversal.ITraversalCoursePluginFactory? implementation) || implementation == null)
                {
                    failure = "PluginRegistrations: the generated lookup returned no implementation for key " + key.ToString();
                    return exercised;
                }

                exercised++;
            }

            // ReducerRegistrations (Reducer, 1 entry)
            for (int i = 0; i < TraversalCatalog.ReducerRegistrations.Length; i++)
            {
                FactoryKey key = TraversalCatalog.ReducerRegistrations[i].Key;
                if (!TraversalCatalog.TryGetReducer(key, out GameCore.Rules.Traversal.ITraversalAccelerationReducer? implementation) || implementation == null)
                {
                    failure = "ReducerRegistrations: the generated lookup returned no implementation for key " + key.ToString();
                    return exercised;
                }

                exercised++;
            }

            // StaticPredicateRegistrations (StaticPredicate, 1 entry)
            for (int i = 0; i < TraversalCatalog.StaticPredicateRegistrations.Length; i++)
            {
                FactoryKey key = TraversalCatalog.StaticPredicateRegistrations[i].Key;
                if (!TraversalCatalog.TryGetStaticPredicate(key, out GameCore.Rules.Traversal.ITraversalTargetPredicate? implementation) || implementation == null)
                {
                    failure = "StaticPredicateRegistrations: the generated lookup returned no implementation for key " + key.ToString();
                    return exercised;
                }

                exercised++;
            }

            // SystemFactoryRegistrations (SystemFactory, 5 entries)
            for (int i = 0; i < TraversalCatalog.SystemFactoryRegistrations.Length; i++)
            {
                FactoryKey key = TraversalCatalog.SystemFactoryRegistrations[i].Key;
                if (!TraversalCatalog.TryGetSystemFactory(key, out GameCore.Gameplay.Traversal.ITraversalSystemFactory? implementation) || implementation == null)
                {
                    failure = "SystemFactoryRegistrations: the generated lookup returned no implementation for key " + key.ToString();
                    return exercised;
                }

                exercised++;
            }

            return exercised;
        }

        /// <summary>
        /// Writes every declared schema through its generated serializer, validates the document, re-reads it
        /// and compares every declared field. A schema whose serializer did not survive stripping fails here
        /// (P-054, 05 section 6).
        /// </summary>
        public static int ExerciseSchemas(out string failure)
        {
            failure = string.Empty;
            int exercised = 0;

            // traversal.schema.course-config (schema a84cdef288cab0b5dc1283d7cd208e72 version 1)
            {
                TraversalCatalog.TraversalConfigSerializer serializer = new TraversalCatalog.TraversalConfigSerializer();
                byte[] written = serializer.Serialize(new TraversalCatalog.TraversalConfigValue(9U));
                if (!serializer.TryValidate(written, out EnvelopeError validateError))
                {
                    failure = "traversal.schema.course-config: the generated document failed validation with " + validateError.ToString();
                    return exercised;
                }

                if (!serializer.TryDeserialize(written, out TraversalCatalog.TraversalConfigValue read, out EnvelopeError readError))
                {
                    failure = "traversal.schema.course-config: the generated serializer failed to re-read its own document with " + readError.ToString();
                    return exercised;
                }

                if (!(read.SchemaVersion == 9U))
                {
                    failure = "traversal.schema.course-config: a declared field did not survive the generated round trip";
                    return exercised;
                }

                exercised++;
            }

            return exercised;
        }

        /// <summary>Number of closed generic instantiations this catalog decides to root.</summary>
        public const int ClosedGenericRootCount = 0;

        /// <summary>
        /// This catalog declares no closed generic instantiation, so there is nothing to execute here. The
        /// method still exists so every generated catalog has one exercise surface (04 section 8).
        /// </summary>
        public static void ExerciseClosedGenericRoots()
        {
        }
    }
}
