// <auto-generated />
// Generated by GameCore.Content.Compiler catalog tooling; do not edit by hand.
//
// Reachability exercise for CardCatalog: it resolves every generated registration through the
// catalog's own generated lookup method, writes and re-reads every declared schema through its generated
// serializer, and calls the generated closed-generic root method when the catalog emits one. It is compiled
// into the same assembly as the catalog, so a stripped registration or serializer fails here in a player build
// instead of only in the Editor (04 section 8, GC-025).
#nullable enable
using System;
using GameCore.Contracts;

namespace GameCore.Validation.GeneratedCards
{
    /// <summary>
    /// Generated reachability exercise of <see cref="CardCatalog"/>. Every method returns the number of
    /// entries it exercised and reports the first failure in <c>failure</c> instead of throwing, so a player
    /// probe can record the exact missing entry.
    /// </summary>
    public static class CardCatalogCoverage
    {
        /// <summary>Number of generated registration entries this exercise resolves by key.</summary>
        public const int RegistrationCount = 8;

        /// <summary>
        /// Resolves every generated registration through the table's own generated lookup method and checks that a
        /// non-null implementation comes back under exactly the key the table declares. A key absent from the
        /// table must return false (P-009).
        /// </summary>
        public static int ExerciseRegistrations(out string failure)
        {
            failure = string.Empty;
            int exercised = 0;

            // FamilyEntryRegistrations (PluginFactory, 1 entry)
            for (int i = 0; i < CardCatalog.FamilyEntryRegistrations.Length; i++)
            {
                FactoryKey key = CardCatalog.FamilyEntryRegistrations[i].Key;
                if (!CardCatalog.TryGetFamilyEntry(key, out GameCore.Validation.Slices.IFamilyPluginEntry? implementation) || implementation == null)
                {
                    failure = "FamilyEntryRegistrations: the generated lookup returned no implementation for key " + key.ToString();
                    return exercised;
                }

                exercised++;
            }

            // PluginRegistrations (PluginFactory, 1 entry)
            for (int i = 0; i < CardCatalog.PluginRegistrations.Length; i++)
            {
                FactoryKey key = CardCatalog.PluginRegistrations[i].Key;
                if (!CardCatalog.TryGetPluginFactory(key, out GameCore.Gameplay.Cards.ICardTablePluginFactory? implementation) || implementation == null)
                {
                    failure = "PluginRegistrations: the generated lookup returned no implementation for key " + key.ToString();
                    return exercised;
                }

                exercised++;
            }

            // ReducerRegistrations (Reducer, 1 entry)
            for (int i = 0; i < CardCatalog.ReducerRegistrations.Length; i++)
            {
                FactoryKey key = CardCatalog.ReducerRegistrations[i].Key;
                if (!CardCatalog.TryGetReducer(key, out GameCore.Rules.Cards.ICardBonusReducer? implementation) || implementation == null)
                {
                    failure = "ReducerRegistrations: the generated lookup returned no implementation for key " + key.ToString();
                    return exercised;
                }

                exercised++;
            }

            // StaticPredicateRegistrations (StaticPredicate, 1 entry)
            for (int i = 0; i < CardCatalog.StaticPredicateRegistrations.Length; i++)
            {
                FactoryKey key = CardCatalog.StaticPredicateRegistrations[i].Key;
                if (!CardCatalog.TryGetStaticPredicate(key, out GameCore.Rules.Cards.ICardTargetPredicate? implementation) || implementation == null)
                {
                    failure = "StaticPredicateRegistrations: the generated lookup returned no implementation for key " + key.ToString();
                    return exercised;
                }

                exercised++;
            }

            // SystemFactoryRegistrations (SystemFactory, 4 entries)
            for (int i = 0; i < CardCatalog.SystemFactoryRegistrations.Length; i++)
            {
                FactoryKey key = CardCatalog.SystemFactoryRegistrations[i].Key;
                if (!CardCatalog.TryGetSystemFactory(key, out GameCore.Gameplay.Cards.ICardTableSystemFactory? implementation) || implementation == null)
                {
                    failure = "SystemFactoryRegistrations: the generated lookup returned no implementation for key " + key.ToString();
                    return exercised;
                }

                exercised++;
            }

            return exercised;
        }

        /// <summary>
        /// Writes every declared schema through its generated serializer, validates the document, re-reads it
        /// and compares every declared field. A schema whose serializer did not survive stripping fails here
        /// (P-054, 05 section 6).
        /// </summary>
        public static int ExerciseSchemas(out string failure)
        {
            failure = string.Empty;
            int exercised = 0;

            // cards.schema.card-config (schema 02bb49501222979cfea308ce5f5f2ca1 version 1)
            {
                CardCatalog.CardConfigSerializer serializer = new CardCatalog.CardConfigSerializer();
                byte[] written = serializer.Serialize(new CardCatalog.CardConfigValue(9U));
                if (!serializer.TryValidate(written, out EnvelopeError validateError))
                {
                    failure = "cards.schema.card-config: the generated document failed validation with " + validateError.ToString();
                    return exercised;
                }

                if (!serializer.TryDeserialize(written, out CardCatalog.CardConfigValue read, out EnvelopeError readError))
                {
                    failure = "cards.schema.card-config: the generated serializer failed to re-read its own document with " + readError.ToString();
                    return exercised;
                }

                if (!(read.SchemaVersion == 9U))
                {
                    failure = "cards.schema.card-config: a declared field did not survive the generated round trip";
                    return exercised;
                }

                exercised++;
            }

            return exercised;
        }

        /// <summary>Number of closed generic instantiations this catalog decides to root.</summary>
        public const int ClosedGenericRootCount = 0;

        /// <summary>
        /// This catalog declares no closed generic instantiation, so there is nothing to execute here. The
        /// method still exists so every generated catalog has one exercise surface (04 section 8).
        /// </summary>
        public static void ExerciseClosedGenericRoots()
        {
        }
    }
}
