// <auto-generated />
// Generated by GameCore.Content.Compiler.CatalogEmitter; do not edit by hand.
// Description format: gamecore.catalog-description/1
// Protocol: 1.0
// Deterministic output: fixed declaration order, canonical key order inside every table,
// no timestamps, no machine paths, no culture-sensitive formatting, LF line endings.
// Regenerating from the same validated description must reproduce this file byte for byte.
// Regenerate with the GameCore content compiler (menu GameCore/Content/Generate Catalog or
// -executeMethod GameCore.Content.Compiler.Editor.CatalogGeneratorMenu.GenerateFromCommandLine).

#nullable enable
using System;
using System.Collections.Generic;
using GameCore.Contracts;
using GameCore.Rules.Cards;
using GameCore.Gameplay.Cards;
using GameCore.Validation.Slices;

namespace GameCore.Validation.GeneratedCards
{
    /// <summary>
    /// Generated closed registration catalog. Every registration is a direct reference, so managed
    /// stripping cannot remove a registration the player resolves by key at runtime (04 section 8).
    /// </summary>
    public static class CardCatalog
    {
        /// <summary>File name this catalog was generated into.</summary>
        public const string GeneratedFileName = "CardCatalog.g.cs";

        /// <summary>Description format this catalog was generated from.</summary>
        public const string DescriptionFormat = "gamecore.catalog-description/1";

        /// <summary>Declared protocol version this catalog was generated for.</summary>
        public const string ProtocolVersion = "1.0";

        /// <summary>Hash algorithm used by CatalogFileHash.</summary>
        public const string HashAlgorithm = "SHA-256";

        /// <summary>Exact scope of CatalogFileHash, so the recorded value can be reproduced independently.</summary>
        public const string CatalogFileHashScope = "SHA-256 over the UTF-8 bytes, with LF line endings, of the file prefix that ends immediately before the eight-space-indented CatalogFileHash declaration; that prefix ends with the newline that terminates the previous line, and the declaration itself, its value and the rest of the file are excluded";

        /// <summary>Scope of CatalogFingerprint, identical to GameCore.Contracts.CatalogFingerprint.Scope.</summary>
        public const string CatalogFingerprintScope = "SHA-256 over, in this fixed order: (1) every registered factory key in canonical ascending order as 16-byte big-endian id, 4-byte big-endian key version, 4-byte big-endian factory kind, 16-byte big-endian owner package id, 16-byte big-endian implementation id, 4-byte big-endian contract version; (2) every accepted schema in ascending schema-id order as 16-byte big-endian id, 4-byte big-endian schema version, one byte 1 when required and 0 when optional, 16-byte big-endian serializer key id, 4-byte big-endian serializer key version, 16-byte big-endian owner package id; (3) every supported feature id in ascending order as 16 bytes. Declaration order, registration timing, machine paths and timestamps are excluded (P-008, P-028, P-053).";

        /// <summary>Canonical fingerprint of the registrations below (P-028, P-053).</summary>
        public const string CatalogFingerprint = "77838f4766f9086a0fa32b4fb30d8d5fceeb3a8072e61594fa2177946ad3315d";

        /// <summary>Supported protocol feature ids, in canonical identity order (P-055).</summary>
        public static readonly Id128[] SupportedFeatureIds =
        {
        };

        /// <summary>Generated key of gamecore.validation.entry.cards ('gamecore.validation.entry.cards').</summary>
        public static readonly FactoryKey CardFamilyEntryKey = new FactoryKey(new Id128(0x6924A730DAE9ADD6UL, 0xDE4FC185BD76C778UL), 1U);

        /// <summary>Generated key of cards.factory.card-table-plugin ('cards.factory.card-table-plugin').</summary>
        public static readonly FactoryKey CardTablePluginKey = new FactoryKey(new Id128(0xBB026AC0599E6783UL, 0x83F12FFCA82E5B2BUL), 1U);

        /// <summary>Generated key of cards.reducer.int32-sum ('cards.reducer.int32-sum').</summary>
        public static readonly FactoryKey CardSetBonusReducerKey = new FactoryKey(new Id128(0xF85B12F56C1232B2UL, 0x70108056ACB54B19UL), 1U);

        /// <summary>Generated key of cards.predicate.always ('cards.predicate.always').</summary>
        public static readonly FactoryKey CardAlwaysPredicateKey = new FactoryKey(new Id128(0xD8CABB8F16C64380UL, 0x102DE6820045DF34UL), 1U);

        /// <summary>Generated key of cards.system.output ('cards.system.output').</summary>
        public static readonly FactoryKey CardOutputSystemKey = new FactoryKey(new Id128(0x2CB9BBFC9BB6CC94UL, 0x95666C211E20EE0FUL), 1U);

        /// <summary>Generated key of cards.system.input ('cards.system.input').</summary>
        public static readonly FactoryKey CardInputSystemKey = new FactoryKey(new Id128(0x4522EE4E182F61DCUL, 0xE6E7466B929DEE07UL), 1U);

        /// <summary>Generated key of cards.system.commit ('cards.system.commit').</summary>
        public static readonly FactoryKey CardCommitSystemKey = new FactoryKey(new Id128(0xA61B22DF091D9AC4UL, 0xC299AE0D0AE30F30UL), 1U);

        /// <summary>Generated key of cards.system.validate ('cards.system.validate').</summary>
        public static readonly FactoryKey CardValidateSystemKey = new FactoryKey(new Id128(0xE113F54073E28D83UL, 0x0803E540BE4EEDFBUL), 1U);

        /// <summary>Generated serializer key of schema 02bb49501222979cfea308ce5f5f2ca1 ('cards.schema.card-config').</summary>
        public static readonly FactoryKey CardConfigSerializerKey = new FactoryKey(new Id128(0x02BB49501222979CUL, 0xFEA308CE5F5F2CA1UL), 1U);

        /// <summary>Generated registrations of PluginFactory, in canonical key order, each bound to a direct constructor reference.</summary>
        public static readonly BoundRegistration<GameCore.Validation.Slices.IFamilyPluginEntry>[] FamilyEntryRegistrations =
        {
            new BoundRegistration<GameCore.Validation.Slices.IFamilyPluginEntry>(
                CardFamilyEntryKey,
                "gamecore.validation.entry.cards",
                new GameCore.Validation.Slices.CardFamilyPluginEntry()),
        };

        /// <summary>Generated keys of FamilyEntryRegistrations, in the same canonical order.</summary>
        public static readonly FactoryKey[] FamilyEntryKeys =
        {
            CardFamilyEntryKey,
        };

        /// <summary>
        /// Catalog registrations of PluginFactory, in the same canonical order as FamilyEntryRegistrations.
        /// Every entry carries its own owner package and precompiled implementation identity, so the
        /// runtime catalog hashes exactly the declarations this file was generated from (P-009, P-028).
        /// </summary>
        public static readonly FactoryRegistration[] FamilyEntryRegistrationsCatalogRegistrations =
        {
            new FactoryRegistration(
                CardFamilyEntryKey,
                FactoryKind.PluginFactory,
                new Id128(0x0000000000000000UL, 0x0000000000000000UL),
                new Id128(0x6924A730DAE9ADD6UL, 0xDE4FC185BD76C778UL),
                1U),
        };

        /// <summary>Generated registrations of PluginFactory, in canonical key order, each bound to a direct constructor reference.</summary>
        public static readonly BoundRegistration<GameCore.Gameplay.Cards.ICardTablePluginFactory>[] PluginRegistrations =
        {
            new BoundRegistration<GameCore.Gameplay.Cards.ICardTablePluginFactory>(
                CardTablePluginKey,
                "cards.factory.card-table-plugin",
                new CardTablePluginFactory(CardTablePluginKey)),
        };

        /// <summary>Generated keys of PluginRegistrations, in the same canonical order.</summary>
        public static readonly FactoryKey[] PluginKeys =
        {
            CardTablePluginKey,
        };

        /// <summary>
        /// Catalog registrations of PluginFactory, in the same canonical order as PluginRegistrations.
        /// Every entry carries its own owner package and precompiled implementation identity, so the
        /// runtime catalog hashes exactly the declarations this file was generated from (P-009, P-028).
        /// </summary>
        public static readonly FactoryRegistration[] PluginRegistrationsCatalogRegistrations =
        {
            new FactoryRegistration(
                CardTablePluginKey,
                FactoryKind.PluginFactory,
                new Id128(0x0000000000000000UL, 0x0000000000000000UL),
                new Id128(0xBB026AC0599E6783UL, 0x83F12FFCA82E5B2BUL),
                1U),
        };

        /// <summary>Generated registrations of Reducer, in canonical key order, each bound to a direct constructor reference.</summary>
        public static readonly BoundRegistration<GameCore.Rules.Cards.ICardBonusReducer>[] ReducerRegistrations =
        {
            new BoundRegistration<GameCore.Rules.Cards.ICardBonusReducer>(
                CardSetBonusReducerKey,
                "cards.reducer.int32-sum",
                new CardSetBonusReducer(CardSetBonusReducerKey)),
        };

        /// <summary>Generated keys of ReducerRegistrations, in the same canonical order.</summary>
        public static readonly FactoryKey[] ReducerKeys =
        {
            CardSetBonusReducerKey,
        };

        /// <summary>
        /// Catalog registrations of Reducer, in the same canonical order as ReducerRegistrations.
        /// Every entry carries its own owner package and precompiled implementation identity, so the
        /// runtime catalog hashes exactly the declarations this file was generated from (P-009, P-028).
        /// </summary>
        public static readonly FactoryRegistration[] ReducerRegistrationsCatalogRegistrations =
        {
            new FactoryRegistration(
                CardSetBonusReducerKey,
                FactoryKind.Reducer,
                new Id128(0x0000000000000000UL, 0x0000000000000000UL),
                new Id128(0xF85B12F56C1232B2UL, 0x70108056ACB54B19UL),
                1U),
        };

        /// <summary>Generated registrations of StaticPredicate, in canonical key order, each bound to a direct constructor reference.</summary>
        public static readonly BoundRegistration<GameCore.Rules.Cards.ICardTargetPredicate>[] StaticPredicateRegistrations =
        {
            new BoundRegistration<GameCore.Rules.Cards.ICardTargetPredicate>(
                CardAlwaysPredicateKey,
                "cards.predicate.always",
                new CardAlwaysPredicate(CardAlwaysPredicateKey)),
        };

        /// <summary>Generated keys of StaticPredicateRegistrations, in the same canonical order.</summary>
        public static readonly FactoryKey[] StaticPredicateKeys =
        {
            CardAlwaysPredicateKey,
        };

        /// <summary>
        /// Catalog registrations of StaticPredicate, in the same canonical order as StaticPredicateRegistrations.
        /// Every entry carries its own owner package and precompiled implementation identity, so the
        /// runtime catalog hashes exactly the declarations this file was generated from (P-009, P-028).
        /// </summary>
        public static readonly FactoryRegistration[] StaticPredicateRegistrationsCatalogRegistrations =
        {
            new FactoryRegistration(
                CardAlwaysPredicateKey,
                FactoryKind.StaticPredicate,
                new Id128(0x0000000000000000UL, 0x0000000000000000UL),
                new Id128(0xD8CABB8F16C64380UL, 0x102DE6820045DF34UL),
                1U),
        };

        /// <summary>Generated registrations of SystemFactory, in canonical key order, each bound to a direct constructor reference.</summary>
        public static readonly BoundRegistration<GameCore.Gameplay.Cards.ICardTableSystemFactory>[] SystemFactoryRegistrations =
        {
            new BoundRegistration<GameCore.Gameplay.Cards.ICardTableSystemFactory>(
                CardOutputSystemKey,
                "cards.system.output",
                new CardTableSystemFactory(CardOutputSystemKey)),
            new BoundRegistration<GameCore.Gameplay.Cards.ICardTableSystemFactory>(
                CardInputSystemKey,
                "cards.system.input",
                new CardTableSystemFactory(CardInputSystemKey)),
            new BoundRegistration<GameCore.Gameplay.Cards.ICardTableSystemFactory>(
                CardCommitSystemKey,
                "cards.system.commit",
                new CardTableSystemFactory(CardCommitSystemKey)),
            new BoundRegistration<GameCore.Gameplay.Cards.ICardTableSystemFactory>(
                CardValidateSystemKey,
                "cards.system.validate",
                new CardTableSystemFactory(CardValidateSystemKey)),
        };

        /// <summary>Generated keys of SystemFactoryRegistrations, in the same canonical order.</summary>
        public static readonly FactoryKey[] SystemFactoryKeys =
        {
            CardOutputSystemKey,
            CardInputSystemKey,
            CardCommitSystemKey,
            CardValidateSystemKey,
        };

        /// <summary>
        /// Catalog registrations of SystemFactory, in the same canonical order as SystemFactoryRegistrations.
        /// Every entry carries its own owner package and precompiled implementation identity, so the
        /// runtime catalog hashes exactly the declarations this file was generated from (P-009, P-028).
        /// </summary>
        public static readonly FactoryRegistration[] SystemFactoryRegistrationsCatalogRegistrations =
        {
            new FactoryRegistration(
                CardOutputSystemKey,
                FactoryKind.SystemFactory,
                new Id128(0x0000000000000000UL, 0x0000000000000000UL),
                new Id128(0x2CB9BBFC9BB6CC94UL, 0x95666C211E20EE0FUL),
                1U),
            new FactoryRegistration(
                CardInputSystemKey,
                FactoryKind.SystemFactory,
                new Id128(0x0000000000000000UL, 0x0000000000000000UL),
                new Id128(0x4522EE4E182F61DCUL, 0xE6E7466B929DEE07UL),
                1U),
            new FactoryRegistration(
                CardCommitSystemKey,
                FactoryKind.SystemFactory,
                new Id128(0x0000000000000000UL, 0x0000000000000000UL),
                new Id128(0xA61B22DF091D9AC4UL, 0xC299AE0D0AE30F30UL),
                1U),
            new FactoryRegistration(
                CardValidateSystemKey,
                FactoryKind.SystemFactory,
                new Id128(0x0000000000000000UL, 0x0000000000000000UL),
                new Id128(0xE113F54073E28D83UL, 0x0803E540BE4EEDFBUL),
                1U),
        };

        /// <summary>Validated schema registrations, in canonical schema-id order.</summary>
        public static readonly SchemaRegistration[] SchemaRegistrations =
        {
            new SchemaRegistration(
                new SchemaRef(new SchemaId(new Id128(0x02BB49501222979CUL, 0xFEA308CE5F5F2CA1UL)), 1U),
                new Id128(0x0000000000000000UL, 0x0000000000000000UL),
                CardConfigSerializerKey,
                true),
        };

        /// <summary>
        /// Resolves one generated registration by key. A key absent from this table returns false with a
        /// null implementation; nothing is constructed by reflection or runtime type discovery (04 section 8).
        /// </summary>
        public static bool TryGetFamilyEntry(FactoryKey key, out GameCore.Validation.Slices.IFamilyPluginEntry? implementation)
        {
            for (int i = 0; i < FamilyEntryRegistrations.Length; i++)
            {
                if (FamilyEntryRegistrations[i].Key.Equals(key))
                {
                    implementation = FamilyEntryRegistrations[i].Implementation;
                    return true;
                }
            }

            implementation = null;
            return false;
        }

        /// <summary>
        /// Resolves one generated registration by key. A key absent from this table returns false with a
        /// null implementation; nothing is constructed by reflection or runtime type discovery (04 section 8).
        /// </summary>
        public static bool TryGetPluginFactory(FactoryKey key, out GameCore.Gameplay.Cards.ICardTablePluginFactory? implementation)
        {
            for (int i = 0; i < PluginRegistrations.Length; i++)
            {
                if (PluginRegistrations[i].Key.Equals(key))
                {
                    implementation = PluginRegistrations[i].Implementation;
                    return true;
                }
            }

            implementation = null;
            return false;
        }

        /// <summary>
        /// Resolves one generated registration by key. A key absent from this table returns false with a
        /// null implementation; nothing is constructed by reflection or runtime type discovery (04 section 8).
        /// </summary>
        public static bool TryGetReducer(FactoryKey key, out GameCore.Rules.Cards.ICardBonusReducer? implementation)
        {
            for (int i = 0; i < ReducerRegistrations.Length; i++)
            {
                if (ReducerRegistrations[i].Key.Equals(key))
                {
                    implementation = ReducerRegistrations[i].Implementation;
                    return true;
                }
            }

            implementation = null;
            return false;
        }

        /// <summary>
        /// Resolves one generated registration by key. A key absent from this table returns false with a
        /// null implementation; nothing is constructed by reflection or runtime type discovery (04 section 8).
        /// </summary>
        public static bool TryGetStaticPredicate(FactoryKey key, out GameCore.Rules.Cards.ICardTargetPredicate? implementation)
        {
            for (int i = 0; i < StaticPredicateRegistrations.Length; i++)
            {
                if (StaticPredicateRegistrations[i].Key.Equals(key))
                {
                    implementation = StaticPredicateRegistrations[i].Implementation;
                    return true;
                }
            }

            implementation = null;
            return false;
        }

        /// <summary>
        /// Resolves one generated registration by key. A key absent from this table returns false with a
        /// null implementation; nothing is constructed by reflection or runtime type discovery (04 section 8).
        /// </summary>
        public static bool TryGetSystemFactory(FactoryKey key, out GameCore.Gameplay.Cards.ICardTableSystemFactory? implementation)
        {
            for (int i = 0; i < SystemFactoryRegistrations.Length; i++)
            {
                if (SystemFactoryRegistrations[i].Key.Equals(key))
                {
                    implementation = SystemFactoryRegistrations[i].Implementation;
                    return true;
                }
            }

            implementation = null;
            return false;
        }

        /// <summary>
        /// Generated value of schema 02bb49501222979cfea308ce5f5f2ca1 ('cards.schema.card-config').
        /// Fields are declared in ascending field-id order, which is also the wire order (05 s6).
        /// </summary>
        public readonly struct CardConfigValue
        {
            /// <summary>Field id 1, wire type UInt32, required.</summary>
            public readonly uint SchemaVersion;

            public CardConfigValue(uint schemaVersion)
            {
                SchemaVersion = schemaVersion;
            }

            /// <summary>Diagnostic form; never used as an identity (P-004).</summary>
            public override string ToString()
            {
                return "CardConfigValue(SchemaVersion=" + SchemaVersion + ")";
            }
        }

        /// <summary>
        /// Generated serializer of schema 02bb49501222979cfea308ce5f5f2ca1 version 1. Canonical envelope format only: no reflection,
        /// no dynamic type construction (05 s6, P-054).
        /// </summary>
        public sealed class CardConfigSerializer : GeneratedSerializerBase
        {
            private static readonly GeneratedFieldSlot[] DeclaredFieldSlots =
            {
                new GeneratedFieldSlot(1, WireType.UInt32, true),
            };

            public CardConfigSerializer()
                : base(
                    CardConfigSerializerKey,
                    new SchemaRef(new SchemaId(new Id128(0x02BB49501222979CUL, 0xFEA308CE5F5F2CA1UL)), 1U),
                    SupportedFeatureIds)
            {
            }

            /// <summary>Declared fields in ascending field-id order.</summary>
            protected override IReadOnlyList<GeneratedFieldSlot> DeclaredFields => DeclaredFieldSlots;

            /// <summary>Writes one value as a canonical envelope document with a trailing checksum.</summary>
            public byte[] Serialize(CardConfigValue value)
            {
                EnvelopeWriter writer = CreateWriter();
                writer.WriteUInt32Field(1, value.SchemaVersion);
                writer.WriteChecksum();
                return writer.ToArray();
            }

            /// <summary>
            /// Validates one document against this schema and decodes its declared fields. A false result
            /// reports the exact envelope error and leaves the value at its default.
            /// </summary>
            public bool TryDeserialize(byte[] document, out CardConfigValue value, out EnvelopeError error)
            {
                value = default(CardConfigValue);
                GeneratedFieldBuffer buffer = new GeneratedFieldBuffer();
                if (!TryReadDeclaredFields(document, buffer, out error))
                {
                    return false;
                }

                EnvelopeReader reader = new EnvelopeReader(document);
                uint value0 = default(uint);
                for (int i = 0; i < buffer.Count; i++)
                {
                    EnvelopeField recorded = buffer.Field(i);
                    if (!reader.TrySeekTo(buffer.RecordOffset(i)))
                    {
                        error = reader.LastError;
                        return false;
                    }

                    switch (recorded.FieldId)
                    {
                        case 1:
                        {
                            if (!reader.TryReadField(out EnvelopeField field0))
                            {
                                error = reader.LastError;
                                return false;
                            }

                            uint field0Value;
                            if (!reader.TryReadUInt32(field0, out field0Value))
                            {
                                error = reader.LastError;
                                return false;
                            }

                            value0 = field0Value;
                            break;
                        }
                        default:
                            break;
                    }
                }

                // A declared field the document omitted keeps its default, and every declared field
                // is assigned exactly once, so the generated value type stays immutable (05 s6, P-054).
                value = new CardConfigValue(value0);
                error = EnvelopeError.None;
                return true;
            }
        }

        /// <summary>
        /// Generated serializer instances, one per declared schema, in the same canonical order as
        /// SchemaRegistrations. Instances are constructed directly; no serializer is discovered at runtime.
        /// </summary>
        public static readonly ISchemaSerializer[] Serializers =
        {
            new CardConfigSerializer(),
        };

        /// <summary>
        /// Validates every generated table under the production catalog rules and returns the immutable
        /// catalog, or the exact structured rejections (P-009). Nothing is exposed on rejection.
        /// </summary>
        public static CatalogBuildResult BuildCatalog()
        {
            FactoryRegistration[] groupRegistrations = GroupCatalogRegistrations();
            FactoryRegistration[] all = new FactoryRegistration[groupRegistrations.Length + SchemaRegistrations.Length];
            Array.Copy(groupRegistrations, 0, all, 0, groupRegistrations.Length);

            for (int i = 0; i < SchemaRegistrations.Length; i++)
            {
                SchemaRegistration registration = SchemaRegistrations[i];
                all[groupRegistrations.Length + i] = new FactoryRegistration(
                    registration.Serializer,
                    FactoryKind.Serializer,
                    registration.OwnerPackageId,
                    registration.Schema.Id.Value,
                    registration.Schema.Version);
            }

            return ImmutableCatalog.Build(all, SchemaRegistrations, SupportedFeatureIds, Serializers);
        }

        /// <summary>Every group's catalog registrations concatenated in declaration order.</summary>
        private static FactoryRegistration[] GroupCatalogRegistrations()
        {
            FactoryRegistration[] all = new FactoryRegistration[8];
            int offset = 0;
            Array.Copy(FamilyEntryRegistrationsCatalogRegistrations, 0, all, offset, 1);
            offset += 1;
            Array.Copy(PluginRegistrationsCatalogRegistrations, 0, all, offset, 1);
            offset += 1;
            Array.Copy(ReducerRegistrationsCatalogRegistrations, 0, all, offset, 1);
            offset += 1;
            Array.Copy(StaticPredicateRegistrationsCatalogRegistrations, 0, all, offset, 1);
            offset += 1;
            Array.Copy(SystemFactoryRegistrationsCatalogRegistrations, 0, all, offset, 4);
            offset += 4;

            return all;
        }

        /// <summary>
        /// Builds the catalog and asserts that its fingerprint equals the value emitted into this file, so a
        /// stale generated file cannot describe a catalog whose declarations changed (P-028).
        /// </summary>
        public static CatalogBuildResult BuildVerifiedCatalog(out ContentHash observedFingerprint)
        {
            CatalogBuildResult result = BuildCatalog();
            observedFingerprint = result.Catalog == null ? ContentHash.Empty : result.Catalog.Fingerprint;
            return result;
        }

        /// <summary>
        /// Fingerprint the generated declarations must produce. A test compares this literal against a
        /// freshly built catalog so an unnoticed declaration change fails instead of being ignored.
        /// </summary>
        public static bool FingerprintMatchesGeneratedCatalog(out ContentHash observed)
        {
            CatalogBuildResult result = BuildVerifiedCatalog(out observed);
            return result.Catalog != null && string.Equals(observed.ToHex(), CatalogFingerprint, StringComparison.Ordinal);
        }

        /// <summary>True because this catalog emits closed generic roots.</summary>
        public const bool HasClosedGenericRoots = false;

        /// <summary>Number of generated registration groups.</summary>
        public const int RegistrationGroupCount = 5;

        /// <summary>Number of declared schemas.</summary>
        public const int SchemaCount = 1;

        /// <summary>Hash of the generated source that precedes this declaration.</summary>
        public const string CatalogFileHash = "902402a6f03fcf28dd242f23f573fcb9ddd53d013efb06f08aa513f689ff3bf8";
    }
}
