// <auto-generated />
// Generated by GameCore.Content.Compiler catalog tooling; do not edit by hand.
//
// Reachability exercise for CheckpointCatalog: it resolves every generated registration through the
// catalog's own generated lookup method, writes and re-reads every declared schema through its generated
// serializer, and calls the generated closed-generic root method when the catalog emits one. It is compiled
// into the same assembly as the catalog, so a stripped registration or serializer fails here in a player build
// instead of only in the Editor (04 section 8, GC-025).
#nullable enable
using System;
using GameCore.Contracts;

namespace GameCore.Validation.GeneratedCheckpoint
{
    /// <summary>
    /// Generated reachability exercise of <see cref="CheckpointCatalog"/>. Every method returns the number of
    /// entries it exercised and reports the first failure in <c>failure</c> instead of throwing, so a player
    /// probe can record the exact missing entry.
    /// </summary>
    public static class CheckpointCatalogCoverage
    {
        /// <summary>Number of generated registration entries this exercise resolves by key.</summary>
        public const int RegistrationCount = 0;

        /// <summary>
        /// Resolves every generated registration through the table's own generated lookup method and checks that a
        /// non-null implementation comes back under exactly the key the table declares. A key absent from the
        /// table must return false (P-009).
        /// </summary>
        public static int ExerciseRegistrations(out string failure)
        {
            failure = string.Empty;
            int exercised = 0;

            return exercised;
        }

        /// <summary>
        /// Writes every declared schema through its generated serializer, validates the document, re-reads it
        /// and compares every declared field. A schema whose serializer did not survive stripping fails here
        /// (P-054, 05 section 6).
        /// </summary>
        public static int ExerciseSchemas(out string failure)
        {
            failure = string.Empty;
            int exercised = 0;

            // gamecore.checkpoint.schema.scope (schema 1bb5c533dab84e7604c8b98f1b97066a version 1)
            {
                CheckpointCatalog.ScopeRecordSerializer serializer = new CheckpointCatalog.ScopeRecordSerializer();
                byte[] written = serializer.Serialize(new CheckpointCatalog.ScopeRecordValue(10UL, 10UL, 10UL, 10UL, 9U, 9U, 9U, 9U, true, true, 9U, 9U));
                if (!serializer.TryValidate(written, out EnvelopeError validateError))
                {
                    failure = "gamecore.checkpoint.schema.scope: the generated document failed validation with " + validateError.ToString();
                    return exercised;
                }

                if (!serializer.TryDeserialize(written, out CheckpointCatalog.ScopeRecordValue read, out EnvelopeError readError))
                {
                    failure = "gamecore.checkpoint.schema.scope: the generated serializer failed to re-read its own document with " + readError.ToString();
                    return exercised;
                }

                if (!(read.ScopeHigh == 10UL && read.ScopeLow == 10UL && read.ParentHigh == 10UL && read.ParentLow == 10UL && read.Depth == 9U && read.Mode == 9U && read.InstallCount == 9U && read.GrantCount == 9U && read.ServiceIsolationAll == true && read.CapabilityIsolationAll == true && read.ServiceIsolationCount == 9U && read.CapabilityIsolationCount == 9U))
                {
                    failure = "gamecore.checkpoint.schema.scope: a declared field did not survive the generated round trip";
                    return exercised;
                }

                exercised++;
            }

            // gamecore.checkpoint.schema.cursor (schema 1ddc64b87daa5363e1c1951d44ad5f07 version 1)
            {
                CheckpointCatalog.CursorRecordSerializer serializer = new CheckpointCatalog.CursorRecordSerializer();
                byte[] written = serializer.Serialize(new CheckpointCatalog.CursorRecordValue(9U, 10UL, 10UL, 10UL, 10UL, 10UL));
                if (!serializer.TryValidate(written, out EnvelopeError validateError))
                {
                    failure = "gamecore.checkpoint.schema.cursor: the generated document failed validation with " + validateError.ToString();
                    return exercised;
                }

                if (!serializer.TryDeserialize(written, out CheckpointCatalog.CursorRecordValue read, out EnvelopeError readError))
                {
                    failure = "gamecore.checkpoint.schema.cursor: the generated serializer failed to re-read its own document with " + readError.ToString();
                    return exercised;
                }

                if (!(read.RowKind == 9U && read.IssuerHigh == 10UL && read.IssuerLow == 10UL && read.Sequence == 10UL && read.SessionHigh == 10UL && read.SessionLow == 10UL))
                {
                    failure = "gamecore.checkpoint.schema.cursor: a declared field did not survive the generated round trip";
                    return exercised;
                }

                exercised++;
            }

            // gamecore.checkpoint.schema.slot (schema 325ebfc76f751ee2c2b4985df3d088a0 version 1)
            {
                CheckpointCatalog.SlotRecordSerializer serializer = new CheckpointCatalog.SlotRecordSerializer();
                byte[] written = serializer.Serialize(new CheckpointCatalog.SlotRecordValue(10UL, 10UL, 10UL, 10UL, 10UL, 10UL, 9U, 7, true));
                if (!serializer.TryValidate(written, out EnvelopeError validateError))
                {
                    failure = "gamecore.checkpoint.schema.slot: the generated document failed validation with " + validateError.ToString();
                    return exercised;
                }

                if (!serializer.TryDeserialize(written, out CheckpointCatalog.SlotRecordValue read, out EnvelopeError readError))
                {
                    failure = "gamecore.checkpoint.schema.slot: the generated serializer failed to re-read its own document with " + readError.ToString();
                    return exercised;
                }

                if (!(read.TargetHigh == 10UL && read.TargetLow == 10UL && read.OwnerHigh == 10UL && read.OwnerLow == 10UL && read.SlotHigh == 10UL && read.SlotLow == 10UL && read.SchemaVersion == 9U && read.Value == 7 && read.Active == true))
                {
                    failure = "gamecore.checkpoint.schema.slot: a declared field did not survive the generated round trip";
                    return exercised;
                }

                exercised++;
            }

            // gamecore.checkpoint.schema.selection (schema 4736afccc12b5b625adb5bcdbb714e3f version 1)
            {
                CheckpointCatalog.SelectionRecordSerializer serializer = new CheckpointCatalog.SelectionRecordSerializer();
                byte[] written = serializer.Serialize(new CheckpointCatalog.SelectionRecordValue(10UL, 10UL, 10UL, 10UL, 9U, 10UL, 10UL, 9U));
                if (!serializer.TryValidate(written, out EnvelopeError validateError))
                {
                    failure = "gamecore.checkpoint.schema.selection: the generated document failed validation with " + validateError.ToString();
                    return exercised;
                }

                if (!serializer.TryDeserialize(written, out CheckpointCatalog.SelectionRecordValue read, out EnvelopeError readError))
                {
                    failure = "gamecore.checkpoint.schema.selection: the generated serializer failed to re-read its own document with " + readError.ToString();
                    return exercised;
                }

                if (!(read.InstanceHigh == 10UL && read.InstanceLow == 10UL && read.ContractHigh == 10UL && read.ContractLow == 10UL && read.ContractVersion == 9U && read.ProviderHigh == 10UL && read.ProviderLow == 10UL && read.Order == 9U))
                {
                    failure = "gamecore.checkpoint.schema.selection: a declared field did not survive the generated round trip";
                    return exercised;
                }

                exercised++;
            }

            // gamecore.checkpoint.schema.clock (schema 49f4779fa88d83ea0440e2bab679d545 version 1)
            {
                CheckpointCatalog.ClockRecordSerializer serializer = new CheckpointCatalog.ClockRecordSerializer();
                byte[] written = serializer.Serialize(new CheckpointCatalog.ClockRecordValue(9U, 10UL, 10UL, 9U, 9U, true, 10UL, 10UL, 10UL, 10UL, 9U, 10UL, 10UL, 10UL, 9U, 9U));
                if (!serializer.TryValidate(written, out EnvelopeError validateError))
                {
                    failure = "gamecore.checkpoint.schema.clock: the generated document failed validation with " + validateError.ToString();
                    return exercised;
                }

                if (!serializer.TryDeserialize(written, out CheckpointCatalog.ClockRecordValue read, out EnvelopeError readError))
                {
                    failure = "gamecore.checkpoint.schema.clock: the generated serializer failed to re-read its own document with " + readError.ToString();
                    return exercised;
                }

                if (!(read.RowKind == 9U && read.ClockHigh == 10UL && read.ClockLow == 10UL && read.ClockKind == 9U && read.PausePolicy == 9U && read.Persists == true && read.WakeHigh == 10UL && read.WakeLow == 10UL && read.PayloadSchemaHigh == 10UL && read.PayloadSchemaLow == 10UL && read.PayloadSchemaVersion == 9U && read.ScheduledAtSequence == 10UL && read.RemainingSteps == 10UL && read.RemainingTicks == 10UL && read.WakeState == 9U && read.Order == 9U))
                {
                    failure = "gamecore.checkpoint.schema.clock: a declared field did not survive the generated round trip";
                    return exercised;
                }

                exercised++;
            }

            // gamecore.checkpoint.schema.grant (schema 54d0f9cccec243b78414ec19245173c6 version 1)
            {
                CheckpointCatalog.GrantRecordSerializer serializer = new CheckpointCatalog.GrantRecordSerializer();
                byte[] written = serializer.Serialize(new CheckpointCatalog.GrantRecordValue(9U, 10UL, 10UL, 10UL, 10UL, 10UL, 10UL, 9U, 10UL, 10UL, 10UL, 10UL, 10UL, 10UL, 9U, 10UL, 10UL, true, true, 9U, 9U));
                if (!serializer.TryValidate(written, out EnvelopeError validateError))
                {
                    failure = "gamecore.checkpoint.schema.grant: the generated document failed validation with " + validateError.ToString();
                    return exercised;
                }

                if (!serializer.TryDeserialize(written, out CheckpointCatalog.GrantRecordValue read, out EnvelopeError readError))
                {
                    failure = "gamecore.checkpoint.schema.grant: the generated serializer failed to re-read its own document with " + readError.ToString();
                    return exercised;
                }

                if (!(read.Kind == 9U && read.ScopeHigh == 10UL && read.ScopeLow == 10UL && read.TargetHigh == 10UL && read.TargetLow == 10UL && read.CapabilityHigh == 10UL && read.CapabilityLow == 10UL && read.CapabilityVersion == 9U && read.ProviderHigh == 10UL && read.ProviderLow == 10UL && read.RuleHigh == 10UL && read.RuleLow == 10UL && read.ContractHigh == 10UL && read.ContractLow == 10UL && read.ContractVersion == 9U && read.SubjectHigh == 10UL && read.SubjectLow == 10UL && read.AppliesToSubtree == true && read.AllContracts == true && read.ExclusionKind == 9U && read.Order == 9U))
                {
                    failure = "gamecore.checkpoint.schema.grant: a declared field did not survive the generated round trip";
                    return exercised;
                }

                exercised++;
            }

            // gamecore.checkpoint.schema.install (schema 5666c5db5d34ad37d470140f8c18808f version 1)
            {
                CheckpointCatalog.InstallRecordSerializer serializer = new CheckpointCatalog.InstallRecordSerializer();
                byte[] written = serializer.Serialize(new CheckpointCatalog.InstallRecordValue(10UL, 10UL, 10UL, 10UL, 10UL, 10UL, 10UL, 10UL, 10UL, 10UL, 10UL, 7, 10UL, 10UL, 9U, 9U, new byte[] { 1, 2, 3 }, 9U, true));
                if (!serializer.TryValidate(written, out EnvelopeError validateError))
                {
                    failure = "gamecore.checkpoint.schema.install: the generated document failed validation with " + validateError.ToString();
                    return exercised;
                }

                if (!serializer.TryDeserialize(written, out CheckpointCatalog.InstallRecordValue read, out EnvelopeError readError))
                {
                    failure = "gamecore.checkpoint.schema.install: the generated serializer failed to re-read its own document with " + readError.ToString();
                    return exercised;
                }

                if (!(read.InstanceHigh == 10UL && read.InstanceLow == 10UL && read.PluginTypeHigh == 10UL && read.PluginTypeLow == 10UL && read.ScopeHigh == 10UL && read.ScopeLow == 10UL && read.ConfigRevision == 10UL && read.ConfigHashA == 10UL && read.ConfigHashB == 10UL && read.ConfigHashC == 10UL && read.ConfigHashD == 10UL && read.Priority == 7 && read.Generation == 10UL && read.ActivationEpoch == 10UL && read.State == 9U && read.ConfigFieldCount == 9U && read.ConfigBytes != null && read.ConfigBytes.Length == 3 && read.ConfigBytes[1] == 2 && read.SelectionCount == 9U && read.HasConfigDocument == true))
                {
                    failure = "gamecore.checkpoint.schema.install: a declared field did not survive the generated round trip";
                    return exercised;
                }

                exercised++;
            }

            // gamecore.checkpoint.schema.message (schema 744d60d006798058b50b656c613a21f3 version 1)
            {
                CheckpointCatalog.MessageRecordSerializer serializer = new CheckpointCatalog.MessageRecordSerializer();
                byte[] written = serializer.Serialize(new CheckpointCatalog.MessageRecordValue(10UL, 10UL, 10UL, 10UL, 10UL, 10UL, 10UL, 10UL, 10UL, 10UL, 10UL, 10UL, 10UL, 9U, 9U, 10UL, 9U, 10UL, 10UL, 10UL, 10UL, 9U, 10UL, 10UL, true, true, true, new byte[] { 1, 2, 3 }));
                if (!serializer.TryValidate(written, out EnvelopeError validateError))
                {
                    failure = "gamecore.checkpoint.schema.message: the generated document failed validation with " + validateError.ToString();
                    return exercised;
                }

                if (!serializer.TryDeserialize(written, out CheckpointCatalog.MessageRecordValue read, out EnvelopeError readError))
                {
                    failure = "gamecore.checkpoint.schema.message: the generated serializer failed to re-read its own document with " + readError.ToString();
                    return exercised;
                }

                if (!(read.Step == 10UL && read.Epoch == 10UL && read.RequestIssuerHigh == 10UL && read.RequestIssuerLow == 10UL && read.RequestSequence == 10UL && read.RouteHigh == 10UL && read.RouteLow == 10UL && read.OwnerHigh == 10UL && read.OwnerLow == 10UL && read.TargetHigh == 10UL && read.TargetLow == 10UL && read.PayloadSchemaHigh == 10UL && read.PayloadSchemaLow == 10UL && read.PayloadSchemaVersion == 9U && read.MessageKind == 9U && read.OrderAdmitted == 10UL && read.OrderOrdinal == 9U && read.OriginKeyHigh == 10UL && read.OriginKeyLow == 10UL && read.ProducerKeyHigh == 10UL && read.ProducerKeyLow == 10UL && read.ProducerKeyVersion == 9U && read.BufferHigh == 10UL && read.BufferLow == 10UL && read.HasPayload == true && read.HasRequest == true && read.IsOutcome == true && read.Payload != null && read.Payload.Length == 3 && read.Payload[1] == 2))
                {
                    failure = "gamecore.checkpoint.schema.message: a declared field did not survive the generated round trip";
                    return exercised;
                }

                exercised++;
            }

            // gamecore.checkpoint.schema.outbox (schema ac96339bd83d4a4ca453b3f4e46e4639 version 1)
            {
                CheckpointCatalog.OutboxRecordSerializer serializer = new CheckpointCatalog.OutboxRecordSerializer();
                byte[] written = serializer.Serialize(new CheckpointCatalog.OutboxRecordValue(9U, 9U, 10UL, 10UL, 10UL, 10UL, 10UL, 10UL, 10UL, 10UL, 10UL, 10UL, 10UL, 10UL, 10UL, 10UL, 9U, 9U, 9U, 9U, 9U, 9U, 10UL, 10UL, 9U, 9U, new byte[] { 1, 2, 3 }));
                if (!serializer.TryValidate(written, out EnvelopeError validateError))
                {
                    failure = "gamecore.checkpoint.schema.outbox: the generated document failed validation with " + validateError.ToString();
                    return exercised;
                }

                if (!serializer.TryDeserialize(written, out CheckpointCatalog.OutboxRecordValue read, out EnvelopeError readError))
                {
                    failure = "gamecore.checkpoint.schema.outbox: the generated serializer failed to re-read its own document with " + readError.ToString();
                    return exercised;
                }

                if (!(read.RowKind == 9U && read.RecordVersion == 9U && read.OutboxHigh == 10UL && read.OutboxLow == 10UL && read.DestinationHigh == 10UL && read.DestinationLow == 10UL && read.IdempotencyHigh == 10UL && read.IdempotencyLow == 10UL && read.SourceEventSequence == 10UL && read.SourceStep == 10UL && read.SourceEpoch == 10UL && read.CausalIssuerHigh == 10UL && read.CausalIssuerLow == 10UL && read.CausalIssuerSequence == 10UL && read.PayloadSchemaHigh == 10UL && read.PayloadSchemaLow == 10UL && read.PayloadSchemaVersion == 9U && read.DeliveryState == 9U && read.ReasonCode == 9U && read.AttemptCount == 9U && read.Durability == 9U && read.OrderOrdinal == 9U && read.CursorHigh == 10UL && read.CursorLow == 10UL && read.CursorCount == 9U && read.PrunedCount == 9U && read.Payload != null && read.Payload.Length == 3 && read.Payload[1] == 2))
                {
                    failure = "gamecore.checkpoint.schema.outbox: a declared field did not survive the generated round trip";
                    return exercised;
                }

                exercised++;
            }

            // gamecore.checkpoint.schema.target (schema b780328c6fa158f7bd88603db3ebae2f version 1)
            {
                CheckpointCatalog.TargetRecordSerializer serializer = new CheckpointCatalog.TargetRecordSerializer();
                byte[] written = serializer.Serialize(new CheckpointCatalog.TargetRecordValue(10UL, 10UL, 10UL, 10UL, 10UL, 10UL, 10UL, 10UL, 9U, 10UL, 9U, 10UL));
                if (!serializer.TryValidate(written, out EnvelopeError validateError))
                {
                    failure = "gamecore.checkpoint.schema.target: the generated document failed validation with " + validateError.ToString();
                    return exercised;
                }

                if (!serializer.TryDeserialize(written, out CheckpointCatalog.TargetRecordValue read, out EnvelopeError readError))
                {
                    failure = "gamecore.checkpoint.schema.target: the generated serializer failed to re-read its own document with " + readError.ToString();
                    return exercised;
                }

                if (!(read.TargetHigh == 10UL && read.TargetLow == 10UL && read.ScopeHigh == 10UL && read.ScopeLow == 10UL && read.DefinitionHigh == 10UL && read.DefinitionLow == 10UL && read.SchemaHigh == 10UL && read.SchemaLow == 10UL && read.SchemaVersion == 9U && read.ContentRevision == 10UL && read.SourceSlot == 9U && read.SourceGeneration == 10UL))
                {
                    failure = "gamecore.checkpoint.schema.target: a declared field did not survive the generated round trip";
                    return exercised;
                }

                exercised++;
            }

            // gamecore.checkpoint.schema.rng (schema cd069d4291975928edb3f9e9af5e037d version 1)
            {
                CheckpointCatalog.RngRecordSerializer serializer = new CheckpointCatalog.RngRecordSerializer();
                byte[] written = serializer.Serialize(new CheckpointCatalog.RngRecordValue(10UL, 10UL, 10UL, 10UL, 10UL));
                if (!serializer.TryValidate(written, out EnvelopeError validateError))
                {
                    failure = "gamecore.checkpoint.schema.rng: the generated document failed validation with " + validateError.ToString();
                    return exercised;
                }

                if (!serializer.TryDeserialize(written, out CheckpointCatalog.RngRecordValue read, out EnvelopeError readError))
                {
                    failure = "gamecore.checkpoint.schema.rng: the generated serializer failed to re-read its own document with " + readError.ToString();
                    return exercised;
                }

                if (!(read.StreamHigh == 10UL && read.StreamLow == 10UL && read.State == 10UL && read.StreamKey == 10UL && read.DrawCount == 10UL))
                {
                    failure = "gamecore.checkpoint.schema.rng: a declared field did not survive the generated round trip";
                    return exercised;
                }

                exercised++;
            }

            // gamecore.checkpoint.schema.header (schema d578e5fe72e484be8d8c015a17d8b66b version 1)
            {
                CheckpointCatalog.HeaderRecordSerializer serializer = new CheckpointCatalog.HeaderRecordSerializer();
                byte[] written = serializer.Serialize(new CheckpointCatalog.HeaderRecordValue(10UL, 10UL, 10UL, 10UL, 9U, 9U, 9U, 10UL, 10UL, 9U, true, 10UL, 10UL, 1.5, 10UL, 9U, 10UL, 10UL, 10UL, 10UL, 9U, 10UL, 9U, 10UL, 9U, 9U, 9U, 9U, 9U, 9U, 9U, 9U, 9U, 9U, 9U, 10UL, 10UL, 10UL, 9U, 9U));
                if (!serializer.TryValidate(written, out EnvelopeError validateError))
                {
                    failure = "gamecore.checkpoint.schema.header: the generated document failed validation with " + validateError.ToString();
                    return exercised;
                }

                if (!serializer.TryDeserialize(written, out CheckpointCatalog.HeaderRecordValue read, out EnvelopeError readError))
                {
                    failure = "gamecore.checkpoint.schema.header: the generated serializer failed to re-read its own document with " + readError.ToString();
                    return exercised;
                }

                if (!(read.WorldDefinitionHigh == 10UL && read.WorldDefinitionLow == 10UL && read.SourceSessionHigh == 10UL && read.SourceSessionLow == 10UL && read.ProtocolMajor == 9U && read.ProtocolMinor == 9U && read.TemporalModel == 9U && read.StepDurationTicks == 10UL && read.TicksPerSecond == 10UL && read.MaxStepsPerPump == 9U && read.UsesUnscaledHostClock == true && read.LogicalStep == 10UL && read.TimeDebtTicks == 10UL && read.DomainSeconds == 1.5 && read.PendingDemand == 10UL && read.PropagationMode == 9U && read.CatalogFingerprintA == 10UL && read.CatalogFingerprintB == 10UL && read.CatalogFingerprintC == 10UL && read.CatalogFingerprintD == 10UL && read.QueuePolicy == 9U && read.AdmissionCutoff == 10UL && read.RejectedQueuedCount == 9U && read.LastEventSequence == 10UL && read.ScopeCount == 9U && read.InstallCount == 9U && read.SelectionCount == 9U && read.TargetCount == 9U && read.SlotCount == 9U && read.GrantCount == 9U && read.ClockCount == 9U && read.CommandCount == 9U && read.MessageCount == 9U && read.RngStreamCount == 9U && read.CursorCount == 9U && read.SourcePublishedRevision == 10UL && read.SourcePublishedEpoch == 10UL && read.SourceHostTicksPerSecond == 10UL && read.ContentRevisionCount == 9U && read.OutboxCount == 9U))
                {
                    failure = "gamecore.checkpoint.schema.header: a declared field did not survive the generated round trip";
                    return exercised;
                }

                exercised++;
            }

            // gamecore.checkpoint.schema.command (schema efe5ab3007e3f7b821d96f9264ab31ef version 1)
            {
                CheckpointCatalog.CommandRecordSerializer serializer = new CheckpointCatalog.CommandRecordSerializer();
                byte[] written = serializer.Serialize(new CheckpointCatalog.CommandRecordValue(10UL, 10UL, 10UL, 10UL, 10UL, 10UL, 10UL, 10UL, 10UL, 9U, 10UL, 10UL, 10UL, 9U, 9U, 10UL, 10UL, 10UL, 10UL, new byte[] { 1, 2, 3 }));
                if (!serializer.TryValidate(written, out EnvelopeError validateError))
                {
                    failure = "gamecore.checkpoint.schema.command: the generated document failed validation with " + validateError.ToString();
                    return exercised;
                }

                if (!serializer.TryDeserialize(written, out CheckpointCatalog.CommandRecordValue read, out EnvelopeError readError))
                {
                    failure = "gamecore.checkpoint.schema.command: the generated serializer failed to re-read its own document with " + readError.ToString();
                    return exercised;
                }

                if (!(read.IssuerHigh == 10UL && read.IssuerLow == 10UL && read.IssuerSequence == 10UL && read.RouteHigh == 10UL && read.RouteLow == 10UL && read.TargetHigh == 10UL && read.TargetLow == 10UL && read.SchemaHigh == 10UL && read.SchemaLow == 10UL && read.SchemaVersion == 9U && read.AdmittedStep == 10UL && read.AdmittedEpoch == 10UL && read.AdmissionSequence == 10UL && read.OrderOrdinal == 9U && read.OriginKind == 9U && read.InputHashA == 10UL && read.InputHashB == 10UL && read.InputHashC == 10UL && read.InputHashD == 10UL && read.Payload != null && read.Payload.Length == 3 && read.Payload[1] == 2))
                {
                    failure = "gamecore.checkpoint.schema.command: a declared field did not survive the generated round trip";
                    return exercised;
                }

                exercised++;
            }

            return exercised;
        }

        /// <summary>Number of closed generic instantiations this catalog decides to root.</summary>
        public const int ClosedGenericRootCount = 0;

        /// <summary>
        /// This catalog declares no closed generic instantiation, so there is nothing to execute here. The
        /// method still exists so every generated catalog has one exercise surface (04 section 8).
        /// </summary>
        public static void ExerciseClosedGenericRoots()
        {
        }
    }
}
