// GameCore.Content.Compiler - deterministic catalog emitter (GC-003).
//
// Reproducibility contract: generated bytes depend only on the validated description. Fixed declaration
// order, LF line endings, no timestamps, no machine paths, no culture-sensitive formatting, and every table
// canonically sorted by derived 128-bit key rather than declaration order. The catalog fingerprint is computed
// from the same canonical tables the runtime catalog builds, and the file hash is computed over the file
// prefix that precedes the hash declaration so the recorded value can be reproduced independently.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Security.Cryptography;
using System.Text;
using GameCore.Contracts;

namespace GameCore.Content.Compiler
{
    /// <summary>Emits one deterministic generated C# catalog from a validated description.</summary>
    public static class CatalogEmitter
    {
        /// <summary>Exact declaration whose value is the file-prefix hash; the hash input ends just before it.</summary>
        public const string HashDeclaration = "        public const string CatalogFileHash = ";

        /// <summary>Rendered name of the generated closed-generic AOT root method.</summary>
        public const string ClosedGenericRootMethodName = "RootClosedGenericInstantiations";

        /// <summary>
        /// Prefix <see cref="FilePrefixHash"/> returns when the recorded hash does not cover the file content,
        /// so a caller can distinguish a mismatch verdict from a hash value without a second API.
        /// </summary>
        public const string MismatchPrefix = "mismatch:";

        /// <summary>Emits the complete generated file (header comments, assembly attributes, catalog class).</summary>
        public static string Emit(CatalogDescription description)
        {
            if (description == null)
            {
                throw new ArgumentNullException(nameof(description));
            }

            EmitTables(description, out GeneratedTable[] groups, out GeneratedSchema[] schemas);
            string fingerprint = ComputeFingerprint(description, groups, schemas);
            string body = EmitBody(description, groups, schemas, fingerprint);
            int marker = body.IndexOf(HashDeclaration, StringComparison.Ordinal);
            if (marker < 0)
            {
                throw new CatalogDescriptionException("the emitter template lost its hash declaration line.");
            }

            string hashInput = body.Substring(0, marker);
            return body.Replace("@@CATALOG_FILE_HASH@@", Sha256Hex(hashInput));
        }

        /// <summary>Hash of the emitted file prefix; identical to the value embedded in the generated file.</summary>
        public static string FilePrefixHash(string generatedText)
        {
            if (generatedText == null)
            {
                throw new ArgumentNullException(nameof(generatedText));
            }

            int marker = generatedText.IndexOf(HashDeclaration, StringComparison.Ordinal);
            if (marker < 0)
            {
                throw new CatalogDescriptionException("the generated text has no catalog file-hash declaration.");
            }

            string hashInput = generatedText.Substring(0, marker);
            int firstQuote = marker + HashDeclaration.Length;
            if (firstQuote >= generatedText.Length || generatedText[firstQuote] != '"')
            {
                throw new CatalogDescriptionException("the catalog file-hash declaration has no value.");
            }

            int secondQuote = generatedText.IndexOf('"', firstQuote + 1);
            if (secondQuote < 0)
            {
                throw new CatalogDescriptionException("the catalog file-hash value is not terminated.");
            }

            string declared = generatedText.Substring(firstQuote + 1, secondQuote - firstQuote - 1);
            string computed = Sha256Hex(hashInput);
            return string.Equals(declared, computed, StringComparison.Ordinal) ? computed : MismatchPrefix + declared;
        }

        /// <summary>
        /// Computes the catalog fingerprint a runtime catalog reports for these declarations. Declared as a
        /// public helper so a test can assert the generated literal against a freshly built production catalog.
        /// </summary>
        public static string ComputeFingerprint(CatalogDescription description)
        {
            if (description == null)
            {
                throw new ArgumentNullException(nameof(description));
            }

            EmitTables(description, out GeneratedTable[] groups, out GeneratedSchema[] schemas);
            return ComputeFingerprint(description, groups, schemas);
        }

        private static string ComputeFingerprint(
            CatalogDescription description,
            GeneratedTable[] groups,
            GeneratedSchema[] schemas)
        {
            List<FactoryRegistration> factories = new List<FactoryRegistration>();
            List<SchemaRegistration> registrations = new List<SchemaRegistration>();

            for (int g = 0; g < groups.Length; g++)
            {
                FactoryKind kind = CatalogFactoryKinds.Parse(groups[g].Group.Kind);
                for (int i = 0; i < groups[g].Entries.Length; i++)
                {
                    GeneratedEntry entry = groups[g].Entries[i];
                    factories.Add(new FactoryRegistration(
                        new FactoryKey(entry.Key, entry.Entry.KeyVersion),
                        kind,
                        ParseIdentity(entry.Entry.OwnerPackageIdHex),
                        ParseIdentity(entry.Entry.ImplementationIdHex),
                        entry.Entry.KeyVersion));
                }
            }

            for (int s = 0; s < schemas.Length; s++)
            {
                GeneratedSchema schema = schemas[s];
                Id128 schemaId = schema.SchemaId;
                Id128 serializerKey = StableNameKeyDerivation.Derive(schema.Declaration.StableName);
                Id128 owner = ParseIdentity(schema.Declaration.OwnerPackageIdHex);

                factories.Add(new FactoryRegistration(
                    new FactoryKey(serializerKey, schema.Declaration.SerializerKeyVersion),
                    FactoryKind.Serializer,
                    owner,
                    schemaId,
                    schema.Declaration.SchemaVersion));

                registrations.Add(new SchemaRegistration(
                    new SchemaRef(new SchemaId(schemaId), schema.Declaration.SchemaVersion),
                    owner,
                    new FactoryKey(serializerKey, schema.Declaration.SerializerKeyVersion),
                    schema.Declaration.IsRequired));
            }

            List<Id128> features = new List<Id128>();
            for (int i = 0; i < description.SupportedFeatureHexIds.Count; i++)
            {
                features.Add(ParseIdentity(description.SupportedFeatureHexIds[i]));
            }

            return CatalogFingerprint.Compute(factories, registrations, features).ToHex();
        }

        private static void EmitTables(
            CatalogDescription description,
            out GeneratedTable[] groups,
            out GeneratedSchema[] schemas)
        {
            groups = new GeneratedTable[description.Groups.Count];
            for (int g = 0; g < groups.Length; g++)
            {
                groups[g] = GeneratedTable.Create(description.Groups[g]);
            }

            schemas = new GeneratedSchema[description.Schemas.Count];
            for (int s = 0; s < schemas.Length; s++)
            {
                schemas[s] = GeneratedSchema.Create(description.Schemas[s]);
            }

            // Canonical emission order: groups by ordinal table name, schemas by schema identity. Declaration
            // order never reaches the generated file, so two descriptions with the same declarations produce
            // byte-identical output (P-008).
            Array.Sort(groups, CompareTables);
            Array.Sort(schemas, CompareSchemas);
        }

        private static int CompareTables(GeneratedTable left, GeneratedTable right) =>
            string.CompareOrdinal(left.Group.TableName, right.Group.TableName);

        private static int CompareSchemas(GeneratedSchema left, GeneratedSchema right) =>
            left.SchemaId.CompareTo(right.SchemaId);

        private static string EmitBody(
            CatalogDescription description,
            GeneratedTable[] groups,
            GeneratedSchema[] schemas,
            string fingerprint)
        {
            StringBuilder builder = new StringBuilder(16 * 1024);

            builder.Append("// <auto-generated />\n");
            builder.Append("// Generated by GameCore.Content.Compiler.CatalogEmitter; do not edit by hand.\n");
            builder.Append("// Description format: ").Append(description.DescriptionFormat).Append('\n');
            builder.Append("// Protocol: ").Append(description.ProtocolMajor).Append('.').Append(description.ProtocolMinor).Append('\n');
            builder.Append("// Deterministic output: fixed declaration order, canonical key order inside every table,\n");
            builder.Append("// no timestamps, no machine paths, no culture-sensitive formatting, LF line endings.\n");
            builder.Append("// Regenerating from the same validated description must reproduce this file byte for byte.\n");
            builder.Append("// Regenerate with the GameCore content compiler (menu GameCore/Content/Generate Catalog or\n");
            builder.Append("// -executeMethod GameCore.Content.Compiler.Editor.CatalogGeneratorMenu.GenerateFromCommandLine).\n");
            builder.Append('\n');
            builder.Append("#nullable enable\n");
            builder.Append("using System;\n");
            builder.Append("using System.Collections.Generic;\n");
            builder.Append("using GameCore.Contracts;\n");
            for (int i = 0; i < description.Code.UsingDirectives.Count; i++)
            {
                builder.Append("using ").Append(description.Code.UsingDirectives[i]).Append(";\n");
            }

            builder.Append('\n');
            for (int i = 0; i < description.Code.AssemblyAttributes.Count; i++)
            {
                builder.Append("[assembly: ").Append(description.Code.AssemblyAttributes[i]).Append("]\n");
            }

            if (description.Code.AssemblyAttributes.Count != 0)
            {
                builder.Append('\n');
            }

            builder.Append("namespace ").Append(description.GeneratedNamespace).Append('\n');
            builder.Append("{\n");
            builder.Append("    /// <summary>\n");
            builder.Append("    /// Generated closed registration catalog. Every registration is a direct reference, so managed\n");
            builder.Append("    /// stripping cannot remove a registration the player resolves by key at runtime (04 section 8).\n");
            builder.Append("    /// </summary>\n");
            builder.Append("    public static class ").Append(description.ClassName).Append('\n');
            builder.Append("    {\n");
            EmitConstants(builder, description, fingerprint);
            EmitKeys(builder, groups, schemas);
            EmitTables(builder, description, groups, schemas);
            EmitLookups(builder, groups);
            EmitSchemaTypes(builder, schemas);
            EmitCatalogFactory(builder, description, groups, schemas);
            EmitCodeDirectives(builder, description);

            builder.Append("        /// <summary>Hash of the generated source that precedes this declaration.</summary>\n");
            builder.Append(HashDeclaration).Append("\"@@CATALOG_FILE_HASH@@\";\n");
            builder.Append("    }\n");
            builder.Append("}\n");
            return builder.ToString();
        }

        private static void EmitConstants(StringBuilder builder, CatalogDescription description, string fingerprint)
        {
            builder.Append("        /// <summary>File name this catalog was generated into.</summary>\n");
            builder.Append("        public const string GeneratedFileName = \"").Append(description.GeneratedFileName).Append("\";\n");
            builder.Append('\n');
            builder.Append("        /// <summary>Description format this catalog was generated from.</summary>\n");
            builder.Append("        public const string DescriptionFormat = \"").Append(description.DescriptionFormat).Append("\";\n");
            builder.Append('\n');
            builder.Append("        /// <summary>Declared protocol version this catalog was generated for.</summary>\n");
            builder.Append("        public const string ProtocolVersion = \"").Append(description.ProtocolMajor).Append('.')
                .Append(description.ProtocolMinor).Append("\";\n");
            builder.Append('\n');
            builder.Append("        /// <summary>Hash algorithm used by CatalogFileHash.</summary>\n");
            builder.Append("        public const string HashAlgorithm = \"SHA-256\";\n");
            builder.Append('\n');
            builder.Append("        /// <summary>Exact scope of CatalogFileHash, so the recorded value can be reproduced independently.</summary>\n");
            builder.Append("        public const string CatalogFileHashScope = \"")
                .Append(EscapeStringLiteral(
                    "SHA-256 over the UTF-8 bytes, with LF line endings, of the file prefix that ends immediately "
                    + "before the eight-space-indented CatalogFileHash declaration; that prefix ends with the "
                    + "newline that terminates the previous line, and the declaration itself, its value and the "
                    + "rest of the file are excluded"))
                .Append("\";\n");
            builder.Append('\n');
            builder.Append("        /// <summary>Scope of CatalogFingerprint, identical to GameCore.Contracts.CatalogFingerprint.Scope.</summary>\n");
            builder.Append("        public const string CatalogFingerprintScope = \"")
                .Append(EscapeStringLiteral(CatalogFingerprint.Scope))
                .Append("\";\n");
            builder.Append('\n');
            builder.Append("        /// <summary>Canonical fingerprint of the registrations below (P-028, P-053).</summary>\n");
            builder.Append("        public const string CatalogFingerprint = \"")
                .Append(fingerprint)
                .Append("\";\n");
            builder.Append('\n');
            builder.Append("        /// <summary>Supported protocol feature ids, in canonical identity order (P-055).</summary>\n");
            builder.Append("        public static readonly Id128[] SupportedFeatureIds =\n");
            builder.Append("        {\n");
            for (int i = 0; i < description.SupportedFeatureHexIds.Count; i++)
            {
                Id128 feature = ParseIdentity(description.SupportedFeatureHexIds[i]);
                builder.Append("            new Id128(0x").Append(Hex(feature.High)).Append("UL, 0x").Append(Hex(feature.Low)).Append("UL),\n");
            }

            builder.Append("        };\n");
            builder.Append('\n');
        }

        private static void EmitKeys(StringBuilder builder, GeneratedTable[] groups, GeneratedSchema[] schemas)
        {
            for (int g = 0; g < groups.Length; g++)
            {
                for (int i = 0; i < groups[g].Entries.Length; i++)
                {
                    GeneratedEntry entry = groups[g].Entries[i];
                    builder.Append("        /// <summary>Generated key of ").Append(EscapeStringLiteral(entry.Entry.StableName))
                        .Append(" ('").Append(EscapeStringLiteral(entry.Entry.StableName)).Append("').</summary>\n");
                    builder.Append("        public static readonly FactoryKey ").Append(entry.Entry.KeyName)
                        .Append(" = new FactoryKey(new Id128(0x").Append(Hex(entry.Key.High))
                        .Append("UL, 0x").Append(Hex(entry.Key.Low)).Append("UL), ")
                        .Append(entry.Entry.KeyVersion.ToString(CultureInfo.InvariantCulture)).Append("U);\n");
                    builder.Append('\n');
                }
            }

            for (int s = 0; s < schemas.Length; s++)
            {
                GeneratedSchema schema = schemas[s];
                builder.Append("        /// <summary>Generated serializer key of schema ").Append(schema.Declaration.SchemaIdHex)
                    .Append(" ('").Append(EscapeStringLiteral(schema.Declaration.StableName)).Append("').</summary>\n");
                builder.Append("        public static readonly FactoryKey ").Append(schema.Declaration.SerializerKeyName)
                    .Append(" = new FactoryKey(new Id128(0x").Append(Hex(schema.SerializerKey.High))
                    .Append("UL, 0x").Append(Hex(schema.SerializerKey.Low)).Append("UL), ")
                    .Append(schema.Declaration.SerializerKeyVersion.ToString(CultureInfo.InvariantCulture)).Append("U);\n");
                builder.Append('\n');
            }
        }

        private static void EmitTables(
            StringBuilder builder,
            CatalogDescription description,
            GeneratedTable[] groups,
            GeneratedSchema[] schemas)
        {
            for (int g = 0; g < groups.Length; g++)
            {
                GeneratedTable table = groups[g];
                builder.Append("        /// <summary>Generated registrations of ").Append(table.Group.Kind)
                    .Append(", in canonical key order, each bound to a direct constructor reference.</summary>\n");
                builder.Append("        public static readonly BoundRegistration<").Append(table.Group.InterfaceType)
                    .Append(">[] ").Append(table.Group.TableName).Append(" =\n");
                builder.Append("        {\n");
                for (int i = 0; i < table.Entries.Length; i++)
                {
                    GeneratedEntry entry = table.Entries[i];
                    builder.Append("            new BoundRegistration<").Append(table.Group.InterfaceType).Append(">(\n");
                    builder.Append("                ").Append(entry.Entry.KeyName).Append(",\n");
                    builder.Append("                \"").Append(EscapeStringLiteral(entry.Entry.StableName)).Append("\",\n");
                    builder.Append("                ").Append(entry.Entry.ImplementationExpression).Append("),\n");
                }

                builder.Append("        };\n");
                builder.Append('\n');
                builder.Append("        /// <summary>Generated keys of ").Append(table.Group.TableName)
                    .Append(", in the same canonical order.</summary>\n");
                builder.Append("        public static readonly FactoryKey[] ").Append(table.Group.KeysName).Append(" =\n");
                builder.Append("        {\n");
                for (int i = 0; i < table.Entries.Length; i++)
                {
                    builder.Append("            ").Append(table.Entries[i].Entry.KeyName).Append(",\n");
                }

                builder.Append("        };\n");
                builder.Append('\n');
                builder.Append("        /// <summary>\n");
                builder.Append("        /// Catalog registrations of ").Append(table.Group.Kind)
                    .Append(", in the same canonical order as ").Append(table.Group.TableName).Append(".\n");
                builder.Append("        /// Every entry carries its own owner package and precompiled implementation identity, so the\n");
                builder.Append("        /// runtime catalog hashes exactly the declarations this file was generated from (P-009, P-028).\n");
                builder.Append("        /// </summary>\n");
                builder.Append("        public static readonly FactoryRegistration[] ").Append(table.Group.TableName)
                    .Append("CatalogRegistrations =\n");
                builder.Append("        {\n");
                for (int i = 0; i < table.Entries.Length; i++)
                {
                    GeneratedEntry entry = table.Entries[i];
                    builder.Append("            new FactoryRegistration(\n");
                    builder.Append("                ").Append(entry.Entry.KeyName).Append(",\n");
                    builder.Append("                FactoryKind.").Append(table.Group.Kind).Append(",\n");
                    builder.Append("                new Id128(0x").Append(Hex(ParseIdentity(entry.Entry.OwnerPackageIdHex).High))
                        .Append("UL, 0x").Append(Hex(ParseIdentity(entry.Entry.OwnerPackageIdHex).Low)).Append("UL),\n");
                    builder.Append("                new Id128(0x").Append(Hex(ParseIdentity(entry.Entry.ImplementationIdHex).High))
                        .Append("UL, 0x").Append(Hex(ParseIdentity(entry.Entry.ImplementationIdHex).Low)).Append("UL),\n");
                    builder.Append("                ").Append(entry.Entry.KeyVersion.ToString(CultureInfo.InvariantCulture)).Append("U),\n");
                }

                builder.Append("        };\n");
                builder.Append('\n');
            }

            builder.Append("        /// <summary>Validated schema registrations, in canonical schema-id order.</summary>\n");
            builder.Append("        public static readonly SchemaRegistration[] SchemaRegistrations =\n");
            builder.Append("        {\n");
            for (int s = 0; s < schemas.Length; s++)
            {
                GeneratedSchema schema = schemas[s];
                builder.Append("            new SchemaRegistration(\n");
                builder.Append("                new SchemaRef(new SchemaId(new Id128(0x").Append(Hex(schema.SchemaId.High))
                    .Append("UL, 0x").Append(Hex(schema.SchemaId.Low)).Append("UL)), ")
                    .Append(schema.Declaration.SchemaVersion.ToString(CultureInfo.InvariantCulture)).Append("U),\n");
                builder.Append("                new Id128(0x").Append(Hex(schema.OwnerPackageId.High)).Append("UL, 0x")
                    .Append(Hex(schema.OwnerPackageId.Low)).Append("UL),\n");
                builder.Append("                ").Append(schema.Declaration.SerializerKeyName).Append(",\n");
                builder.Append("                ").Append(schema.Declaration.IsRequired ? "true" : "false").Append("),\n");
            }

            builder.Append("        };\n");
            builder.Append('\n');
        }

        private static void EmitLookups(StringBuilder builder, GeneratedTable[] groups)
        {
            for (int g = 0; g < groups.Length; g++)
            {
                GeneratedTable table = groups[g];
                builder.Append("        /// <summary>\n");
                builder.Append("        /// Resolves one generated registration by key. A key absent from this table returns false with a\n");
                builder.Append("        /// null implementation; nothing is constructed by reflection or runtime type discovery (04 section 8).\n");
                builder.Append("        /// </summary>\n");
                builder.Append("        public static bool ").Append(table.Group.LookupMethodName).Append("(FactoryKey key, out ")
                    .Append(table.Group.InterfaceType).Append("? implementation)\n");
                builder.Append("        {\n");
                builder.Append("            for (int i = 0; i < ").Append(table.Group.TableName).Append(".Length; i++)\n");
                builder.Append("            {\n");
                builder.Append("                if (").Append(table.Group.TableName).Append("[i].Key.Equals(key))\n");
                builder.Append("                {\n");
                builder.Append("                    implementation = ").Append(table.Group.TableName).Append("[i].Implementation;\n");
                builder.Append("                    return true;\n");
                builder.Append("                }\n");
                builder.Append("            }\n");
                builder.Append('\n');
                builder.Append("            implementation = null;\n");
                builder.Append("            return false;\n");
                builder.Append("        }\n");
                builder.Append('\n');
            }
        }

        /// <summary>
        /// Emits, for every declared schema, its generated value type and its generated serializer. The serializer
        /// declares its field table once and derives both directions from it: writing walks the declared fields in
        /// ascending field-id order, reading performs the structural envelope walk and then decodes each recorded
        /// declared field. Required-field enforcement, the required-feature gate and the checksum all come from
        /// <see cref="GeneratedSerializerBase"/>, so every generated serializer obeys the same rules (05 s6).
        /// </summary>
        private static void EmitSchemaTypes(StringBuilder builder, GeneratedSchema[] schemas)
        {
            for (int s = 0; s < schemas.Length; s++)
            {
                EmitValueType(builder, schemas[s]);
                EmitSerializer(builder, schemas[s]);
            }

            builder.Append("        /// <summary>\n");
            builder.Append("        /// Generated serializer instances, one per declared schema, in the same canonical order as\n");
            builder.Append("        /// SchemaRegistrations. Instances are constructed directly; no serializer is discovered at runtime.\n");
            builder.Append("        /// </summary>\n");
            builder.Append("        public static readonly ISchemaSerializer[] Serializers =\n");
            builder.Append("        {\n");
            for (int s = 0; s < schemas.Length; s++)
            {
                builder.Append("            new ").Append(schemas[s].Declaration.SerializerTypeName).Append("(),\n");
            }

            builder.Append("        };\n");
            builder.Append('\n');
        }

        /// <summary>Verbatim identifier from the validated description; every member name is already a valid identifier.</summary>
        private static string EscapedIdentifier(string name) => name;

        /// <summary>
        /// Constructor parameter of one generated field. A leading-underscore-free camel-cased form is derived
        /// from the field name so a description never has to declare parameter names twice.
        /// </summary>
        private static string ParameterName(string fieldName)
        {
            if (fieldName.Length == 0)
            {
                return "value";
            }

            char first = fieldName[0];
            if (first >= 'A' && first <= 'Z')
            {
                return char.ToLowerInvariant(first) + fieldName.Substring(1);
            }

            return fieldName;
        }

        private static void EmitValueType(StringBuilder builder, GeneratedSchema schema)
        {
            CatalogSchemaDeclaration declaration = schema.Declaration;
            builder.Append("        /// <summary>\n");
            builder.Append("        /// Generated value of schema ").Append(declaration.SchemaIdHex).Append(" ('")
                .Append(EscapeStringLiteral(declaration.StableName)).Append("').\n");
            builder.Append("        /// Fields are declared in ascending field-id order, which is also the wire order (05 s6).\n");
            builder.Append("        /// </summary>\n");
            builder.Append("        public readonly struct ").Append(declaration.ValueTypeName).Append('\n');
            builder.Append("        {\n");

            for (int i = 0; i < declaration.Fields.Count; i++)
            {
                CatalogFieldDeclaration field = declaration.Fields[i];
                CatalogWireType wire = CatalogWireTypes.Find(field.WireType)!;
                builder.Append("            /// <summary>Field id ").Append(field.FieldId.ToString(CultureInfo.InvariantCulture))
                    .Append(", wire type ").Append(wire.Name)
                    .Append(field.Required ? ", required." : ", optional.").Append("</summary>\n");
                builder.Append("            public readonly ").Append(wire.CSharpType)
                    .Append(wire.IsNullableReference ? "?" : string.Empty).Append(' ')
                    .Append(EscapedIdentifier(field.Name)).Append(";\n");
            }

            builder.Append('\n');
            builder.Append("            public ").Append(declaration.ValueTypeName).Append('(');
            for (int i = 0; i < declaration.Fields.Count; i++)
            {
                CatalogFieldDeclaration field = declaration.Fields[i];
                CatalogWireType wire = CatalogWireTypes.Find(field.WireType)!;
                if (i != 0)
                {
                    builder.Append(", ");
                }

                builder.Append(wire.CSharpType).Append(wire.IsNullableReference ? "?" : string.Empty).Append(' ')
                    .Append(ParameterName(field.Name));
            }

            builder.Append(")\n");
            builder.Append("            {\n");
            for (int i = 0; i < declaration.Fields.Count; i++)
            {
                CatalogFieldDeclaration field = declaration.Fields[i];
                builder.Append("                ").Append(EscapedIdentifier(field.Name)).Append(" = ")
                    .Append(ParameterName(field.Name)).Append(";\n");
            }

            builder.Append("            }\n");
            builder.Append('\n');
            builder.Append("            /// <summary>Diagnostic form; never used as an identity (P-004).</summary>\n");
            builder.Append("            public override string ToString()\n");
            builder.Append("            {\n");
            builder.Append("                return \"").Append(EscapeStringLiteral(declaration.ValueTypeName)).Append('(');
            for (int i = 0; i < declaration.Fields.Count; i++)
            {
                CatalogFieldDeclaration field = declaration.Fields[i];
                if (i != 0)
                {
                    builder.Append(", ");
                }

                builder.Append(EscapeStringLiteral(field.Name + "=")).Append("\" + ");
                if (field.WireType == "Bytes")
                {
                    // A byte[] has no string form: the diagnostic carries the byte count, and a null reads
                    // as empty because an absent optional field and a null one both decode to null (05 s6).
                    builder.Append('(').Append(EscapedIdentifier(field.Name))
                        .Append(" ?? Array.Empty<byte>()).Length.ToString()");
                }
                else if (CatalogWireTypes.Find(field.WireType)!.IsNullableReference)
                {
                    builder.Append('(').Append(EscapedIdentifier(field.Name)).Append(" ?? \"<null>\")");
                }
                else
                {
                    builder.Append(EscapedIdentifier(field.Name));
                }

                builder.Append(" + \"");
            }

            builder.Append(")\";\n");
            builder.Append("            }\n");
            builder.Append("        }\n");
            builder.Append('\n');
        }

        private static void EmitSerializer(StringBuilder builder, GeneratedSchema schema)
        {
            CatalogSchemaDeclaration declaration = schema.Declaration;
            builder.Append("        /// <summary>\n");
            builder.Append("        /// Generated serializer of schema ").Append(declaration.SchemaIdHex)
                .Append(" version ").Append(declaration.SchemaVersion.ToString(CultureInfo.InvariantCulture))
                .Append(". Canonical envelope format only: no reflection,\n");
            builder.Append("        /// no dynamic type construction (05 s6, P-054).\n");
            builder.Append("        /// </summary>\n");
            builder.Append("        public sealed class ").Append(declaration.SerializerTypeName)
                .Append(" : GeneratedSerializerBase\n");
            builder.Append("        {\n");
            builder.Append("            private static readonly GeneratedFieldSlot[] DeclaredFieldSlots =\n");
            builder.Append("            {\n");
            for (int i = 0; i < declaration.Fields.Count; i++)
            {
                CatalogFieldDeclaration field = declaration.Fields[i];
                CatalogWireType wire = CatalogWireTypes.Find(field.WireType)!;
                builder.Append("                new GeneratedFieldSlot(").Append(field.FieldId.ToString(CultureInfo.InvariantCulture))
                    .Append(", WireType.").Append(wire.Name).Append(", ")
                    .Append(field.Required ? "true" : "false").Append("),\n");
            }

            builder.Append("            };\n");
            builder.Append('\n');
            builder.Append("            public ").Append(declaration.SerializerTypeName).Append("()\n");
            builder.Append("                : base(\n");
            builder.Append("                    ").Append(declaration.SerializerKeyName).Append(",\n");
            builder.Append("                    new SchemaRef(new SchemaId(new Id128(0x").Append(Hex(schema.SchemaId.High))
                .Append("UL, 0x").Append(Hex(schema.SchemaId.Low)).Append("UL)), ")
                .Append(declaration.SchemaVersion.ToString(CultureInfo.InvariantCulture)).Append("U),\n");
            builder.Append("                    SupportedFeatureIds)\n");
            builder.Append("            {\n");
            builder.Append("            }\n");
            builder.Append('\n');
            builder.Append("            /// <summary>Declared fields in ascending field-id order.</summary>\n");
            builder.Append("            protected override IReadOnlyList<GeneratedFieldSlot> DeclaredFields => DeclaredFieldSlots;\n");
            builder.Append('\n');
            builder.Append("            /// <summary>Writes one value as a canonical envelope document with a trailing checksum.</summary>\n");
            builder.Append("            public byte[] Serialize(").Append(declaration.ValueTypeName).Append(" value)\n");
            builder.Append("            {\n");
            builder.Append("                EnvelopeWriter writer = CreateWriter();\n");
            for (int i = 0; i < declaration.Fields.Count; i++)
            {
                CatalogFieldDeclaration field = declaration.Fields[i];
                CatalogWireType wire = CatalogWireTypes.Find(field.WireType)!;
                builder.Append("                writer.").Append(wire.WriteMethod).Append('(')
                    .Append(field.FieldId.ToString(CultureInfo.InvariantCulture)).Append(", value.")
                    .Append(EscapedIdentifier(field.Name)).Append(");\n");
            }

            builder.Append("                writer.WriteChecksum();\n");
            builder.Append("                return writer.ToArray();\n");
            builder.Append("            }\n");
            builder.Append('\n');
            builder.Append("            /// <summary>\n");
            builder.Append("            /// Validates one document against this schema and decodes its declared fields. A false result\n");
            builder.Append("            /// reports the exact envelope error and leaves the value at its default.\n");
            builder.Append("            /// </summary>\n");
            builder.Append("            public bool TryDeserialize(byte[] document, out ").Append(declaration.ValueTypeName)
                .Append(" value, out EnvelopeError error)\n");
            builder.Append("            {\n");
            builder.Append("                value = default(").Append(declaration.ValueTypeName).Append(");\n");
            builder.Append("                GeneratedFieldBuffer buffer = new GeneratedFieldBuffer();\n");
            builder.Append("                if (!TryReadDeclaredFields(document, buffer, out error))\n");
            builder.Append("                {\n");
            builder.Append("                    return false;\n");
            builder.Append("                }\n");
            builder.Append('\n');
            builder.Append("                EnvelopeReader reader = new EnvelopeReader(document);\n");
            for (int i = 0; i < declaration.Fields.Count; i++)
            {
                CatalogFieldDeclaration field = declaration.Fields[i];
                CatalogWireType wire = CatalogWireTypes.Find(field.WireType)!;
                builder.Append("                ").Append(wire.CSharpType).Append(wire.IsNullableReference ? "?" : string.Empty)
                    .Append(" value").Append(i.ToString(CultureInfo.InvariantCulture)).Append(" = default(")
                    .Append(wire.CSharpType).Append(wire.IsNullableReference ? "?" : string.Empty).Append(");\n");
            }

            builder.Append("                for (int i = 0; i < buffer.Count; i++)\n");
            builder.Append("                {\n");
            builder.Append("                    EnvelopeField recorded = buffer.Field(i);\n");
            builder.Append("                    if (!reader.TrySeekTo(buffer.RecordOffset(i)))\n");
            builder.Append("                    {\n");
            builder.Append("                        error = reader.LastError;\n");
            builder.Append("                        return false;\n");
            builder.Append("                    }\n");
            builder.Append('\n');
            builder.Append("                    switch (recorded.FieldId)\n");
            builder.Append("                    {\n");
            for (int i = 0; i < declaration.Fields.Count; i++)
            {
                EmitFieldCase(builder, declaration.Fields[i], i);
            }

            builder.Append("                        default:\n");
            builder.Append("                            break;\n");
            builder.Append("                    }\n");
            builder.Append("                }\n");
            builder.Append('\n');
            builder.Append("                // A declared field the document omitted keeps its default, and every declared field\n");
            builder.Append("                // is assigned exactly once, so the generated value type stays immutable (05 s6, P-054).\n");
            builder.Append("                value = new ").Append(declaration.ValueTypeName).Append('(');
            for (int i = 0; i < declaration.Fields.Count; i++)
            {
                if (i != 0)
                {
                    builder.Append(", ");
                }

                builder.Append("value").Append(i.ToString(CultureInfo.InvariantCulture));
            }

            builder.Append(");\n");
            builder.Append("                error = EnvelopeError.None;\n");
            builder.Append("                return true;\n");
            builder.Append("            }\n");
            builder.Append("        }\n");
            builder.Append('\n');
        }

        private static void EmitFieldCase(StringBuilder builder, CatalogFieldDeclaration field, int index)
        {
            CatalogWireType wire = CatalogWireTypes.Find(field.WireType)!;
            string fieldVar = "field" + index.ToString(CultureInfo.InvariantCulture);
            string valueVar = fieldVar + "Value";
            string bitsVar = fieldVar + "Bits";
            string indent = "                        ";

            builder.Append(indent).Append("case ").Append(field.FieldId.ToString(CultureInfo.InvariantCulture)).Append(":\n");
            builder.Append(indent).Append("{\n");
            builder.Append(indent).Append("    if (!reader.TryReadField(out EnvelopeField ").Append(fieldVar).Append("))\n");
            builder.Append(indent).Append("    {\n");
            builder.Append(indent).Append("        error = reader.LastError;\n");
            builder.Append(indent).Append("        return false;\n");
            builder.Append(indent).Append("    }\n");
            builder.Append('\n');

            if (field.WireType == "Float32")
            {
                builder.Append(indent).Append("    uint ").Append(bitsVar).Append(";\n");
            }
            else if (field.WireType == "Float64")
            {
                builder.Append(indent).Append("    ulong ").Append(bitsVar).Append(";\n");
            }

            builder.Append(indent).Append("    ").Append(wire.CSharpType)
                .Append(wire.IsNullableReference ? "?" : string.Empty).Append(' ').Append(valueVar).Append(";\n");
            builder.Append(indent).Append("    if (!reader.").Append(wire.ReadMethod).Append('(').Append(fieldVar)
                .Append(", out ").Append(valueVar);
            if (field.WireType == "Float32" || field.WireType == "Float64")
            {
                builder.Append(", out ").Append(bitsVar);
            }

            builder.Append("))\n");
            builder.Append(indent).Append("    {\n");
            builder.Append(indent).Append("        error = reader.LastError;\n");
            builder.Append(indent).Append("        return false;\n");
            builder.Append(indent).Append("    }\n");
            builder.Append('\n');
            builder.Append(indent).Append("    value").Append(index.ToString(CultureInfo.InvariantCulture))
                .Append(" = ").Append(valueVar).Append(";\n");
            builder.Append(indent).Append("    break;\n");
            builder.Append(indent).Append("}\n");
        }

        private static void EmitCatalogFactory(
            StringBuilder builder,
            CatalogDescription description,
            GeneratedTable[] groups,
            GeneratedSchema[] schemas)
        {
            builder.Append("        /// <summary>\n");
            builder.Append("        /// Validates every generated table under the production catalog rules and returns the immutable\n");
            builder.Append("        /// catalog, or the exact structured rejections (P-009). Nothing is exposed on rejection.\n");
            builder.Append("        /// </summary>\n");
            builder.Append("        public static CatalogBuildResult BuildCatalog()\n");
            builder.Append("        {\n");
            builder.Append("            FactoryRegistration[] groupRegistrations = GroupCatalogRegistrations();\n");
            builder.Append("            FactoryRegistration[] all = new FactoryRegistration[groupRegistrations.Length + SchemaRegistrations.Length];\n");
            builder.Append("            Array.Copy(groupRegistrations, 0, all, 0, groupRegistrations.Length);\n");
            builder.Append('\n');
            builder.Append("            for (int i = 0; i < SchemaRegistrations.Length; i++)\n");
            builder.Append("            {\n");
            builder.Append("                SchemaRegistration registration = SchemaRegistrations[i];\n");
            builder.Append("                all[groupRegistrations.Length + i] = new FactoryRegistration(\n");
            builder.Append("                    registration.Serializer,\n");
            builder.Append("                    FactoryKind.Serializer,\n");
            builder.Append("                    registration.OwnerPackageId,\n");
            builder.Append("                    registration.Schema.Id.Value,\n");
            builder.Append("                    registration.Schema.Version);\n");
            builder.Append("            }\n");
            builder.Append('\n');
            builder.Append("            return ImmutableCatalog.Build(all, SchemaRegistrations, SupportedFeatureIds, Serializers);\n");
            builder.Append("        }\n");
            builder.Append('\n');
            builder.Append("        /// <summary>Every group's catalog registrations concatenated in declaration order.</summary>\n");
            builder.Append("        private static FactoryRegistration[] GroupCatalogRegistrations()\n");
            builder.Append("        {\n");
            if (groups.Length == 0)
            {
                builder.Append("            return Array.Empty<FactoryRegistration>();\n");
            }
            else
            {
                int total = 0;
                for (int g = 0; g < groups.Length; g++)
                {
                    total += groups[g].Entries.Length;
                }

                builder.Append("            FactoryRegistration[] all = new FactoryRegistration[")
                    .Append(total.ToString(CultureInfo.InvariantCulture)).Append("];\n");
                builder.Append("            int offset = 0;\n");
                for (int g = 0; g < groups.Length; g++)
                {
                    string name = groups[g].Group.TableName + "CatalogRegistrations";
                    int count = groups[g].Entries.Length;
                    if (count == 0)
                    {
                        continue;
                    }

                    builder.Append("            Array.Copy(").Append(name).Append(", 0, all, offset, ")
                        .Append(count.ToString(CultureInfo.InvariantCulture)).Append(");\n");
                    builder.Append("            offset += ").Append(count.ToString(CultureInfo.InvariantCulture)).Append(";\n");
                }

                builder.Append("            return all;\n");
            }

            builder.Append("        }\n");
            builder.Append('\n');
            builder.Append("        /// <summary>\n");
            builder.Append("        /// Builds the catalog and asserts that its fingerprint equals the value emitted into this file, so a\n");
            builder.Append("        /// stale generated file cannot describe a catalog whose declarations changed (P-028).\n");
            builder.Append("        /// </summary>\n");
            builder.Append("        public static CatalogBuildResult BuildVerifiedCatalog(out ContentHash observedFingerprint)\n");
            builder.Append("        {\n");
            builder.Append("            CatalogBuildResult result = BuildCatalog();\n");
            builder.Append("            observedFingerprint = result.Catalog == null ? ContentHash.Empty : result.Catalog.Fingerprint;\n");
            builder.Append("            return result;\n");
            builder.Append("        }\n");
            builder.Append('\n');
            builder.Append("        /// <summary>\n");
            builder.Append("        /// Fingerprint the generated declarations must produce. A test compares this literal against a\n");
            builder.Append("        /// freshly built catalog so an unnoticed declaration change fails instead of being ignored.\n");
            builder.Append("        /// </summary>\n");
            builder.Append("        public static bool FingerprintMatchesGeneratedCatalog(out ContentHash observed)\n");
            builder.Append("        {\n");
            builder.Append("            CatalogBuildResult result = BuildVerifiedCatalog(out observed);\n");
            builder.Append("            return result.Catalog != null && string.Equals(observed.ToHex(), CatalogFingerprint, StringComparison.Ordinal);\n");
            builder.Append("        }\n");
            builder.Append('\n');
            if (description.Code.ClosedGenericRootStatements.Count != 0)
            {
                builder.Append("        /// <summary>\n");
                builder.Append("        /// Roots every closed generic instantiation this catalog depends on, so the instantiation exists in an\n");
                builder.Append("        /// AOT/IL2CPP player even when no other reachable code calls it (04 section 8 item 3).\n");
                builder.Append("        /// </summary>\n");
                builder.Append("        public static void ").Append(ClosedGenericRootMethodName).Append("()\n");
                builder.Append("        {\n");
                for (int i = 0; i < description.Code.ClosedGenericRootStatements.Count; i++)
                {
                    // A statement fragment is emitted as an expression statement, so the emitter supplies the
                    // terminator; the fragment itself may not contain one.
                    builder.Append("            ").Append(description.Code.ClosedGenericRootStatements[i]).Append(";\n");
                }

                builder.Append("        }\n");
                builder.Append('\n');
                builder.Append("        /// <summary>True because this catalog emits closed generic roots.</summary>\n");
                builder.Append("        public const bool HasClosedGenericRoots = true;\n");
                builder.Append('\n');
            }
            else
            {
                builder.Append("        /// <summary>True because this catalog emits closed generic roots.</summary>\n");
                builder.Append("        public const bool HasClosedGenericRoots = false;\n");
                builder.Append('\n');
            }
        }

        private static void EmitCodeDirectives(StringBuilder builder, CatalogDescription description)
        {
            builder.Append("        /// <summary>Number of generated registration groups.</summary>\n");
            builder.Append("        public const int RegistrationGroupCount = ")
                .Append(description.Groups.Count.ToString(CultureInfo.InvariantCulture)).Append(";\n");
            builder.Append('\n');
            builder.Append("        /// <summary>Number of declared schemas.</summary>\n");
            builder.Append("        public const int SchemaCount = ")
                .Append(description.Schemas.Count.ToString(CultureInfo.InvariantCulture)).Append(";\n");
            builder.Append('\n');
        }

        internal static Id128 ParseIdentity(string hex)
        {
            if (!Id128Codec.TryParseHex(hex, out Id128 value))
            {
                throw new CatalogDescriptionException("'" + hex + "' is not a canonical 32-character lowercase hexadecimal id.");
            }

            return value;
        }

        internal static string Hex(ulong value) => value.ToString("X16", CultureInfo.InvariantCulture);

        internal static string Sha256Hex(string content)
        {
            using (SHA256 sha256 = SHA256.Create())
            {
                byte[] hash = sha256.ComputeHash(new UTF8Encoding(false).GetBytes(content));
                StringBuilder builder = new StringBuilder(hash.Length * 2);
                for (int i = 0; i < hash.Length; i++)
                {
                    builder.Append(hash[i].ToString("x2", CultureInfo.InvariantCulture));
                }

                return builder.ToString();
            }
        }

        internal static string EscapeStringLiteral(string text)
        {
            StringBuilder builder = new StringBuilder(text.Length + 8);
            for (int i = 0; i < text.Length; i++)
            {
                char c = text[i];
                switch (c)
                {
                    case '\\':
                        builder.Append("\\\\");
                        break;
                    case '"':
                        builder.Append("\\\"");
                        break;
                    case '\n':
                        builder.Append("\\n");
                        break;
                    case '\r':
                        builder.Append("\\r");
                        break;
                    case '\t':
                        builder.Append("\\t");
                        break;
                    default:
                        if (c < 0x20 || c > 0x7E)
                        {
                            builder.Append("\\u").Append(((int)c).ToString("x4", CultureInfo.InvariantCulture));
                        }
                        else
                        {
                            builder.Append(c);
                        }

                        break;
                }
            }

            return builder.ToString();
        }

        /// <summary>One registration group with its entries sorted into canonical key order.</summary>
        internal sealed class GeneratedTable
        {
            private GeneratedTable(CatalogRegistrationGroup group, GeneratedEntry[] entries)
            {
                Group = group;
                Entries = entries;
            }

            internal CatalogRegistrationGroup Group { get; }

            internal GeneratedEntry[] Entries { get; }

            internal static GeneratedTable Create(CatalogRegistrationGroup group)
            {
                GeneratedEntry[] entries = new GeneratedEntry[group.Entries.Count];
                for (int i = 0; i < entries.Length; i++)
                {
                    entries[i] = new GeneratedEntry(group.Entries[i], StableNameKeyDerivation.Derive(group.Entries[i].StableName));
                }

                Array.Sort(entries, CompareEntries);
                return new GeneratedTable(group, entries);
            }

            private static int CompareEntries(GeneratedEntry left, GeneratedEntry right)
            {
                int byId = left.Key.CompareTo(right.Key);
                return byId != 0 ? byId : left.Entry.KeyVersion.CompareTo(right.Entry.KeyVersion);
            }
        }

        /// <summary>One registration entry with its derived key.</summary>
        internal sealed class GeneratedEntry
        {
            internal GeneratedEntry(CatalogRegistrationEntry entry, Id128 key)
            {
                Entry = entry;
                Key = key;
            }

            internal CatalogRegistrationEntry Entry { get; }

            internal Id128 Key { get; }
        }

        /// <summary>One schema declaration with its parsed identities and serializer key.</summary>
        internal sealed class GeneratedSchema
        {
            private GeneratedSchema(CatalogSchemaDeclaration declaration, Id128 schemaId, Id128 ownerPackageId, Id128 serializerKey)
            {
                Declaration = declaration;
                SchemaId = schemaId;
                OwnerPackageId = ownerPackageId;
                SerializerKey = serializerKey;
            }

            internal CatalogSchemaDeclaration Declaration { get; }

            internal Id128 SchemaId { get; }

            internal Id128 OwnerPackageId { get; }

            internal Id128 SerializerKey { get; }

            internal static GeneratedSchema Create(CatalogSchemaDeclaration declaration) =>
                new GeneratedSchema(
                    declaration,
                    ParseIdentity(declaration.SchemaIdHex),
                    ParseIdentity(declaration.OwnerPackageIdHex),
                    StableNameKeyDerivation.Derive(declaration.StableName));
        }
    }
}
