#!/usr/bin/env python3
"""Check the operator documentation against the repository (interpreter-level; nothing is executed).

`docs/operator/` is deliberately outside `docs/game-core/`, so the game-core documentation validator does
not read it. That is the right split — the operator guide is an implementation contract, not protocol
semantics — but it means nothing else checks it, and an operator page is exactly the kind of document that
rots silently: a renamed flag, a moved path, or a page nobody links.

This tool closes that gap by checking the operator pages against their sources:

  1. every relative link resolves, and every `#anchor` fragment exists in its target;
  2. every `-probe*` command-line flag named in `docs/operator/headless.md` is a real mode in
     `ProbeArguments.cs`, and every mode in that file is documented — the drift direction that matters most,
     because an operator running an undocumented flag gets no help and a removed flag documented as live is
     worse;
  3. every page in `docs/operator/` is reachable from its index, so a new page cannot be orphaned;
  4. the generated failure-code table exists and still carries its "generated, do not edit" banner, so it is
     not mistaken for a hand-maintained document.

Usage:
    python3 tools/check_operator_docs.py [--json <path>] [--self-test]

Exit codes: 0 every invariant holds; 1 at least one problem; 2 a missing prerequisite.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
import unicodedata
from pathlib import Path
from urllib.parse import unquote, urlsplit


ROOT = Path(__file__).resolve().parent.parent
OPERATOR_DIR = ROOT / "docs/operator"
INDEX = OPERATOR_DIR / "README.md"
HEADLESS = OPERATOR_DIR / "headless.md"
FAILURE_CODES = OPERATOR_DIR / "failure-codes.md"
PROBE_ARGUMENTS = (ROOT / "unity/GameCore.Validation/Assets/GameCore.Validation/Runtime"
                   / "ProbeArguments.cs")
ROOT_README = ROOT / "README.md"

GENERATED_BANNER = "Generated by `tools/emit_failure_codes.py`"
# Mode flags contain digits (`-probeW1Gate`, `-probeGc018`), so the character class must include them: a
# letters-only class silently skips every digit-bearing mode and reports a smaller, self-consistent set.
FLAG = re.compile(r"`(-probe[A-Za-z0-9]+)`")


def relative(path: Path, root: Path) -> str:
    """A display path, tolerating a symlinked root (/var vs /private/var on macOS)."""
    try:
        return str(path.relative_to(root))
    except ValueError:
        return str(path)


def slug(text: str) -> str:
    """GitHub-style heading anchor, matching the game-core validator's rule."""
    text = re.sub(r"\[([^\]]*)\]\([^)]*\)", r"\1", text)
    text = unicodedata.normalize("NFKD", text)
    text = re.sub(r"[^\w\s-]", "", text.lower())
    return text.strip().replace(" ", "-")


def without_code(text: str) -> str:
    return re.sub(r"```.*?```", lambda m: "\n" * m.group(0).count("\n"), text, flags=re.S)


def anchors_of(path: Path):
    found = set()
    for line in path.read_text(encoding="utf-8").splitlines():
        heading = re.match(r"^(#{1,6})\s+(.*?)\s*$", line)
        if heading:
            found.add(slug(heading.group(2)))
        for explicit in re.finditer(r"<[a-z][\w-]*\s[^>]*?\b(?:id|name)\s*=\s*['\"]([^'\"]+)['\"]",
                                   line, re.IGNORECASE):
            found.add(explicit.group(1))
    return found


def links_in(path: Path):
    for match in re.finditer(r"\[([^\]]*)\]\(([^)]+)\)", without_code(path.read_text(encoding="utf-8"))):
        yield match.group(2)


def probe_modes(probe_arguments: Path):
    """The literal mode flags ProbeArguments.cs declares."""
    text = probe_arguments.read_text(encoding="utf-8")
    return sorted(set(re.findall(r'ArgumentName\s*=\s*"(-probe[A-Za-z0-9]+)"', text)))


def documented_flags(headless: Path):
    """The `-probe*` flags the operator guide names."""
    return sorted(set(FLAG.findall(headless.read_text(encoding="utf-8"))))


def run_checks(root: Path):
    """Every invariant. Returns (problems, report)."""
    operator_dir = root / "docs/operator"
    index = operator_dir / "README.md"
    headless = operator_dir / "headless.md"
    failure_codes = operator_dir / "failure-codes.md"
    probe_arguments = (root / "unity/GameCore.Validation/Assets/GameCore.Validation/Runtime"
                       / "ProbeArguments.cs")
    problems = []

    if not operator_dir.is_dir():
        return [f"{relative(operator_dir, root)} does not exist"], {}

    pages = sorted(operator_dir.glob("*.md"))
    documents = pages + [p for p in (root / "README.md",) if p.exists()]


    # 1. links and anchors.
    checked_links = 0
    for document in documents:
        for destination in links_in(document):
            url = urlsplit(destination)
            if url.scheme or url.netloc or destination.startswith("//"):
                continue
            target = (document.parent / unquote(url.path)).resolve() if url.path else document.resolve()
            if not target.exists():
                problems.append(
                    f"{relative(document, root)}: link target does not exist: {destination}")
                continue
            checked_links += 1
            if url.fragment and target.suffix == ".md":
                if url.fragment not in anchors_of(target):
                    problems.append(
                        f"{relative(document, root)}: anchor #{url.fragment} not found in "
                        f"{relative(target, root)}")
    # 2. the documented command-line surface must equal the parsed one.
    modes = set(probe_modes(probe_arguments))
    documented = set(documented_flags(headless))
    for flag in sorted(modes - documented):
        problems.append(f"docs/operator/headless.md does not document the mode {flag}")
    for flag in sorted(documented - modes):
        problems.append(
            f"docs/operator/headless.md documents {flag}, which ProbeArguments.cs does not parse")

    # 3. no orphan page.
    index_text = index.read_text(encoding="utf-8") if index.exists() else ""
    for page in pages:
        if page == index:
            continue
        if page.name not in index_text:
            problems.append(f"docs/operator/{page.name} is not linked from docs/operator/README.md")

    # 4. the generated table stays recognisable as generated.
    if not failure_codes.exists():
        problems.append("docs/operator/failure-codes.md does not exist; run tools/emit_failure_codes.py")
    elif GENERATED_BANNER not in failure_codes.read_text(encoding="utf-8"):
        problems.append(
            "docs/operator/failure-codes.md has lost its generated banner; it must not look hand-maintained")

    return problems, {
        "pages": [relative(p, root) for p in pages],
        "links_checked": checked_links,
        "probe_modes_declared": len(modes),
        "probe_flags_documented": len(documented),
    }


def self_test():
    """Falsify each rule against a synthetic docs/operator tree."""
    import tempfile
    failures = 0

    def check(label, condition, detail=""):
        nonlocal failures
        if condition:
            print(f"   ok   {label}")
        else:
            failures += 1
            print(f"   FAIL {label} {detail}")

    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp).resolve()
        operator = root / "docs/operator"
        runtime = root / "unity/GameCore.Validation/Assets/GameCore.Validation/Runtime"
        operator.mkdir(parents=True)
        runtime.mkdir(parents=True)
        (runtime / "ProbeArguments.cs").write_text(
            'private const string AlphaArgumentName = "-probeAlpha";\n'
            'private const string BetaArgumentName = "-probeBeta";\n', encoding="utf-8")

        def write_index(extra):
            # The index links every page a clean tree is expected to have, so a fixture isolates one rule.
            (operator / "README.md").write_text(
                "# Index\n\n[headless](headless.md)\n[failure codes](failure-codes.md)\n" + extra,
                encoding="utf-8")

        def write_headless(flags):
            body = "# Headless\n\n## A section\n\n" + "\n".join(f"| `{f}` | x |" for f in flags) + "\n"
            (operator / "headless.md").write_text(body, encoding="utf-8")

        # A clean tree: both modes documented, page linked, banner present.
        write_index("")
        write_headless(["-probeAlpha", "-probeBeta"])
        (operator / "failure-codes.md").write_text(GENERATED_BANNER + "\n", encoding="utf-8")
        problems, _ = run_checks(root)
        check("a consistent tree has no problem", problems == [], str(problems))

        write_headless(["-probeAlpha"])
        problems, _ = run_checks(root)
        check("an undocumented mode is reported",
              any("does not document the mode -probeBeta" in p for p in problems), str(problems))

        write_headless(["-probeAlpha", "-probeBeta", "-probeGamma"])
        problems, _ = run_checks(root)
        check("a documented-but-unparsed flag is reported",
              any("does not parse" in p and "-probeGamma" in p for p in problems), str(problems))

        write_headless(["-probeAlpha", "-probeBeta"])
        (operator / "orphan.md").write_text("# Orphan\n", encoding="utf-8")
        problems, _ = run_checks(root)
        check("an unlinked page is reported",
              any("orphan.md is not linked" in p for p in problems), str(problems))
        (operator / "orphan.md").unlink()

        write_index("[broken](does-not-exist.md)\n")
        problems, _ = run_checks(root)
        check("a broken link is reported",
              any("link target does not exist" in p for p in problems), str(problems))

        write_index("[deep](headless.md#no-such-anchor)\n")
        problems, _ = run_checks(root)
        check("a missing anchor is reported",
              any("anchor #no-such-anchor" in p for p in problems), str(problems))

        write_index("[good anchor](headless.md#a-section)\n")
        problems, _ = run_checks(root)
        check("a real anchor is accepted", problems == [], str(problems))

        (operator / "failure-codes.md").write_text("# hand written\n", encoding="utf-8")
        problems, _ = run_checks(root)
        check("a de-generated failure table is reported",
              any("lost its generated banner" in p for p in problems), str(problems))

    if failures:
        print(f"check_operator_docs.py --self-test FAILED ({failures} case(s))")
        return 1
    print("check_operator_docs.py --self-test passed (8 cases).")
    return 0


def main(argv):
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--json", metavar="PATH", help="write the report here as well")
    parser.add_argument("--self-test", action="store_true",
                        help="falsify this tool's own rules on a synthetic tree and exit")
    parser.add_argument("--root", default=str(ROOT), help="repository root (default: this file's parent)")
    args = parser.parse_args(argv[1:])

    if args.self_test:
        return self_test()

    root = Path(args.root).resolve()
    problems, report = run_checks(root)

    if args.json:
        Path(args.json).parent.mkdir(parents=True, exist_ok=True)
        Path(args.json).write_text(json.dumps({"report": report, "problems": problems}, indent=2) + "\n",
                                   encoding="utf-8")

    if problems:
        print(f"check_operator_docs.py FAILED ({len(problems)} problem(s)):", file=sys.stderr)
        for problem in problems:
            print(f"  - {problem}", file=sys.stderr)
        return 1

    print(f"operator documentation agrees with the repository: {len(report['pages'])} page(s), "
          f"{report['links_checked']} local link(s) resolved, "
          f"{report['probe_modes_declared']} probe mode(s) documented and declared.")
    print("No Unity, no .NET and no player run was required by this check.")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
