#!/usr/bin/env python3
"""Emit the GameCore Studio JSON Schemas from the C# model shapes (P0.3, docs/studio/03-authoring-contracts.md).

The schemas are generated by the reflective emitter in dotnet/src/GameCore.Studio.Model.Schema (draft 2020-12,
sorted keys, '\\n' newlines) from the Unity-free GameCore.Studio.Model types, and committed under
docs/studio/schemas/:

    authoring-ref, selection-snapshot, semantic-index, tool-catalog, change-set, diagnostic (.schema.json)

Usage:
    python3 tools/studio/emit_studio_schemas.py            # regenerate docs/studio/schemas in place
    python3 tools/studio/emit_studio_schemas.py --check    # exit 1 if regeneration would change any file

Needs a .NET 8 SDK: $DOTNET, else ~/.dotnet/dotnet, else `dotnet` on PATH (the Mac checkout has none; run it on the
Linux build host). Exit codes: 0 ok / up to date; 1 schemas differ (--check) or the emitter failed; 2 no dotnet.
Standard library only.
"""
from __future__ import annotations

import argparse
import filecmp
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
PROJECT = ROOT / "dotnet/src/GameCore.Studio.Model.Schema/GameCore.Studio.Model.Schema.csproj"
SCHEMAS = ROOT / "docs/studio/schemas"
EXPECTED = [
    "authoring-ref.schema.json",
    "selection-snapshot.schema.json",
    "semantic-index.schema.json",
    "tool-catalog.schema.json",
    "change-set.schema.json",
    "diagnostic.schema.json",
]


def find_dotnet() -> str | None:
    candidates = [os.environ.get("DOTNET"), str(Path.home() / ".dotnet/dotnet"), shutil.which("dotnet")]
    for candidate in candidates:
        if candidate and Path(candidate).is_file() and os.access(candidate, os.X_OK):
            return candidate
    return None


def emit(dotnet: str, out_dir: Path) -> None:
    command = [dotnet, "run", "--project", str(PROJECT), "-c", "Release", "--", "--out", str(out_dir)]
    environment = dict(os.environ, DOTNET_CLI_TELEMETRY_OPTOUT="1", DOTNET_NOLOGO="1")
    result = subprocess.run(command, cwd=ROOT, env=environment, capture_output=True, text=True)
    if result.returncode != 0:
        sys.stderr.write(result.stdout)
        sys.stderr.write(result.stderr)
        raise SystemExit(f"emit_studio_schemas.py: the emitter failed (exit {result.returncode})")
    produced = sorted(path.name for path in out_dir.glob("*.schema.json"))
    if produced != sorted(EXPECTED):
        raise SystemExit(f"emit_studio_schemas.py: unexpected emitter output {produced}")


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="fail if regeneration differs from the committed files")
    args = parser.parse_args(argv[1:])

    dotnet = find_dotnet()
    if dotnet is None:
        print("emit_studio_schemas.py: no .NET SDK found ($DOTNET, ~/.dotnet/dotnet, PATH); run on the build host",
              file=sys.stderr)
        return 2

    if not args.check:
        SCHEMAS.mkdir(parents=True, exist_ok=True)
        emit(dotnet, SCHEMAS)
        print(f"wrote {len(EXPECTED)} schema(s) to {SCHEMAS.relative_to(ROOT)}")
        return 0

    with tempfile.TemporaryDirectory(prefix="studio-schemas-") as temporary:
        fresh = Path(temporary)
        emit(dotnet, fresh)
        problems = []
        for name in EXPECTED:
            committed = SCHEMAS / name
            if not committed.exists():
                problems.append(f"{name}: missing from {SCHEMAS.relative_to(ROOT)}")
            elif not filecmp.cmp(committed, fresh / name, shallow=False):
                problems.append(f"{name}: differs from a fresh emission")
        extra = sorted(path.name for path in SCHEMAS.glob("*.schema.json") if path.name not in EXPECTED)
        problems.extend(f"{name}: not produced by the emitter" for name in extra)
        if problems:
            print("emit_studio_schemas.py --check FAILED:", file=sys.stderr)
            for problem in problems:
                print(f"  - {problem}", file=sys.stderr)
            print("regenerate with: python3 tools/studio/emit_studio_schemas.py", file=sys.stderr)
            return 1
    print(f"studio schemas are up to date ({len(EXPECTED)} file(s))")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
