// Hollowmere - authors the P1.5 UI and audio content through the ui.* and audio.* tools (idempotent).
//
//   Assets/Hollowmere/Audio/Generated/*.wav + HollowmereAudio.manifest.json   procedural placeholder audio
//   Assets/Hollowmere/Audio/Definitions/*.asset                                bank, music states, ambiences, audio set
//   Assets/Hollowmere/Audio/HollowmereMixer.mixer                              hand-written mixer (Master + 4 groups)
//   Assets/Hollowmere/UI/Theme/*                                               USS, TSS, PanelSettings, ThemeDefinition
//   Assets/Hollowmere/UI/Screens/*.uxml + Assets/Hollowmere/UI/Definitions/*   documents with their binding maps, flow
//   Assets/Hollowmere/UI/Resources/Hollowmere/UiAudio.asset                    the content asset GameBoot loads
// Existing assets keep their GUIDs and authoring ids; bindings are re-applied (no-ops when unchanged) and the audio is
// regenerated byte-identically. No world definition is touched, so the world bake is unaffected.
#nullable enable
using System;
using System.Collections.Generic;
using System.IO;
using GameCore.Gameplay.Audio;
using GameCore.Gameplay.Audio.Editor;
using GameCore.Gameplay.Contracts;
using GameCore.Gameplay.Save;
using GameCore.Gameplay.Ui;
using GameCore.Gameplay.Ui.Editor;
using GameCore.Gameplay.World;
using GameCore.Rules.Gameplay.Ui;
using GameCore.Unity.App;
using Hollowmere.UiAudio;
using UnityEditor;
using UnityEngine;
using UnityEngine.Audio;
using UnityEngine.UIElements;

namespace Hollowmere.UiAudioAuthoring
{
    /// <summary>What one authoring pass did.</summary>
    public sealed class UiAudioAuthoringReport
    {
        public int Clips { get; internal set; }

        public int Documents { get; internal set; }

        public int Bindings { get; internal set; }

        public List<GameplayDiagnostic> Diagnostics { get; } = new List<GameplayDiagnostic>();

        public bool Ok => Diagnostics.Count == 0;

        public override string ToString()
        {
            string text = Clips + " clips, " + Documents + " documents, " + Bindings + " bindings, " + Diagnostics.Count + " diagnostics";
            for (int i = 0; i < Diagnostics.Count; i++)
            {
                text += "\n  " + Diagnostics[i].Code + " " + Diagnostics[i].SubjectId + ": " + Diagnostics[i].Message;
            }

            return text;
        }
    }

    /// <summary>Creates (when missing) and refreshes the Hollowmere UI and audio content.</summary>
    public static class HollowmereUiAudioAuthoring
    {
        public const string UiRoot = "Assets/Hollowmere/UI";
        public const string AudioRoot = "Assets/Hollowmere/Audio";
        public const string GeneratedFolder = AudioRoot + "/Generated";
        public const string AudioManifestName = "HollowmereAudio.manifest.json";
        public const string MixerPath = AudioRoot + "/HollowmereMixer.mixer";
        public const string BankPath = AudioRoot + "/Definitions/HollowmereAudioBank.asset";
        public const string AudioSetPath = AudioRoot + "/Definitions/HollowmereAudio.asset";
        public const string UssPath = UiRoot + "/Theme/Hollowmere.uss";
        public const string TssPath = UiRoot + "/Theme/HollowmereTheme.tss";
        public const string PanelSettingsPath = UiRoot + "/Theme/HollowmerePanelSettings.asset";
        public const string ThemePath = UiRoot + "/Theme/HollowmereTheme.asset";
        public const string FlowPath = UiRoot + "/Definitions/HollowmereScreenFlow.asset";
        public const string ContentPath = UiRoot + "/Resources/Hollowmere/UiAudio.asset";
        public const string RegionsFolder = "Assets/Hollowmere/World/Regions";

        public const string MusicExplore = "music.explore";
        public const string MusicTense = "music.tense";
        public const string MusicEnding = "music.ending";
        public const string Bell = "stinger.bell";

        private sealed class ScreenPlan
        {
            public ScreenPlan(UiScreen screen, string uxml, string asset, int layer)
            {
                Screen = screen;
                Uxml = UiRoot + "/Screens/" + uxml;
                Asset = UiRoot + "/Definitions/" + asset;
                Layer = layer;
            }

            public UiScreen Screen { get; }

            public string Uxml { get; }

            public string Asset { get; }

            public int Layer { get; }
        }

        [MenuItem("Hollowmere/Author UI and Audio")]
        public static void AuthorMenu()
        {
            UiAudioAuthoringReport report = Author();
            if (report.Ok)
            {
                Debug.Log("[Hollowmere] UI and audio: " + report);
            }
            else
            {
                Debug.LogError("[Hollowmere] UI and audio: " + report);
            }
        }

        /// <summary>The procedural clip specs (also the manifest's parameter record).</summary>
        public static List<ProceduralClipSpec> AudioSpecs()
        {
            return new List<ProceduralClipSpec>
            {
                new ProceduralClipSpec("ambience.village", "ambience_village.wav", ProceduralRecipe.Ambience, 10f, 11)
                {
                    noise = 0.5f, noiseCutoffHz = 900f, swellCycles = 2f, swellDepth = 0.4f, tones = new[] { 110f, 165f }, toneGain = 0.12f,
                    pulseHz = 2400f, pulsesPerLoop = 6, pulseGain = 0.15f, pulseDecay = 30f, peak = 0.45f,
                },
                new ProceduralClipSpec("ambience.marsh", "ambience_marsh.wav", ProceduralRecipe.Ambience, 10f, 23)
                {
                    noise = 0.6f, noiseCutoffHz = 400f, swellCycles = 3f, swellDepth = 0.5f, tones = new[] { 55f, 82.5f }, toneGain = 0.2f,
                    pulseHz = 180f, pulsesPerLoop = 9, pulseGain = 0.35f, pulseDecay = 18f, peak = 0.5f,
                },
                new ProceduralClipSpec("ambience.belfry", "ambience_belfry.wav", ProceduralRecipe.Ambience, 10f, 37)
                {
                    noise = 0.7f, noiseCutoffHz = 1800f, swellCycles = 1f, swellDepth = 0.6f, tones = new[] { 73.4f, 77f }, toneGain = 0.25f,
                    peak = 0.45f,
                },
                new ProceduralClipSpec(MusicExplore, "music_explore.wav", ProceduralRecipe.Pad, 12f, 41)
                {
                    tones = new[] { 220f, 277.2f, 329.6f }, swellCycles = 2f, swellDepth = 0.3f, noise = 0.02f, noiseCutoffHz = 2000f, peak = 0.35f,
                },
                new ProceduralClipSpec(MusicTense, "music_tense.wav", ProceduralRecipe.Pad, 12f, 43)
                {
                    tones = new[] { 110f, 130.8f, 155.6f }, swellCycles = 4f, swellDepth = 0.2f, pulsesPerLoop = 16, pulseGain = 0.6f, pulseDecay = 6f,
                    peak = 0.35f,
                },
                new ProceduralClipSpec(MusicEnding, "music_ending.wav", ProceduralRecipe.Pad, 12f, 47)
                {
                    tones = new[] { 196f, 246.9f, 293.7f, 392f }, swellCycles = 1f, swellDepth = 0.4f, peak = 0.35f,
                },
                new ProceduralClipSpec(Bell, "stinger_bell.wav", ProceduralRecipe.Bell, 4f, 53) { frequency = 196f, decay = 1.2f, peak = 0.7f },
                new ProceduralClipSpec("sfx.footstep", "sfx_footstep.wav", ProceduralRecipe.Footstep, 0.18f, 5)
                {
                    noise = 1f, noiseCutoffHz = 900f, frequency = 80f, decay = 30f, peak = 0.5f,
                },
                new ProceduralClipSpec("sfx.footstep.stone", "sfx_footstep_stone.wav", ProceduralRecipe.Footstep, 0.14f, 7)
                {
                    noise = 1f, noiseCutoffHz = 2600f, frequency = 120f, decay = 40f, peak = 0.5f,
                },
                new ProceduralClipSpec("sfx.ui.click", "sfx_ui_click.wav", ProceduralRecipe.Click, 0.06f, 3)
                {
                    frequency = 1400f, decay = 70f, noise = 0.4f, peak = 0.4f,
                },
                new ProceduralClipSpec("sfx.ui.confirm", "sfx_ui_confirm.wav", ProceduralRecipe.Click, 0.12f, 9)
                {
                    frequency = 880f, decay = 30f, noise = 0.2f, peak = 0.4f,
                },
            };
        }

        /// <summary>Creates whatever is missing and refreshes the rest; returns the report with validator diagnostics.</summary>
        public static UiAudioAuthoringReport Author()
        {
            var report = new UiAudioAuthoringReport();
            EnsureFolder(AudioRoot + "/Definitions");
            EnsureFolder(GeneratedFolder);
            EnsureFolder(UiRoot + "/Definitions");
            EnsureFolder(UiRoot + "/Resources/Hollowmere");
            AudioSetDefinition set = AuthorAudio(report);
            ScreenFlowDefinition flow = AuthorUi(report);
            HollowmereUiAudioContent content = LoadOrCreate<HollowmereUiAudioContent>(ContentPath, null);
            content.Configure(flow, set);
            EditorUtility.SetDirty(content);
            AssetDatabase.SaveAssets();
            report.Diagnostics.AddRange(AudioValidator.Validate(set));
            report.Diagnostics.AddRange(UiValidator.Validate(flow));
            return report;
        }

        // ------------------------------------------------------------------ audio

        private static AudioSetDefinition AuthorAudio(UiAudioAuthoringReport report)
        {
            List<ProceduralClipSpec> specs = AudioSpecs();
            ProceduralAudioGenerator.Generate(GeneratedFolder, AudioManifestName, specs);
            AssetDatabase.Refresh(ImportAssetOptions.ForceSynchronousImport);
            AudioMixer? mixer = AssetDatabase.LoadAssetAtPath<AudioMixer>(MixerPath);
            AudioBankDefinition bank = LoadOrCreate<AudioBankDefinition>(BankPath, b => b.EnsureAuthoringId());
            bank.SetMixer(mixer);
            for (int i = 0; i < specs.Count; i++)
            {
                ProceduralClipSpec spec = specs[i];
                AudioClip? clip = AssetDatabase.LoadAssetAtPath<AudioClip>(GeneratedFolder + "/" + spec.file);
                if (clip == null)
                {
                    report.Diagnostics.Add(new GameplayDiagnostic(PresentationDiagnosticCodes.AudioMissingClip, spec.id, spec.file + " did not import"));
                    continue;
                }

                AudioGroup group = spec.id.StartsWith("ambience.", StringComparison.Ordinal) ? AudioGroup.Ambience
                    : spec.id.StartsWith("music.", StringComparison.Ordinal) || spec.id.StartsWith("stinger.", StringComparison.Ordinal) ? AudioGroup.Music
                    : spec.id.StartsWith("sfx.ui.", StringComparison.Ordinal) ? AudioGroup.Ui : AudioGroup.Sfx;
                bool spatial = group == AudioGroup.Sfx;
                AudioTools.AssignClip(bank, spec.id, clip, group, spatial ? 0.9f : 1f, spec.loop, spatial);
                report.Clips++;
            }

            EditorUtility.SetDirty(bank);
            AudioSetDefinition set = LoadOrCreate<AudioSetDefinition>(AudioSetPath, s => s.EnsureAuthoringId());
            if (set.Bank != bank)
            {
                set.Configure(bank, set.MusicStates, set.StartMusicState, set.Ambiences);
            }

            AudioTools.SetMusicState(set, MusicExplore, MusicExplore, 2500, string.Empty, true, AudioRoot + "/Definitions/MusicState_Explore.asset");
            AudioTools.SetMusicState(set, MusicTense, MusicTense, 1200, Bell, false, AudioRoot + "/Definitions/MusicState_Tense.asset");
            AudioTools.SetMusicState(set, MusicEnding, MusicEnding, 4000, Bell, false, AudioRoot + "/Definitions/MusicState_Ending.asset");
            Ambience(set, "ThornwickVillage", "ambience.village");
            Ambience(set, "BlackmereMarsh", "ambience.marsh");
            Ambience(set, "DrownedBelfry", "ambience.belfry");
            EditorUtility.SetDirty(set);
            return set;
        }

        private static void Ambience(AudioSetDefinition set, string regionAsset, string clipId)
        {
            RegionDefinition? region = AssetDatabase.LoadAssetAtPath<RegionDefinition>(RegionsFolder + "/" + regionAsset + ".asset");
            if (region == null)
            {
                throw new InvalidOperationException("region " + regionAsset + " is missing; author the P1.1 world first");
            }

            AudioTools.SetAmbience(set, region, clipId, 0.8f, 2500, AudioRoot + "/Definitions/Ambience_" + regionAsset + ".asset");
        }

        // ------------------------------------------------------------------ UI

        private static ScreenFlowDefinition AuthorUi(UiAudioAuthoringReport report)
        {
            AssetDatabase.ImportAsset(UssPath, ImportAssetOptions.ForceSynchronousImport);
            AssetDatabase.ImportAsset(TssPath, ImportAssetOptions.ForceSynchronousImport);
            StyleSheet? uss = AssetDatabase.LoadAssetAtPath<StyleSheet>(UssPath);
            ThemeStyleSheet? tss = AssetDatabase.LoadAssetAtPath<ThemeStyleSheet>(TssPath);
            PanelSettings panel = LoadOrCreate<PanelSettings>(PanelSettingsPath, p =>
            {
                p.scaleMode = PanelScaleMode.ScaleWithScreenSize;
                p.referenceResolution = new Vector2Int(1920, 1080);
                p.screenMatchMode = PanelScreenMatchMode.MatchWidthOrHeight;
                p.match = 0.5f;
            });
            if (tss != null && panel.themeStyleSheet != tss)
            {
                panel.themeStyleSheet = tss;
                EditorUtility.SetDirty(panel);
            }

            ThemeDefinition theme = LoadOrCreate<ThemeDefinition>(ThemePath, t => t.EnsureAuthoringId());
            ScreenFlowDefinition flow = LoadOrCreate<ScreenFlowDefinition>(FlowPath, f =>
            {
                f.EnsureAuthoringId();
                f.Configure("Hollowmere", UiScreen.Menu, null, 3000);
            });
            UiTools.SetTheme(flow, theme, panel, tss, uss != null ? new[] { uss } : Array.Empty<StyleSheet>());
            flow.SetMessages(Messages());
            EditorUtility.SetDirty(flow);

            var plans = new[]
            {
                new ScreenPlan(UiScreen.Hud, "Hud.uxml", "Doc_Hud.asset", 0),
                new ScreenPlan(UiScreen.Hud, "Dialogue.uxml", "Doc_Dialogue.asset", 20),
                new ScreenPlan(UiScreen.Menu, "MainMenu.uxml", "Doc_MainMenu.asset", 10),
                new ScreenPlan(UiScreen.Pause, "Pause.uxml", "Doc_Pause.asset", 10),
                new ScreenPlan(UiScreen.Settings, "Settings.uxml", "Doc_Settings.asset", 10),
                new ScreenPlan(UiScreen.Save, "SaveLoad.uxml", "Doc_Save.asset", 10),
                new ScreenPlan(UiScreen.Load, "SaveLoad.uxml", "Doc_Load.asset", 10),
                new ScreenPlan(UiScreen.Journal, "Journal.uxml", "Doc_Journal.asset", 10),
                new ScreenPlan(UiScreen.Inventory, "Inventory.uxml", "Doc_Inventory.asset", 10),
                new ScreenPlan(UiScreen.Ending, "Ending.uxml", "Doc_Ending.asset", 10),
            };
            for (int i = 0; i < plans.Length; i++)
            {
                UiDocumentDefinition document = Document(flow, plans[i]);
                report.Bindings += BindScreen(document, plans[i].Screen, plans[i].Uxml);
                report.Documents++;
            }

            return flow;
        }

        private static UiDocumentDefinition Document(ScreenFlowDefinition flow, ScreenPlan plan)
        {
            AssetDatabase.ImportAsset(plan.Uxml, ImportAssetOptions.ForceSynchronousImport);
            UiDocumentDefinition? document = AssetDatabase.LoadAssetAtPath<UiDocumentDefinition>(plan.Asset);
            if (document == null)
            {
                return UiTools.AddScreen(flow, plan.Screen, plan.Uxml, plan.Layer, plan.Asset);
            }

            document.EnsureAuthoringId();
            document.Configure(plan.Screen, plan.Layer, AssetDatabase.LoadAssetAtPath<VisualTreeAsset>(plan.Uxml));
            EditorUtility.SetDirty(document);
            if (flow.AddDocument(document))
            {
                EditorUtility.SetDirty(flow);
            }

            return document;
        }

        /// <summary>The binding map of one screen, applied through ui.bind / ui.setCommand.</summary>
        private static int BindScreen(UiDocumentDefinition d, UiScreen screen, string uxml)
        {
            int n = 0;
            if (uxml.EndsWith("Hud.uxml", StringComparison.Ordinal))
            {
                n += B(d, "objective-line", "vm:hud.ObjectiveText");
                n += B(d, "objective-line", "vm:hud.ObjectiveVisible", "visible");
                n += B(d, "stamina-bar", "vm:hud.Stamina", "value");
                n += B(d, "stamina-bar", "vm:hud.StaminaVisible", "visible");
                n += B(d, "region-banner", "vm:hud.RegionBannerVisible", "visible");
                n += B(d, "region-name", "event:region-entered");
                n += B(d, "message", "vm:screen.MessageText");
                n += B(d, "message", "vm:screen.MessageVisible", "visible");
                n += B(d, "prompt", "vm:prompt.Visible", "visible");
                n += B(d, "prompt-text", "vm:prompt.Text");
                n += B(d, "prompt-text", "vm:prompt.Enabled", "enabled");
                return n;
            }

            if (uxml.EndsWith("Dialogue.uxml", StringComparison.Ordinal))
            {
                n += B(d, "dialogue-panel", "vm:dialogue.Visible", "visible");
                n += B(d, "dialogue-speaker", "vm:dialogue.Speaker");
                n += B(d, "dialogue-text", "vm:dialogue.Text");
                n += B(d, "dialogue-choices", "vm:dialogue.Choices", "items", "command:choose");
                n += B(d, "dialogue-choices", "vm:dialogue.Selected", "selected");
                n += B(d, "dialogue-choices", "vm:dialogue.HasChoices", "visible");
                n += C(d, "dialogue-continue", "advance");
                return n;
            }

            switch (screen)
            {
                case UiScreen.Menu:
                    n += B(d, "menu-title", "vm:menu.Title");
                    n += B(d, "menu-continue", "vm:menu.ContinueAvailable", "enabled");
                    n += B(d, "menu-message", "vm:screen.MessageText");
                    n += C(d, "menu-new", "newgame");
                    n += C(d, "menu-continue", "continue");
                    n += C(d, "menu-load", "open.load");
                    n += C(d, "menu-settings", "open.settings");
                    n += C(d, "menu-quit", "quit");
                    break;
                case UiScreen.Pause:
                    n += C(d, "pause-resume", "resume");
                    n += C(d, "pause-save", "open.save");
                    n += C(d, "pause-load", "open.load");
                    n += C(d, "pause-settings", "open.settings");
                    n += C(d, "pause-menu", "quitToMenu");
                    n += C(d, "pause-quit", "quit");
                    n += B(d, "pause-volume", "slot:audio.owner/audio.volumeMaster@audio", "text", "percent:1000");
                    break;
                case UiScreen.Settings:
                    n += B(d, "settings-master", "vm:settings.MasterVolume", "value");
                    n += B(d, "settings-music", "vm:settings.MusicVolume", "value");
                    n += B(d, "settings-sfx", "vm:settings.SfxVolume", "value");
                    n += B(d, "settings-voice", "vm:settings.VoiceVolume", "value");
                    n += C(d, "settings-master", "volume.0", "changed");
                    n += C(d, "settings-music", "volume.1", "changed");
                    n += C(d, "settings-sfx", "volume.2", "changed");
                    n += C(d, "settings-voice", "volume.3", "changed");
                    n += B(d, "settings-master", "vm:settings.AudioAvailable", "enabled");
                    n += B(d, "settings-music", "vm:settings.AudioAvailable", "enabled");
                    n += B(d, "settings-sfx", "vm:settings.AudioAvailable", "enabled");
                    n += B(d, "settings-voice", "vm:settings.AudioAvailable", "enabled");
                    n += B(d, "settings-sensitivity", "vm:settings.Sensitivity", "value");
                    n += C(d, "settings-sensitivity", "sensitivity", "changed");
                    n += B(d, "settings-resolution", "vm:settings.Resolutions", "items");
                    n += B(d, "settings-resolution", "vm:settings.ResolutionIndex", "value");
                    n += C(d, "settings-resolution", "resolution", "changed");
                    n += B(d, "settings-fullscreen", "vm:settings.Fullscreen", "value");
                    n += C(d, "settings-fullscreen", "fullscreen", "changed");
                    n += C(d, "settings-back", "close");
                    break;
                case UiScreen.Save:
                case UiScreen.Load:
                    n += B(d, "saveload-title", "vm:saveload.Mode", "text", "{0} game");
                    n += B(d, "saveload-slots", "vm:saveload.SlotLabels", "items", "command:select");
                    n += B(d, "saveload-slots", "vm:saveload.Selected", "selected", "offset:-1");
                    n += B(d, "saveload-status", "vm:saveload.Status");
                    n += B(d, "saveload-code", "vm:saveload.RefusalCode");
                    n += B(d, "saveload-confirm", "vm:saveload.Available", "enabled");
                    n += B(d, "saveload-delete", "vm:saveload.Available", "enabled");
                    n += C(d, "saveload-confirm", "slot.selected");
                    n += C(d, "saveload-delete", "delete.selected");
                    n += C(d, "saveload-back", "close");
                    break;
                case UiScreen.Journal:
                    n += B(d, "journal-quests", "vm:journal.QuestLines", "items", "command:select");
                    n += B(d, "journal-quests", "vm:journal.Selected", "selected");
                    n += B(d, "journal-detail", "vm:journal.DetailLines", "items");
                    n += B(d, "journal-empty", "vm:journal.Empty", "visible");
                    n += C(d, "journal-inventory", "open.inventory");
                    n += C(d, "journal-close", "close");
                    break;
                case UiScreen.Inventory:
                    n += B(d, "inventory-grid", "vm:inventory.SlotLabels", "items", "command:item");
                    n += B(d, "inventory-grid", "vm:inventory.Selected", "selected");
                    n += B(d, "inventory-selected", "vm:inventory.SelectedName");
                    n += B(d, "inventory-currency", "vm:inventory.Currency", "text", "{0} coins");
                    n += B(d, "inventory-use", "vm:inventory.SelectedUsable", "enabled");
                    n += C(d, "inventory-use", "use");
                    n += C(d, "inventory-drop", "drop");
                    n += C(d, "inventory-journal", "open.journal");
                    n += C(d, "inventory-close", "close");
                    break;
                case UiScreen.Ending:
                    n += B(d, "ending-title", "vm:ending.Title");
                    n += B(d, "ending-body", "vm:ending.Body");
                    n += C(d, "ending-restart", "restart");
                    n += C(d, "ending-menu", "quitToMenu");
                    break;
            }

            return n;
        }

        private static int B(UiDocumentDefinition d, string element, string source, string property = "text", string format = "")
        {
            UiTools.Bind(d, element, source, property, format);
            return 1;
        }

        private static int C(UiDocumentDefinition d, string element, string command, string property = "clicked")
        {
            UiTools.SetCommand(d, element, command, property);
            return 1;
        }

        private static List<UiMessageEntry> Messages()
        {
            var messages = new List<UiMessageEntry>
            {
                new UiMessageEntry(UiMessageIds.Saved, "Game saved."),
                new UiMessageEntry(UiMessageIds.Loaded, "Game loaded."),
                new UiMessageEntry(UiMessageIds.Deleted, "Save deleted."),
                new UiMessageEntry(UiMessageIds.NoSave, "There is no saved game yet."),
                new UiMessageEntry(UiMessageIds.SaveUnavailable, "Saving is not available in this build (" + PresentationDiagnosticCodes.UiSaveUnavailable + ")."),
            };
            foreach (SaveRefusalCode code in (SaveRefusalCode[])Enum.GetValues(typeof(SaveRefusalCode)))
            {
                string id = SaveRefusal.IdOf(code);
                if (code != SaveRefusalCode.None && messages.FindIndex(m => m.Id == id) < 0)
                {
                    messages.Add(new UiMessageEntry(id, id + ": " + SaveRefusal.DefaultHint(code)));
                }
            }

            return messages;
        }

        // ------------------------------------------------------------------ helpers

        private static T LoadOrCreate<T>(string path, Action<T>? initialize) where T : ScriptableObject
        {
            T? existing = AssetDatabase.LoadAssetAtPath<T>(path);
            if (existing != null)
            {
                return existing;
            }

            T created = ScriptableObject.CreateInstance<T>();
            initialize?.Invoke(created);
            AssetDatabase.CreateAsset(created, path);
            return created;
        }

        private static void EnsureFolder(string path)
        {
            if (AssetDatabase.IsValidFolder(path))
            {
                return;
            }

            string parent = Path.GetDirectoryName(path)?.Replace('\\', '/') ?? "Assets";
            EnsureFolder(parent);
            AssetDatabase.CreateFolder(parent, Path.GetFileName(path));
        }
    }
}
