#nullable enable
using System;
using System.Collections.Generic;
using System.IO;
using GameCore.Validation.Probe;
using Unity.Burst;
using UnityEditor;
using UnityEditor.Build;
using UnityEditor.Build.Reporting;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.SceneManagement;

namespace GameCore.Validation.Editor
{
    /// <summary>
    /// Checked-in batchmode build entry point for the GC-001 qualification player
    /// (<c>docs/game-core/04-unity-integration.md</c> section 10). It sets the scripting backend, stripping
    /// level, API compatibility and target from the API so no hand-written <c>ProjectSettings</c> YAML is
    /// required, then builds the standalone probe player for the selected baseline target.
    ///
    /// Callable with
    /// <c>-batchmode -nographics -quit -projectPath unity/GameCore.Validation -executeMethod
    /// GameCore.Validation.Editor.BuildProbe.BuildLinuxIL2CPP -logFile artifacts/toolchain/build.log</c>.
    /// Any failure calls <see cref="EditorApplication.Exit"/> with a nonzero code.
    /// </summary>
    public static class BuildProbe
    {
        /// <summary>Build output directory, relative to the Unity project root.</summary>
        public const string OutputDirectory = "Builds/Linux64";

        /// <summary>Executable name of the built probe player.</summary>
        public const string ExecutableName = "GameCoreProbe.x86_64";

        /// <summary>Bootstrap scene generated by this script and added to the build.</summary>
        public const string ScenePath = "Assets/Scenes/GameCoreProbe.unity";

        /// <summary>Target player platform of the selected qualification profile.</summary>
        public const BuildTarget Target = BuildTarget.StandaloneLinux64;

        /// <summary>Target group of the selected qualification profile.</summary>
        public const BuildTargetGroup TargetGroup = BuildTargetGroup.Standalone;

        /// <summary>Editor revision this profile is pinned to.</summary>
        public const string ExpectedEditorVersion = "6000.0.75f1";

        /// <summary>Managed stripping level required for release qualification.</summary>
        public const ManagedStrippingLevel StrippingLevel = ManagedStrippingLevel.High;

        /// <summary>
        /// Batchmode entry point for the selected baseline target: StandaloneLinux64, IL2CPP, High stripping.
        /// </summary>
        public static void BuildLinuxIL2CPP()
        {
            try
            {
                Run();
                Exit(0);
            }
            catch (Exception exception)
            {
                Debug.LogError("[GC001] build failed: " + exception);
                Exit(1);
            }
        }

        private static void Run()
        {
            Debug.Log(
                "[GC001] build started; editorVersion=" + Application.unityVersion
                + "; expectedEditorVersion=" + ExpectedEditorVersion
                + "; target=" + Target
                + "; backend=IL2CPP"
                + "; stripping=" + StrippingLevel
                + "; apiCompatibility=.NET Standard 2.1"
                + "; burstCompilerAvailable=" + BurstCompiler.IsEnabled);

            if (!string.Equals(Application.unityVersion, ExpectedEditorVersion, StringComparison.Ordinal))
            {
                throw new InvalidOperationException(
                    "Editor version mismatch: the baseline pins Unity " + ExpectedEditorVersion
                    + " but this Editor reports " + Application.unityVersion
                    + ". Update the baseline deliberately instead of building on an unpinned Editor.");
            }

            if (!BuildPipeline.IsBuildTargetSupported(TargetGroup, Target))
            {
                throw new InvalidOperationException(
                    "build target " + Target + " is not installed in this Editor; install the Linux build "
                    + "support module (Linux IL2CPP) before running this build.");
            }

            NamedBuildTarget namedTarget = NamedBuildTarget.Standalone;

            // Backend and stripping first: both are re-read below so the build fails on any silent override.
            PlayerSettings.SetScriptingBackend(namedTarget, ScriptingImplementation.IL2CPP);
            PlayerSettings.SetManagedStrippingLevel(namedTarget, StrippingLevel);
            PlayerSettings.SetApiCompatibilityLevel(namedTarget, ApiCompatibilityLevel.NET_Standard);
            PlayerSettings.SetIl2CppCompilerConfiguration(namedTarget, Il2CppCompilerConfiguration.Release);
            PlayerSettings.productName = "GameCoreProbe";
            PlayerSettings.companyName = "GameCore";
            PlayerSettings.bundleVersion = "0.1.0";
            ScriptingImplementation backend = PlayerSettings.GetScriptingBackend(namedTarget);
            ManagedStrippingLevel stripping = PlayerSettings.GetManagedStrippingLevel(namedTarget);
            ApiCompatibilityLevel apiCompatibility = PlayerSettings.GetApiCompatibilityLevel(namedTarget);
            Debug.Log(
                "[GC001] player settings applied; scriptingBackend=" + backend
                + "; managedStrippingLevel=" + stripping
                + "; apiCompatibilityLevel=" + apiCompatibility);

            if (backend != ScriptingImplementation.IL2CPP)
            {
                throw new InvalidOperationException(
                    "scripting backend is " + backend + " after being set to IL2CPP.");
            }

            if (stripping != StrippingLevel)
            {
                throw new InvalidOperationException(
                    "managed stripping level is " + stripping + " after being set to " + StrippingLevel + ".");
            }

            if (apiCompatibility != ApiCompatibilityLevel.NET_Standard)
            {
                throw new InvalidOperationException(
                    "API compatibility level is " + apiCompatibility + " after being set to .NET Standard 2.1.");
            }

            // Burst AOT compilation for the standalone target is on by default; refuse to build if it is off,
            // because a player built with Burst silently disabled cannot pass TEST-001.
            if (!BurstCompiler.Options.EnableBurstCompilation)
            {
                throw new InvalidOperationException(
                    "Burst compilation is disabled in this Editor; TEST-001 requires Burst enabled, so this "
                    + "build would not prove anything.");
            }

            // Generate (or verify) the closed registration catalog before building, so a stale or missing
            // generated file cannot be blamed on the build.
            ProbeCatalogGenerator.GenerateCatalog();

            string projectRoot = ProjectRoot();
            EnsureBootstrapScene();

            string outputDirectory = Path.Combine(projectRoot, OutputDirectory);
            Directory.CreateDirectory(outputDirectory);
            string outputPath = Path.Combine(outputDirectory, ExecutableName);

            var scenes = new List<string> { ScenePath };
            var options = new BuildPlayerOptions
            {
                scenes = scenes.ToArray(),
                locationPathName = outputPath,
                target = Target,
                targetGroup = TargetGroup,
                options = BuildOptions.None,
            };

            Debug.Log("[GC001] building player; location=" + outputPath + "; scenes=" + string.Join(",", scenes));
            BuildReport report = BuildPipeline.BuildPlayer(options);
            BuildSummary summary = report.summary;

            Debug.Log(
                "[GC001] build finished; result=" + summary.result
                + "; totalSize=" + summary.totalSize
                + "; totalErrors=" + summary.totalErrors
                + "; totalWarnings=" + summary.totalWarnings
                + "; output=" + summary.outputPath
                + "; platform=" + summary.platform
                + "; buildStarted=" + summary.buildStartedAt.ToString("O")
                + "; buildEnded=" + summary.buildEndedAt.ToString("O"));

            if (summary.result != BuildResult.Succeeded)
            {
                throw new InvalidOperationException(
                    "player build did not succeed: result=" + summary.result
                    + "; errors=" + summary.totalErrors);
            }

            if (!File.Exists(outputPath))
            {
                throw new InvalidOperationException("the build reported success but " + outputPath + " does not exist.");
            }

            Debug.Log(
                "[GC001] probe player built; executable=" + outputPath
                + "; catalog=" + ProbeCatalogGenerator.RelativeOutputPath
                + "; catalog hash and hash scope are logged by ProbeCatalogGenerator.GenerateCatalog above");
        }

        /// <summary>
        /// Absolute Unity project root. <c>Application.dataPath</c> ends in <c>/Assets</c>, which is reliable in
        /// batchmode; the process working directory is not guaranteed to be the project.
        /// </summary>
        private static string ProjectRoot()
        {
            string dataPath = Application.dataPath.TrimEnd('/', '\\');
            string? root = Path.GetDirectoryName(dataPath);
            if (string.IsNullOrEmpty(root))
            {
                throw new InvalidOperationException(
                    "cannot derive the project root from Application.dataPath=" + Application.dataPath);
            }

            return root;
        }

        /// <summary>
        /// Creates the empty bootstrap scene when it is absent. The scene is generated through the Editor API so
        /// it always matches this Editor's scene serialization rather than a hand-written YAML file.
        /// </summary>
        private static void EnsureBootstrapScene()
        {
            string absoluteScenePath = Path.Combine(ProjectRoot(), ScenePath);
            if (File.Exists(absoluteScenePath))
            {
                Debug.Log("[GC001] bootstrap scene present at " + ScenePath);
                return;
            }

            string? directory = Path.GetDirectoryName(absoluteScenePath);
            if (!string.IsNullOrEmpty(directory))
            {
                Directory.CreateDirectory(directory);
            }

            Scene scene = EditorSceneManager.NewScene(NewSceneSetup.EmptyScene, NewSceneMode.Single);
            // SaveScene resolves a project-relative path against the project root, so pass ScenePath here.
            if (!EditorSceneManager.SaveScene(scene, ScenePath))
            {
                throw new InvalidOperationException("failed to save the bootstrap scene to " + ScenePath);
            }

            AssetDatabase.Refresh();
            Debug.Log(
                "[GC001] generated empty bootstrap scene " + ScenePath
                + "; the probe itself runs from RuntimeInitializeOnLoadMethod and needs no scene content");
        }

        private static void Exit(int code)
        {
            Debug.Log("[GC001] exiting with code " + code + "; batchMode=" + Application.isBatchMode);
            if (Application.isBatchMode)
            {
                EditorApplication.Exit(code);
            }
            else if (code != 0)
            {
                throw new InvalidOperationException(
                    "BuildProbe failed with code " + code + " outside batch mode; see the log above.");
            }
        }
    }
}
