#nullable enable
using System;
using System.Globalization;
using System.IO;
using System.Security.Cryptography;
using System.Text;
using GameCore.Validation.Probe;
using UnityEditor;
using UnityEngine;

namespace GameCore.Validation.Editor
{
    /// <summary>
    /// Deterministic build-time catalog generator for the GC-001 qualification player. It emits
    /// <c>Assets/GameCore.Validation/Generated/ProbeCatalog.g.cs</c> with a direct plugin factory reference,
    /// a closed generic handler instantiation and the generic job registration that
    /// <c>docs/game-core/04-unity-integration.md</c> section 8 requires.
    ///
    /// Callable from batchmode with
    /// <c>-executeMethod GameCore.Validation.Editor.ProbeCatalogGenerator.GenerateCatalog</c>.
    /// Output is byte-reproducible: fixed declaration order, no timestamps, no machine paths, LF line endings.
    /// </summary>
    public static class ProbeCatalogGenerator
    {
        /// <summary>Project-relative output path of the generated catalog.</summary>
        public const string RelativeOutputPath = "Assets/GameCore.Validation/Generated/ProbeCatalog.g.cs";

        /// <summary>
        /// Declaration text that starts the catalog hash constant. The hash input is exactly the file prefix that
        /// ends immediately before this text, which is why the hash line is emitted last inside the class and why
        /// the generated file records that scope beside the value.
        /// </summary>
        private const string HashDeclaration = "        public const string CatalogFileHash = ";

        /// <summary>
        /// The complete generated file. Placeholders are replaced in a fixed order; the catalog hash is computed
        /// over the substituted text that precedes <see cref="HashDeclaration"/> and substituted last, so the
        /// file cannot contain its own finished hash.
        /// </summary>
        private const string Template = @"// <auto-generated />
// Generated by GameCore.Validation.Editor.ProbeCatalogGenerator; do not edit by hand.
// Sources of truth: Assets/GameCore.Validation/Abstractions/ProbeKeys.cs (stable key literals) and
// Assets/GameCore.Validation/Plugin/FixturePlugin.cs (direct factory reference).
// Deterministic output: fixed declaration order, no timestamps, no machine paths, LF line endings.
// Regenerating from the same ProbeKeys literals must reproduce this file byte for byte.

#nullable enable
using GameCore.Validation.Fixture;
using GameCore.Validation.Probe;
using Unity.Jobs;

// Closed generic job instantiation rooted at build time (docs/game-core/04-unity-integration.md section 8).
[assembly: RegisterGenericJobType(typeof(ProbeAggregateJob<ProbeVector3Value>))]

namespace GameCore.Validation.Generated
{
    /// <summary>
    /// Generated closed registration catalog for the GC-001 qualification player. Plugin factories, the closed
    /// generic handler instantiation and the generic job registration above are direct references, so managed
    /// stripping cannot remove a registration that the player resolves by key at runtime.
    /// </summary>
    public static class ProbeCatalog
    {
        /// <summary>File name this catalog was generated into.</summary>
        public const string GeneratedFileName = ""ProbeCatalog.g.cs"";

        /// <summary>Hash algorithm used by CatalogFileHash.</summary>
        public const string HashAlgorithm = ""SHA-256"";

        /// <summary>Exact scope of CatalogFileHash, so the recorded value can be reproduced independently.</summary>
        public const string CatalogFileHashScope = ""SHA-256 over the UTF-8 bytes, with LF line endings, of the file prefix that ends immediately before the eight-space-indented CatalogFileHash declaration; that prefix ends with the newline that terminates the previous line, and the declaration itself, its value and the rest of the file are excluded"";

        /// <summary>Stable name of the linked-but-inactive fixture plugin registration.</summary>
        public const string FixturePluginStableName = ""gamecore.validation.plugin.fixture"";

        /// <summary>Stable name of the closed generic handler registration.</summary>
        public const string ClosedGenericHandlerStableName = ""gamecore.validation.handler.magnitude"";

        /// <summary>True because the generic job registration in this file is emitted with the catalog.</summary>
        public const bool HasGenericJobRegistration = true;

        /// <summary>Generated key of the linked-but-inactive fixture plugin.</summary>
        private static readonly ProbeKey FixturePluginKey = new ProbeKey(0x@@FIXTURE_HIGH@@UL, 0x@@FIXTURE_LOW@@UL);

        /// <summary>Generated key of the closed generic handler.</summary>
        private static readonly ProbeKey ClosedGenericHandlerKey = new ProbeKey(0x@@HANDLER_HIGH@@UL, 0x@@HANDLER_LOW@@UL);

        /// <summary>Plugin factory registrations. Ordered by key; one entry per generated plugin.</summary>
        private static readonly ProbePluginRegistration[] PluginRegistrations =
        {
            new ProbePluginRegistration(FixturePluginKey, FixturePluginStableName, new FixturePluginFactory()),
        };

        /// <summary>Closed generic handler registrations. Ordered by key; one entry per generated handler.</summary>
        private static readonly ProbeHandlerRegistration[] HandlerRegistrations =
        {
            new ProbeHandlerRegistration(
                ClosedGenericHandlerKey,
                ClosedGenericHandlerStableName,
                new ProbeScalarHandler<ProbeAmount>(ClosedGenericHandlerKey)),
        };

        /// <summary>Registered plugin keys, ordered by key.</summary>
        public static readonly ProbeKey[] PluginKeys = { FixturePluginKey };

        /// <summary>Registered handler keys, ordered by key.</summary>
        public static readonly ProbeKey[] HandlerKeys = { ClosedGenericHandlerKey };

        /// <summary>Number of generated plugin registrations.</summary>
        public static int PluginRegistrationCount => PluginRegistrations.Length;

        /// <summary>Number of generated closed generic handler registrations.</summary>
        public static int HandlerRegistrationCount => HandlerRegistrations.Length;

        /// <summary>
        /// Resolves a plugin factory by generated key. A key absent from this catalog returns false with a null
        /// factory; it is never constructed by reflection or by runtime type discovery.
        /// </summary>
        public static bool TryGetPluginFactory(ProbeKey key, out IProbePluginFactory? factory)
        {
            for (int i = 0; i < PluginRegistrations.Length; i++)
            {
                if (PluginRegistrations[i].Key.Equals(key))
                {
                    factory = PluginRegistrations[i].Factory;
                    return true;
                }
            }

            factory = null;
            return false;
        }

        /// <summary>
        /// Resolves a closed generic handler by generated key. A key absent from this catalog returns false with
        /// a null handler.
        /// </summary>
        public static bool TryGetHandler(ProbeKey key, out IProbeHandler<ProbeAmount, int>? handler)
        {
            for (int i = 0; i < HandlerRegistrations.Length; i++)
            {
                if (HandlerRegistrations[i].Key.Equals(key))
                {
                    handler = HandlerRegistrations[i].Handler;
                    return true;
                }
            }

            handler = null;
            return false;
        }

        /// <summary>
        /// Roots the closed generic instantiations this catalog depends on, so the IL2CPP player contains them
        /// even when no other reachable code calls them.
        /// </summary>
        public static ProbeKey RootClosedGenericInstantiations()
        {
            ProbeAotRoots.TrackJob(default(ProbeAggregateJob<ProbeVector3Value>));
            ProbeAotRoots.TrackHandler(HandlerRegistrations[0].Handler);
            return HandlerRegistrations[0].Handler.HandlerKey;
        }

        /// <summary>Hash of the generated source that precedes this declaration.</summary>
        public const string CatalogFileHash = ""@@CATALOG_HASH@@"";
    }
}
";

        /// <summary>
        /// Batchmode entry point. Throws on any inconsistency so a failing generation produces a nonzero Editor
        /// exit code instead of a silently stale catalog.
        /// </summary>
        public static void GenerateCatalog()
        {
            if (!ProbeKeys.DerivationHolds())
            {
                throw new InvalidOperationException(
                    "ProbeKeys literals do not match the documented derivation "
                    + "ProbeKey.FromStableName(stable name); refusing to generate a catalog with unverifiable keys.");
            }

            string text = RenderCatalog();
            if (text != RenderCatalog())
            {
                throw new InvalidOperationException(
                    "catalog generation is not deterministic; two renders of the same input differ.");
            }

            string path = Path.Combine(ProjectRoot(), RelativeOutputPath);
            string? directory = Path.GetDirectoryName(path);
            if (string.IsNullOrEmpty(directory))
            {
                throw new InvalidOperationException("cannot resolve the directory of " + path);
            }

            Directory.CreateDirectory(directory);
            bool existed = File.Exists(path);
            bool unchanged = existed && string.Equals(File.ReadAllText(path), text, StringComparison.Ordinal);
            if (!unchanged)
            {
                File.WriteAllText(path, text, new UTF8Encoding(false));
            }

            Debug.Log(
                "[GC001] generated catalog " + RelativeOutputPath + " ("
                + (unchanged ? "unchanged" : existed ? "regenerated" : "created")
                + "); bytes=" + Encoding.UTF8.GetByteCount(text)
                + "; catalogFileHash=" + ExtractHash(text)
                + "; hashScope=" + ExtractedHashScope(text));
            AssetDatabase.Refresh();
        }

        /// <summary>Renders the complete generated file, including the prefix hash.</summary>
        public static string RenderCatalog()
        {
            string substituted = Template
                .Replace("@@FIXTURE_HIGH@@", Hex(ProbeKeys.FixturePlugin.High))
                .Replace("@@FIXTURE_LOW@@", Hex(ProbeKeys.FixturePlugin.Low))
                .Replace("@@HANDLER_HIGH@@", Hex(ProbeKeys.ClosedGenericHandler.High))
                .Replace("@@HANDLER_LOW@@", Hex(ProbeKeys.ClosedGenericHandler.Low));

            int marker = substituted.IndexOf(HashDeclaration, StringComparison.Ordinal);
            if (marker < 0)
            {
                throw new InvalidOperationException(
                    "the catalog template no longer contains the CatalogFileHash declaration line.");
            }

            string hashInput = substituted.Substring(0, marker);
            return substituted.Replace("@@CATALOG_HASH@@", Sha256Hex(hashInput));
        }

        private static string ExtractHash(string text)
        {
            int start = text.IndexOf(HashDeclaration, StringComparison.Ordinal);
            if (start < 0)
            {
                return "missing";
            }

            int firstQuote = text.IndexOf('"', start);
            int secondQuote = firstQuote < 0 ? -1 : text.IndexOf('"', firstQuote + 1);
            return firstQuote < 0 || secondQuote < 0 ? "malformed" : text.Substring(firstQuote + 1, secondQuote - firstQuote - 1);
        }

        private static string ExtractedHashScope(string text)
        {
            const string prefix = "        public const string CatalogFileHashScope = \"";
            int start = text.IndexOf(prefix, StringComparison.Ordinal);
            if (start < 0)
            {
                return "missing";
            }

            int begin = start + prefix.Length;
            int end = text.IndexOf('"', begin);
            return end < 0 ? "malformed" : text.Substring(begin, end - begin);
        }

        /// <summary>
        /// Absolute Unity project root. <c>Application.dataPath</c> ends in <c>/Assets</c>, which is reliable in
        /// batchmode; the process working directory is not guaranteed to be the project.
        /// </summary>
        private static string ProjectRoot()
        {
            string dataPath = Application.dataPath.TrimEnd('/', '\\');
            string? root = Path.GetDirectoryName(dataPath);
            if (string.IsNullOrEmpty(root))
            {
                throw new InvalidOperationException(
                    "cannot derive the project root from Application.dataPath=" + Application.dataPath);
            }

            return root;
        }

        private static string Hex(ulong value) => value.ToString("X16", CultureInfo.InvariantCulture);

        private static string Sha256Hex(string content)
        {
            using (SHA256 sha256 = SHA256.Create())
            {
                byte[] hash = sha256.ComputeHash(new UTF8Encoding(false).GetBytes(content));
                var builder = new StringBuilder(hash.Length * 2);
                for (int i = 0; i < hash.Length; i++)
                {
                    builder.Append(hash[i].ToString("x2", CultureInfo.InvariantCulture));
                }

                return builder.ToString();
            }
        }
    }
}
